const accountGrades=['年長',...Array.from({length:6},(_,i)=>`小学${i+1}年`),...Array.from({length:3},(_,i)=>`中学${i+1}年`)];
function accountScreen(title,body){$('#app').innerHTML=`${header()}<main class="wrap account-page"><section class="card"><h1>${title}</h1>${body}</section></main>`;}
function passwordFields(){return `<label class="field">パスワード（8〜128文字）<input name="password" type="password" autocomplete="new-password" minlength="8" maxlength="128" required></label><label class="field">パスワード（確認）<input name="password_confirm" type="password" autocomplete="new-password" minlength="8" maxlength="128" required></label>`;}
function registrationPage(){accountScreen('新規登録',`<p>管理者から案内された登録コードを入力してください。選手1人につき保護者3人まで登録でき、管理者の承認後にログインできます。</p><form onsubmit="registerAccount(event)">${field('管理者から案内された登録コード','invite_code','')}${field('選手名','player_name','')}${field('保護者名','parent_name','')}${field('電話番号','phone','','tel',false)}${selectField('学年','grade',accountGrades,'小学1年')}${field('メールアドレス（登録完了通知・パスワード再設定用）','email','','email')}<label class="field">登録完了のお知らせ方法<select name="notification" onchange="toggleRegistrationLine(this)"><option value="email">メール</option><option value="line">LINE</option></select></label><label class="field" id="registration-line" hidden>LINE ID<input name="line_id" maxlength="100" disabled><small>LINE通知は接続準備中です。現在は希望する連絡先として保存します。</small></label>${!pub.account_mail_ready?'<p class="hint">通知メールは送信準備中です。承認状況は管理者へご確認ください。送信設定後に通知します。</p>':''}<label class="field">ログインID<input name="id" autocomplete="username" pattern="[A-Za-z0-9_-]{3,40}" minlength="3" maxlength="40" required><small>半角英数字・ハイフン・下線で3〜40文字</small></label>${passwordFields()}<p class="hint">ご家族が既に登録済みでも、同じ選手名で申請できます。IDは保護者ごとに別のものを設定してください。</p><div class="error" role="alert"></div><div class="registration-actions"><button class="lime">登録内容確認</button></div></form>`);setupRegistrationDemo();}
function registerAccount(ev){showRegistrationConfirmation(ev,'member');}
function forgotPasswordPage(){accountScreen('パスワードをお忘れの方',`<p>登録したIDとメールアドレスを入力してください。パスワード再設定用のリンクを送信します。</p>${!pub.account_mail_ready?'<p class="error">メール送信の準備中です。管理者へお問い合わせください。</p>':''}<form onsubmit="requestPasswordReset(event)">${field('ログインID','id','')}${field('登録メールアドレス','email','','email')}<div class="error" role="alert"></div><div class="toolbar"><a class="btn outline" href="#login">ログインに戻る</a><button class="lime" ${!pub.account_mail_ready?'disabled':''}>再設定メールを送る</button></div></form>`);}
async function requestPasswordReset(ev){ev.preventDefault();const b=ev.submitter;b.disabled=true;try{await api('password_reset_request',Object.fromEntries(new FormData(ev.target)));accountScreen('再設定メールのご案内','<p>登録内容と一致した場合、メールを送信しました。届いたリンクから30分以内に再設定してください。</p><a class="btn outline" href="#login">ログインへ</a>');}catch(e){ev.target.querySelector('.error').textContent=e.message;b.disabled=false;}}
function passwordResetPage(){const token=new URLSearchParams(location.hash.split('?')[1]||'').get('token');accountScreen('パスワードを再設定',token?`<form onsubmit="saveResetPassword(event)">${passwordFields()}<p>完了後、登録メールアドレスへ再設定完了のお知らせを送ります。</p><div class="error" role="alert"></div><button class="lime">新しいパスワードを保存</button></form>`:'<p>再設定メールのリンクから開いてください。</p><a class="btn outline" href="#forgot-password">再設定メールを申請</a>');}
async function saveResetPassword(ev){ev.preventDefault();const b=ev.submitter;b.disabled=true;try{await api('password_reset',{...Object.fromEntries(new FormData(ev.target)),token:new URLSearchParams(location.hash.split('?')[1]||'').get('token')});user=null;data={};history.replaceState(null,'','#login');accountScreen('再設定が完了しました','<p>新しいパスワードでログインしてください。登録アドレスへ完了通知を送ります。</p><a class="btn lime" href="#login">ログインへ</a>');}catch(e){ev.target.querySelector('.error').textContent=e.message;b.disabled=false;}}
function accountSetupPage(){if(!user){loginPage();return;}const p=data.account_self||{};accountScreen('登録情報の確認・変更',`<p>${esc(user.name)} ／ ログインID：${esc(user.login_display||user.login_id||user.id)}</p><form onsubmit="saveAccountProfile(event)">${field(user.role==='member'?'保護者名':'登録者名','parent_name',p.parent_name||'')}${field('メールアドレス（パスワード再設定用）','email',p.email||'','email')}<label class="field">現在のパスワード（本人確認）<input name="current_password" type="password" autocomplete="current-password" required></label><p class="hint">保存した登録情報は管理者の編集画面に反映されます。パスワード自体は表示されません。</p>${user.role==='member'?field('保護者の電話番号','phone',p.phone||'','tel',false):''}<div class="error" role="alert"></div><div class="toolbar"><a class="btn outline" href="#dashboard">ホームに戻る</a><button class="lime">変更を保存</button></div></form>`);}
async function saveAccountProfile(ev){ev.preventDefault();const b=ev.submitter;b.disabled=true;try{await api('account_profile',Object.fromEntries(new FormData(ev.target)));location.hash='dashboard';await refresh();toast('登録情報を保存しました。');}catch(e){ev.target.querySelector('.error').textContent=e.message;b.disabled=false;}}
function registrationApprovals(){const requests=data.accounts?.pending||[];return `<details class="card" ${requests.length?'open':''}><summary><b>新規登録の承認待ち（${requests.length}件）</b></summary>${!data.accounts?.admin_mail_ready?'<p class="hint">管理者への通知メール・LINEは送信準備中です。ここで申請を確認してください。</p>':''}${requests.map(r=>`<article class="staff-work-entry"><h3>${esc(r.player_name)} ／ ${esc(r.grade)}</h3><p>保護者：${esc(r.parent_name)}<br>ログインID：${esc(r.login_id)}<br>メール：${esc(r.email)}<br>お知らせ方法：${r.notification==='line'?'LINE ／ ID：'+esc(r.line_id):'メール'}</p><button class="lime" onclick="registrationReviewForm('${esc(r.login_id)}')">確認・承認</button></article>`).join('')||'<p>承認待ちはありません。</p>'}</details>`;}
function registrationReviewForm(id){const r=data.accounts.pending.find(r=>r.login_id===id),member=data.users.find(u=>u.id===r.student_id);modal('保護者の登録を確認',`<form onsubmit="reviewRegistration(event,'${esc(id)}')"><p>登録済みの選手：<b>${esc(member?.name||r.player_name)}</b><br>保護者：${esc(r.parent_name)}<br>学年：${esc(r.grade)}<br>ID：${esc(r.login_id)}<br>メール：${esc(r.email)}<br>お知らせ方法：${r.notification==='line'?'LINE ／ ID：'+esc(r.line_id):'メール'}</p><p class="hint">保護者とメールアドレスを確認してから承認してください。登録コードの対象選手に紐づきます。</p><div class="error" role="alert"></div><div class="toolbar"><button class="lime">承認して登録</button><button class="outline" type="button" onclick="rejectRegistration('${esc(id)}')">申請を却下</button></div></form>`);}
async function reviewRegistration(ev,id){ev.preventDefault();await submit(ev,'account_review',{login_id:id,action:'approve'},'登録を承認しました。');}
async function rejectRegistration(id){if(!confirm('この登録申請を却下しますか？'))return;try{await api('account_review',{login_id:id,action:'reject'});$('#modal').close();await refresh();toast('申請を却下しました。');}catch(e){toast(e.message);}}
function accountCredentialsPanel(uid){const list=(data.accounts?.items||[]).filter(a=>a.student_id===uid);if(!list.length)return '<p class="hint">保護者の新規登録・管理者承認後、ここにログイン情報が表示されます。</p>';return `<fieldset class="card"><legend>登録済みのログイン情報${data.users.find(u=>u.id===uid)?.role==='member'?'（最大3件）':''}</legend>${list.map(a=>`<div class="staff-work-entry"><b>ID：${esc(a.login_display||a.login_id)}</b><p>${esc(a.parent_name||'登録者名：初回設定待ち')}<br>${esc(a.email||'メール：未登録')}<br>お知らせ方法：${a.notification==='line'?'LINE ／ ID：'+esc(a.line_id):'メール'}</p><p>パスワード：設定済み（非表示）<br>再設定日時：${esc(a.reset_at||'未実施')}</p></div>`).join('')}</fieldset>`;}

function memberRegistrationStatus(m){return `<span class="tag">${data.accounts?.access?.[m.id]!==false?'承認':'未承認'}</span>`;}
function memberRegistrationControls(m){const approved=data.accounts?.access?.[m.id]!==false;return `<button class="${approved?'outline':'lime'} small" onclick="memberApprovalForm('${esc(m.id)}',${!approved})">${approved?'未承認に戻す':'承認'}</button>`;}
function memberApprovalForm(id,approved){const m=data.users.find(u=>u.id===id),pending=(data.accounts?.pending||[]).filter(a=>a.student_id===id);modal(approved?'会員のログインを承認':'ログインを未承認に戻す',`<p><b>${esc(m.name)}</b></p>${approved?'<p>申請内容を確認し、この選手の保護者ログインを承認します。</p>'+pending.map(a=>`<p>${esc(a.parent_name)} ／ ID：${esc(a.login_display||a.login_id)}<br>${esc(a.email)}</p>`).join(''):'<p>この選手に紐づくログインを停止します。承認すると再び利用できます。</p>'}<form onsubmit="setMemberApproval(event,'${esc(id)}',${approved})"><div class="error" role="alert"></div><button class="lime">${approved?'承認する':'未承認に戻す'}</button></form>`);}
async function setMemberApproval(ev,id,approved){ev.preventDefault();await submit(ev,'member_approval',{user_id:id,approved},approved?'承認しました。':'未承認に戻しました。');}
async function removeMember(id){const m=data.users.find(u=>u.id===id);if(!confirm(m.name+'を会員一覧から削除し、ログインを停止しますか？出欠・会費などの過去の履歴は保持します。'))return;try{await api('member_remove',{user_id:id});await refresh();toast('会員一覧から削除しました。');}catch(e){toast(e.message);}}
function memberInvitePanel(id){const code=data.accounts?.invites?.[id];return code?`<section class="card"><h3>保護者の新規登録コード</h3><p><code>${esc(code)}</code></p><p class="hint">このコードと新規登録画面のURLを保護者へ案内してください。登録後、管理者の承認が必要です。</p><a class="btn outline small" href="#register" target="_blank" rel="noopener">新規登録画面を開く</a></section>`:'';}

function toggleRegistrationLine(select){const label=select.form.querySelector("#registration-line"),input=label.querySelector("input"),show=select.value==="line";label.hidden=!show;input.disabled=!show;input.required=show;}

function memberGuardianList(m){const parents=[...(data.accounts?.items||[]),...(data.accounts?.pending||[])].filter(a=>a.student_id===m.id);return `<div class="member-guardians">${parents.map(a=>`<div class="member-guardian"><div><b>${esc(a.parent_name||'保護者名未登録')}</b><div>ID：${esc(a.login_display||a.login_id)}</div><div>PW：設定済み（非表示）</div>${a.status==='pending'?'<small>承認待ち</small>':''}</div><button type="button" class="outline small" data-student="${esc(m.id)}" data-login="${esc(a.login_id)}" onclick="editGuardian(this.dataset.student,this.dataset.login)" aria-label="${esc(a.parent_name||a.login_id)}の保護者情報を編集">編集</button></div>`).join('')||'<span class="hint">保護者未登録</span>'}</div>`;}
async function removeGuardian(student,id){if(!confirm('この保護者の登録を削除します。ログインできなくなり、新しい保護者を登録できる枠が1人分空きます。選手の記録は残ります。'))return;try{await api('guardian_remove',{user_id:student,login_id:id});await refresh();const panel=document.querySelector('#modal .member-form-guardians .member-guardians'),member=data.users.find(m=>m.id===student);if(member)closeGuardianEdit(student);toast('保護者の登録を削除しました。');}catch(e){toast(e.message);}}

function editGuardian(student,id){const a=[...(data.accounts?.items||[]),...(data.accounts?.pending||[])].find(x=>x.login_id===id);if(!a)return;const section=document.querySelector('#modal .member-form-guardians');section.innerHTML=`<h3>保護者情報を編集</h3><p>ID：${esc(id)} ／ PW：設定済み（非表示）</p><label class="field">保護者名<input data-guardian="parent_name" maxlength="100" value="${esc(a.parent_name||'')}"></label><label class="field">メールアドレス<input data-guardian="email" type="email" value="${esc(a.email||'')}"></label><label class="field">電話番号<input data-guardian="phone" type="tel" autocomplete="tel" value="${esc(a.phone||'')}"></label><p class="hint">ログインIDは変更できません。パスワードはログイン画面から再設定します。</p><div class="error" role="alert"></div><div class="toolbar"><button type="button" class="lime" data-student="${esc(student)}" data-login="${esc(id)}" onclick="saveGuardianEdit(this)">保護者情報を保存</button><button type="button" class="outline" data-student="${esc(student)}" onclick="closeGuardianEdit(this.dataset.student)">閉じる</button><button type="button" class="outline" data-student="${esc(student)}" data-login="${esc(id)}" onclick="removeGuardian(this.dataset.student,this.dataset.login)">保護者登録を削除</button></div>`;}
function closeGuardianEdit(student){const m=data.users.find(x=>x.id===student),section=document.querySelector('#modal .member-form-guardians');if(m&&section)section.innerHTML='<h3>保護者情報</h3>'+memberGuardianList(m);}
async function saveGuardianEdit(button){const section=button.closest('.member-form-guardians'),payload={user_id:button.dataset.student,login_id:button.dataset.login};section.querySelectorAll('[data-guardian]').forEach(input=>payload[input.dataset.guardian]=input.value);button.disabled=true;try{await api('guardian_update',payload);await refresh();closeGuardianEdit(payload.user_id);toast('保護者情報を保存しました。');}catch(e){section.querySelector('.error').textContent=e.message;button.disabled=false;}}

function adminAccessPanel(){return `<details class="card"><summary><b>コーチの種類・権限設定</b></summary><p>コーチごとに非表示・閲覧のみ・編集可能を設定します。種類を選ぶと初期設定が切り替わります。</p>${(data.coach_accounts||[]).map(a=>`<div class="info-row"><span>${esc(a.name)} ／ ${esc(a.kind)}</span><button class="outline small" data-id="${esc(a.id)}" onclick="coachAccessForm(this.dataset.id)">種類・権限を設定</button></div>`).join('')}</details>`;}
function coachAccessForm(id){const a=data.coach_accounts.find(a=>a.id===id);modal('コーチの種類・権限を設定',`<form onsubmit="saveCoachAccess(event,'${esc(id)}',${a.revision})"><h3>${esc(a.name)}</h3>${selectField('コーチの種類','kind',[['閲覧中心','閲覧中心'],['運営コーチ','運営コーチ'],['個別設定','個別設定']],a.kind==='標準コーチ'?'個別設定':a.kind).replace('<select ','<select onchange="coachPermissionPreset(this)" ')}<p>「編集可能」の項目では登録・変更ができます。勤怠管理は本人分のみ表示します。</p>${adminManagementLinks.filter(([key])=>!['staff-approvals','attendance-rates','basket-note-settings'].includes(key)).map(([key,icon,label])=>selectField(label,'permission_'+key,[['none','非表示'],['view','閲覧のみ'],['edit','編集可能']],a.permissions[key]||'none')).join('')}<div class="error" role="alert"></div><button class="lime">権限を保存</button></form>`);}
function coachPermissionPreset(select){if(select.value==='個別設定')return;const standard=['schedule','attendance-list','conditioning','results','announcement-admin','survey-admin','shop-admin','board-admin','members','staff-members','worksheets'];select.form.querySelectorAll('[name^=permission_]').forEach(el=>{el.value=standard.includes(el.name.replace('permission_',''))?(select.value==='運営コーチ'?'edit':'view'):'none';});}
async function saveCoachAccess(ev,id,revision){ev.preventDefault();const f=new FormData(ev.target);try{await api('coach_access',{id,revision,kind:f.get('kind'),permissions:Object.fromEntries(adminManagementLinks.filter(([key])=>!['staff-approvals','attendance-rates','basket-note-settings'].includes(key)).map(([key])=>[key,f.get('permission_'+key)]))});$('#modal').close();await refresh();toast('コーチの種類・権限を保存しました。');}catch(e){ev.target.querySelector('.error').textContent=e.message;}}
function resetCredentialForm(uid,account=''){const choices=(data.credential_accounts||[]).filter(a=>a.user_id===uid),m=data.users.find(m=>m.id===uid),a=choices.find(a=>a.account_id===account)||choices[0];if(!a){toast('登録済みのログインがありません。先に保護者の新規登録が必要です。');return;}modal('ログインID・PWを再設定',`<form onsubmit="resetCredentials(event,'${esc(uid)}','${esc(a.account_id)}')"><h3>${esc(m?.name||'')}</h3>${selectField('再設定するログイン','account',choices.map(x=>[x.account_id,(x.name||'保護者')+' ／ '+x.login_id]),a.account_id).replace('<select ',`<select onchange="resetCredentialForm('${esc(uid)}',this.value)" `)}${field('新しいログインID','login_id',a.login_id)}${field('新しいパスワード（8文字以上）','password','','password')}${field('新しいパスワードを再入力','password_confirm','','password')}<p class="hint">保存すると、旧ID・パスワードでのログインと既存のログイン状態を無効にします。会員の記録は引き継ぎます。新しい情報を本人へ案内してください。</p><div class="error" role="alert"></div><button class="lime">再設定する</button></form>`);}
async function resetCredentials(ev,user_id,account_id){ev.preventDefault();ev.submitter.disabled=true;const a=data.credential_accounts.find(a=>a.account_id===account_id),f=new FormData(ev.target);try{await api('reset_credentials',{user_id,account_id,revision:a.revision,login_id:f.get('login_id'),password:f.get('password'),password_confirm:f.get('password_confirm')});$('#modal').close();await refresh();toast('ログイン情報を再設定しました。');}catch(e){ev.target.querySelector('.error').textContent=e.message;}finally{ev.submitter.disabled=false;}}

function reportTemplatePage(kind){const template=data.report_templates?.[kind];if(!template)return '<p>設定を読み込んでいます。ページを再読み込みしてください。</p>';return heading(kind==='condition'?'体調報告編集':'怪我報告設定','質問文と選択肢を編集します。保存済みの回答は変更されません。')+`<form class="card report-template-form" onsubmit="saveReportTemplate(event,'${kind}',${template.revision})">${template.questions.map(q=>`<fieldset data-question-id="${esc(q.id)}"><legend>${esc(q.label)}</legend>${field('質問文','label',q.label)}${q.type==='select'?`<label class="field">選択肢（1行に1つ）<textarea name="options" required>${esc(q.options.join('\n'))}</textarea></label>`:''}</fieldset>`).join('')}<p class="hint">出欠・体調一覧との連携を保つため、項目の種類は固定です。質問文と選択肢を変更できます。</p><div class="error" role="alert"></div><button class="lime" type="submit">設定を保存する</button></form>`;}
async function saveReportTemplate(ev,kind,revision){ev.preventDefault();ev.submitter.disabled=true;try{const questions=[...ev.target.querySelectorAll('[data-question-id]')].map(el=>({id:el.dataset.questionId,label:el.querySelector('[name=label]').value,options:el.querySelector('[name=options]')?.value.split('\n').map(v=>v.trim()).filter(Boolean)||[]}));await api('report_template',{kind,revision,questions});await refresh();toast('質問・選択肢を保存しました。');}catch(e){ev.target.querySelector('.error').textContent=e.message;ev.submitter.disabled=false;}}
function reportQuestions(kind){return data.report_templates?.[kind]?.questions||[];}
function reportInput(q,value='',required=false){if(q.type==='select')return selectField(q.label,q.id,[['','選択してください'],...q.options.map(x=>[x,x])],value);if(q.type==='textarea')return `<label class="field">${esc(q.label)}<textarea name="${esc(q.id)}" maxlength="2000" ${required?'required':''}>${esc(value)}</textarea></label>`;return field(q.label,q.id,value,q.type,required);}
function coachRegistrationPage(){accountScreen('コーチ新規登録',`<p>管理者から案内された登録コードで申請してください。管理者の承認後にログインできます。</p><form onsubmit="submitCoachRegistration(event)">${field('登録コード','code')}${field('氏名','name')}${field('メールアドレス','email','','email')}${field('ログインID','id')}${passwordFields()}<p class="hint">メール通知は送信サービスの接続後に利用できます。</p><div class="error" role="alert"></div><div class="registration-actions"><button class="lime">登録内容確認</button></div></form>`);setupRegistrationDemo();}
function submitCoachRegistration(ev){showRegistrationConfirmation(ev,'coach');}
function coachRegistrationPanel(){return `<details class="card"><summary><b>コーチ新規登録・承認</b></summary>${data.users.filter(u=>u.role==='coach').map(u=>{const r=data.coach_registrations?.find(r=>r.user_id===u.id);return `<div class="card"><b>${esc(u.name)}</b><p>${r?esc(({invited:'登録待ち',pending:'承認待ち',approved:'承認済み',rejected:'申請差し戻し'})[r.status]):'登録コード未発行'}</p>${r&&r.status!=='approved'?`<p>登録コード：<code>${esc(r.code)}</code></p>`:''}${r?.status==='pending'?`<p>希望ログインID：${esc(r.login_id)}</p><button type="button" class="lime" data-id="${esc(u.id)}" onclick="manageCoachRegistration(this,'approve')">承認する</button> <button type="button" class="outline" data-id="${esc(u.id)}" onclick="manageCoachRegistration(this,'reject')">差し戻す</button>`:`<button type="button" class="outline" data-id="${esc(u.id)}" onclick="manageCoachRegistration(this,'invite')">登録コードを発行</button>`}</div>`}).join('')}</details>`;}
async function manageCoachRegistration(button,action){button.disabled=true;try{await api('coach_registration',{action,user_id:button.dataset.id});await refresh();toast('更新しました。');}catch(e){toast(e.message);button.disabled=false;}}
function officerAccessPanel(){return `<details class="card"><summary><b>役員ごとの管理画面の権限</b></summary>${(data.officer_accounts||[]).map(a=>`<div class="info-row"><b>${esc(a.name)}（${a.year}年度）</b><button class="outline" data-id="${esc(a.id)}" onclick="officerAccessForm(this.dataset.id)">権限を設定</button></div>`).join('')}</details>`;}
function officerAccessForm(id){const a=data.officer_accounts.find(a=>a.id===id);modal('役員の管理画面の権限',`<form onsubmit="saveOfficerAccess(event,'${esc(id)}',${a.revision})"><h3>${esc(a.name)}</h3><p>許可した項目だけメニューに追加されます。会計の操作は担当年度に限ります。</p>${adminManagementLinks.filter(([k])=>!['finance-admin','basket-note-settings','attendance-rates'].includes(k)).map(([k,i,label])=>selectField(label,'permission_'+k,[['none','追加しない'],['view','閲覧のみ'],['edit','編集可能']],a.permissions[k]||'none')).join('')}<div class="error" role="alert"></div><button class="lime">権限を保存</button></form>`);}
async function saveOfficerAccess(ev,id,revision){ev.preventDefault();const permissions=Object.fromEntries([...new FormData(ev.target)].map(([k,v])=>[k.replace('permission_',''),v]));try{await api('officer_access',{id,revision,permissions});$('#modal').close();await refresh();toast('役員の権限を保存しました。');}catch(e){ev.target.querySelector('.error').textContent=e.message;}}
function delegatedNavigationLinks(){const base=user.delegated_officer?[['finance-admin','¥','会計・収支報告']]:[['schedule','▦','練習・試合日程'],['attendance-list','✓','出欠・体調報告'],['attendance-rates','▥','出席率'],['results','◷','試合結果・動画'],['skill-videos','▷','スキルアップ動画'],['basket-notes','▤','バスケノート'],['worksheets','▤','ワークシート'],['members','♧','会員一覧'],['staff-members','♧','スタッフ一覧']];return [...(user.delegated_coach?[['excel','⇩','コーチ・スタッフ勤怠管理']]:[]),...base.filter(([k])=>adminCan(adminSection(k))),...adminManagementLinks.filter(([k])=>!base.some(([b])=>b===k)&&['view','edit'].includes((user.assigned_permissions||user.admin_permissions)[adminSection(k)]))];}
function initStaffPermissions(m){const form=$('#modal form'),a=data.coach_accounts?.find(a=>a.id===m.id),select=form.elements.role;form.staffPermissions={...(a?.permissions||{})};form.staffPermissionRevision=a?.revision||0;const result=document.createElement('div');result.className='staff-permission-result';result.style.gridColumn='1 / -1';select.closest('label').insertAdjacentElement('afterend',result);if(m.id==='admin01'||m.id===user.id){select.disabled=true;const hidden=document.createElement('input');hidden.type='hidden';hidden.name='role';hidden.value=m.role;form.append(hidden);result.textContent='全画面の閲覧・編集・削除が可能です。';return;}if(m.role==='admin'||Object.values(form.staffPermissions).some(v=>v==='edit'))select.value='admin';renderStaffPermissionResult(form);}
function renderStaffPermissionResult(form){const box=form.querySelector('.staff-permission-result');if(!box)return;const permitted=adminManagementLinks.filter(([k])=>form.staffPermissions?.[k]==='edit');box.innerHTML=`<p>編集できる画面：${permitted.map(x=>esc(x[2])).join('、')||'未選択'}</p><button type="button" class="outline" onclick="openStaffPermissionPicker(this.form)">編集できる画面を選択</button>`;box.hidden=form.elements.role.value!=='admin';}
function staffRoleChanged(select){if(page!=='staff-members')return;renderStaffPermissionResult(select.form);if(select.value==='admin')openStaffPermissionPicker(select.form);}
function openStaffPermissionPicker(form){const dialog=document.createElement('dialog');dialog.className='staff-permission-picker';dialog.innerHTML=`<h2>編集できる管理画面</h2><p>チェックした項目だけ、スタッフのメニューに追加・編集を許可します。</p>${adminManagementLinks.filter(([k])=>!['basket-note-settings','attendance-rates','staff-approvals'].includes(k)).map(([k,i,label])=>`<label class="check-row"><input type="checkbox" value="${esc(k)}" ${form.staffPermissions?.[k]==='edit'?'checked':''}>${esc(label)}</label>`).join('')}<div class="dialog-actions"><button class="outline" type="button" data-cancel>キャンセル</button><button class="lime" type="button" data-apply>選択を反映</button></div>`;dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.querySelector('[data-apply]').onclick=()=>{form.staffPermissions=Object.fromEntries([...dialog.querySelectorAll('input:checked')].map(x=>[x.value,'edit']));renderStaffPermissionResult(form);dialog.close();};dialog.addEventListener('close',()=>dialog.remove(),{once:true});document.body.append(dialog);dialog.showModal();}
async function removeStaff(id){if(!await confirmAction('スタッフを削除しますか？','削除すると、このスタッフはログインできなくなります。過去の活動記録は保持します。'))return;try{await api('staff_remove',{user_id:id});await refresh();toast('スタッフを削除し、ログインを停止しました。');}catch(e){toast(e.message);}}

async function setupRegistrationDemo(){
 const form=document.querySelector('main form'),code=form?.querySelector('[name=invite_code],[name=code]');
 if(!code)return;
 try{const info=await api('registration_context');if(!form.isConnected)return;
  if(info.demo){code.required=false;const note=document.createElement('p');note.className='hint';note.textContent='デモアカウントでログイン中：登録コードを空欄にして登録できます。会員・コーチは管理者の承認後にログインできます。';code.closest('label').after(note);}
 }catch(e){/* Registration codes remain required if the context cannot be checked. */}
}
function showRegistrationConfirmation(ev,kind){
 ev.preventDefault();const form=ev.target,values=Object.fromEntries(new FormData(form));
 if(values.password!==values.password_confirm){form.querySelector('.error').textContent='確認用パスワードが一致しません。';return;}
 form.querySelector('.error').textContent='';
 const labels={invite_code:'登録コード',code:'登録コード',player_name:'選手名',parent_name:'保護者名',phone:'電話番号',grade:'学年',email:'メールアドレス',notification:'登録完了のお知らせ方法',line_id:'LINE ID',id:'ログインID',name:'氏名'};
 const rows=Object.entries(values).filter(([key])=>!key.startsWith('password')).map(([key,value])=>`<dt>${esc(labels[key]||key)}</dt><dd>${esc(key==='notification'?(value==='line'?'LINE':'メール'):value||'未入力')}</dd>`).join('');
 const panel=document.createElement('section');panel.className='registration-confirmation';
 panel.innerHTML=`<h2>登録内容確認</h2><dl class="registration-review-values">${rows}<dt>パスワード</dt><dd>入力済み（安全のため表示しません）</dd></dl><div class="error" role="alert"></div><div class="registration-actions"><button type="button" class="outline" data-correct>修正する</button><button type="button" class="lime" data-register>登録する</button></div>`;
 form.hidden=true;form.after(panel);
 panel.querySelector('[data-correct]').onclick=()=>{panel.remove();form.hidden=false;form.scrollIntoView({block:'start'});};
 panel.querySelector('[data-register]').onclick=async()=>{
  const buttons=panel.querySelectorAll('button');buttons.forEach(b=>b.disabled=true);
  try{await api({member:'register',coach:'coach_register',officer:'finance_register'}[kind],values);
   accountScreen('登録完了しました',`${kind==='officer'?'<p>設定したID・パスワードでログインできます。</p>':'<p>登録内容を受け付けました。管理者の承認後、設定したID・パスワードでログインできます。</p>'}<div class="registration-actions"><a class="btn lime" href="#login">ログイン</a></div>`);window.scrollTo(0,0);
  }catch(e){panel.querySelector('.error').textContent=e.message;buttons.forEach(b=>b.disabled=false);}
 };
 panel.scrollIntoView({block:'start'});
}

function enrollmentStatusText(r){if(!r)return '';return r.pause_pending?`${r.status}（${r.pause_date}から${r.scheduled_status}）`:r.status;}
function enrollmentStatusField(name,r){const target=r.scheduled_status||r.status||'在籍',selected=r.pause_mode==='scheduled'?'指定日'+target:target==='在籍'?'在籍':'即日'+target;return `<div class="enrollment-status-fields">${selectField('在籍状況',name,['在籍','即日休会','指定日休会','即日退会','指定日退会'],selected).replace('<select ','<select onchange="changeEnrollmentStatus(this)" ')}<input type="hidden" name="pause_date" value="${esc(r.pause_date||'')}"><div class="enrollment-date-summary" ${selected.startsWith('指定日')?'':'hidden'}><span>${esc(r.pause_date||'日付を選択してください')}</span> <button type="button" class="outline small" onclick="pickEnrollmentDate(this.closest('.enrollment-status-fields').querySelector('select'))">日付を変更</button></div></div>`;}
function changeEnrollmentStatus(select){const area=select.closest('.enrollment-status-fields');area.querySelector('.enrollment-date-summary').hidden=!select.value.startsWith('指定日');if(select.form.querySelector('[data-stop-reason]'))toggleEnrollmentReason(select.form);if(select.value.startsWith('指定日'))pickEnrollmentDate(select);else area.querySelector('[name=pause_date]').value='';}
function pickEnrollmentDate(select){const area=select.closest('.enrollment-status-fields'),value=area.querySelector('[name=pause_date]'),d=document.createElement('dialog');d.className='schedule-choice-dialog';const label=select.value.includes('退会')?'退会日':'休会開始日';d.innerHTML=`<h2>${label}を選択</h2><form><label class="field">${label}<input type="date" name="date" value="${esc(value.value)}" required></label><p class="hint">指定日の午前0時（日本時間）から適用します。</p><div class="registration-actions"><button type="button" class="outline" data-close>閉じる</button><button class="lime">この日付にする</button></div></form>`;d.querySelector('[data-close]').onclick=()=>d.close();d.querySelector('form').onsubmit=e=>{e.preventDefault();value.value=d.querySelector('[name=date]').value;area.querySelector('.enrollment-date-summary span').textContent=value.value;d.close();};d.addEventListener('close',()=>d.remove(),{once:true});document.body.append(d);d.showModal();}
