const financeAccountTypes=['一般会計','特別会計','NEW YEARチャレンジカップ','合宿'];
let financeAccountType='一般会計';
let financeImport=null,financeBusy=false;
const financeMoney=n=>Number(n||0).toLocaleString('ja-JP')+'円';
function accountingDashboard(){page='accounting';$('#app').innerHTML=`<main class="workspace accounting-workspace"><div class="workspace-top"><b>会計担当者：${esc(user.name)}</b><button class="outline" onclick="logout()">ログアウト</button></div>${financePage()}</main>`;}
function financePage(){const f=financeSection(data.finance);if(!f)return '<p>会計情報を読み込めません。</p>';const manage=adminFull(),edit=user.role==='accountant'||user.delegated_officer||(!user.delegated_officer&&adminCan('finance-admin',true));return heading(user.role==='admin'?'役員設定':'会計・収支報告',`${f.account_type} ／ ${f.year}年度（${f.year}年4月〜${f.year+1}年3月）`)+`${manage?financeAssignments(f)+officerAccessPanel():''}${selectField('会計区分','finance_section',['全て',...financeAccountTypes],financeAccountType).replace('<select ',"<select onchange=\"financeAccountType=this.value;dashboard()\" ")}${financeMemberReports(f,edit)}${financeTransportReports(f)}<label class="field">表示年度<select onchange="changeFinanceYear(this.value)">${f.years.map(y=>`<option ${y===f.year?'selected':''}>${y}</option>`).join('')}</select></label><div class="stats"><div class="stat">収入合計<strong>${financeMoney(f.income)}</strong></div><div class="stat">支出合計<strong>${financeMoney(f.expense)}</strong></div><div class="stat">当年度収支差額<strong>${financeMoney(f.balance)}</strong></div></div><p class="hint">繰越金は必要に応じて収入明細として登録してください。</p><div class="toolbar">${edit?'<button class="lime" onclick="financeImportForm()">PDF・CSV・写真を読み込む</button><button class="outline" onclick="financeEntryForm()">明細を追加</button>':''}<a class="btn outline" href="/basketball-club/api/finance_report?year=${f.year}${financeTypeQuery()}&format=xlsx">収支報告書 Excel</a><a class="btn outline" href="/basketball-club/api/finance_report?year=${f.year}${financeTypeQuery()}&format=pdf">収支報告書 PDF</a></div><p class="hint">保存した明細・備考は帳票にも反映されます。サーバーを動かしているPCの「data / 会計 / ${f.year}」へ、明細・領収書・Excel・PDFを自動保存します。</p><div class="finance-status" role="status"></div><div class="stack">${f.entries.map(r=>`<article class="card"><div class="toolbar"><b>${esc(r.date)}　${esc(r.direction)} ／ ${esc(r.category)}</b><strong>${financeMoney(r.amount)}</strong>${edit?`<button class="outline" onclick="financeEntryForm('${r.id}')">編集</button><button class="outline danger" onclick="deleteFinanceEntry('${r.id}')">削除</button>`:''}</div><p>${esc(r.description)}</p>${r.file_id?`<a class="text-link" href="/basketball-club/api/finance_file?year=${f.year}&id=${r.file_id}" target="_blank" rel="noopener">領収書・元ファイルを確認</a>`:''}<label class="field">備考<textarea ${edit?'':'readonly'} maxlength="3000" onchange="saveFinanceNote('${r.id}',this)">${esc(r.note)}</textarea><small class="hint" role="status">${edit?'入力後、欄の外を押すと自動保存します。':''}</small></label></article>`).join('')||'<div class="card">この年度の明細はありません。</div>'}</div>`;}
function financeAssignments(f){return `<details class="card"><summary><b>年度ごとの会計担当者</b></summary><p>担当者を登録し、専用の登録案内を本人へ渡してください。本人がID・パスワードを設定します。年度終了後はログインできなくなります。担当者を削除しても会計記録は残ります。</p><button class="lime" onclick="financeAssignmentForm()">会計担当者を追加</button>${f.assignments.filter(a=>a.active).map(a=>`<article class="staff-work-entry"><b>${esc(a.year)}年度 ／ ${esc(a.name)}</b><p>${a.login_id?'登録済み':'本人による登録待ち'}</p><div class="toolbar"><button class="outline" onclick="financeAssignmentForm('${a.id}')">編集</button><button class="outline danger" onclick="removeFinanceAssignment('${a.id}')">担当者を削除</button></div>${!a.login_id?`<label class="field">本人用の登録URL<input readonly value="${esc(location.origin+'/#finance-register?code='+encodeURIComponent(a.code))}" onclick="this.select()"></label>`:''}</article>`).join('')}</details>`;}
async function changeFinanceYear(year){try{data.finance=await api('finance_data?year='+encodeURIComponent(year));dashboard();}catch(e){toast(e.message);}}
function financeAssignmentForm(id=''){const a=data.finance.assignments.find(a=>a.id===id)||{year:data.finance.year};modal('会計担当者を設定',`<form onsubmit="saveFinanceAssignment(event,'${id}')">${field('担当者の氏名','name',a.name||'')}${field('会計年度（4月開始の年）','year',a.year,'number')}<p class="hint">年度の4月1日〜翌年3月31日に利用できます。削除済みの担当者は再登録してください。</p><div class="error" role="alert"></div><button class="lime">保存</button></form>`);}
async function saveFinanceAssignment(ev,id){ev.preventDefault();const f=new FormData(ev.target),a=data.finance.assignments.find(a=>a.id===id);try{await api('finance_assignment',{id,name:f.get('name'),year:Number(f.get('year')),revision:a?.revision});$('#modal').close();await changeFinanceYear(data.finance.year);}catch(e){ev.target.querySelector('.error').textContent=e.message;}}
async function removeFinanceAssignment(id){if(!confirm('この担当者のログイン権限を解除しますか？会計記録は残ります。'))return;const a=data.finance.assignments.find(a=>a.id===id);try{await api('finance_assignment',{id,delete:true,revision:a.revision});await changeFinanceYear(data.finance.year);}catch(e){toast(e.message);}}
function financeRegistrationPage(){const code=new URLSearchParams(location.hash.split('?')[1]||'').get('code')||'';$('#app').innerHTML=`${header()}<main class="section wrap"><h1>役員の登録</h1><p>管理者から受け取った登録案内を使い、ご自身のID・パスワードを設定してください。</p><form class="card" onsubmit="registerFinance(event)">${field('役員の登録コード','code',code)}${field('ログインID（半角英数字など3〜40文字）','id','')}${field('パスワード（8文字以上）','password','','password')}${field('パスワードを再入力','password_confirm','','password')}<div class="error" role="alert"></div><div class="registration-actions"><button class="lime">登録内容確認</button></div></form></main>`;setupRegistrationDemo();}
function registerFinance(ev){showRegistrationConfirmation(ev,'officer');}
function financeFields(r={}){const date=r.date??new Date().toLocaleDateString('sv-SE');return `${selectField('会計区分','account_type',financeAccountTypes,r.account_type||(financeAccountType==='全て'?'一般会計':financeAccountType))}<div class="form-grid">${field('日付','date',date,'date')}${selectField('収支','direction',['支出','収入'],r.direction||'支出')}${selectField('明細区分','category',[['','選んでください'],...data.finance.categories.map(c=>[c,c])],data.finance.categories.includes(r.category)?r.category:r.category?'':'その他支出')}${field('金額（円）','amount',r.amount??'','number')}</div>${field('摘要（店名・用途など）','description',r.description||'')}<label class="field">備考<textarea name="note" maxlength="3000">${esc(r.note||'')}</textarea></label>`;}
function financeEntryForm(id=''){const r=data.finance.entries.find(r=>r.id===id)||{};modal('会計明細を編集',`<form onsubmit="saveFinanceEntry(event,'${id}')">${financeFields(r)}<div class="error" role="alert"></div><button class="lime">保存</button></form>`);}
function financeValues(form){const f=new FormData(form);return {account_type:f.get('account_type'),date:f.get('date'),direction:f.get('direction'),category:f.get('category'),amount:f.get('amount')===''?null:Number(f.get('amount')),description:f.get('description'),note:f.get('note')};}
async function saveFinanceEntry(ev,id){ev.preventDefault();ev.submitter.disabled=true;try{const old=data.finance.entries.find(r=>r.id===id),result=await api('finance_entry',{...financeValues(ev.target),id,revision:old?.revision,year:data.finance.year});$('#modal').close();await changeFinanceYear(data.finance.year);toast(result.archive_error||'会計明細とローカル帳票を保存しました。');}catch(e){ev.target.querySelector('.error').textContent=e.message;}finally{ev.submitter.disabled=false;}}
async function saveFinanceNote(id,input){const row=data.finance.entries.find(r=>r.id===id),status=input.nextElementSibling;if(!row||row.note===input.value)return;input.disabled=true;status.textContent='保存中…';try{const r=await api('finance_entry',{...row,note:input.value});const fresh=await api('finance_data?year='+row.year);data.finance=fresh;status.textContent=r.archive_error||'備考とExcel・PDFを保存しました。';}catch(e){status.textContent='保存できませんでした：'+e.message;}finally{input.disabled=false;}}
async function deleteFinanceEntry(id){if(!confirm('この明細を削除しますか？'))return;try{const row=data.finance.entries.find(r=>r.id===id),r=await api('finance_entry',{id,year:row.year,revision:row.revision,delete:true});await changeFinanceYear(row.year);toast(r.archive_error||'明細を削除しました。');}catch(e){toast(e.message);}}
function financeImportForm(){financeImport={active:true,rows:[],readFiles:new Set(),worker:null};modal('PDF・CSV・写真から会計明細を読み込む',`<form onsubmit="readFinanceFile(event)"><label class="field">ファイル<input type="file" name="receipt" multiple accept=".pdf,.csv,.jpg,.jpeg,.png,.webp" required></label><p class="hint">最大30件・1件10MB以下。追加選択できます。PDFは領収書1枚単位（5ページまで）。CSVは「日付・収支・明細区分・金額・摘要・備考」の見出しで100件まで読み込めます。写真は端末内で文字を読み取ります。</p><button class="lime">読み取る</button><div class="error" role="alert"></div><p id="finance-read-status" role="status"></p></form><div id="finance-import-review"></div>`);const state=financeImport;$('#modal').addEventListener('close',()=>{state.active=false;state.worker?.terminate().catch(()=>{});},{once:true});}
function financeGuess(text){const t=String(text).normalize('NFKC'),date=t.match(/(20\d{2})[年/.-]\s*(\d{1,2})[月/.-]\s*(\d{1,2})/),totals=[...t.matchAll(/(?:総合計|お買上合計|合計|領収金額|TOTAL)[^\d\n]{0,12}([\d,]+)(?:円)?/gi)];const rules=[['会場費',/体育館|施設使用|会場|レンタルコート/],['交通費',/駐車|高速|交通|電車|ガソリン/],['大会参加費',/大会|エントリー/],['備品費',/ボール|ビブス|バスケット/],['通信費',/切手|郵便|通信/],['保険料',/保険/],['消耗品費',/テープ|文具|電池|消耗/]];return {date:date?`${date[1]}-${date[2].padStart(2,'0')}-${date[3].padStart(2,'0')}`:'',amount:totals.length?Number(totals[totals.length-1][1].replace(/,/g,'')):null,direction:'支出',category:rules.find(([,r])=>r.test(t))?.[0]||'その他支出',description:t.split('\n').map(x=>x.trim()).find(x=>x.length>1)?.slice(0,300)||'',note:t.slice(0,2500)};}
async function financeOCR(canvas,state){if(!state.worker){const T=await loadScoreOcr();state.worker=await T.createWorker('jpn+eng',1,{workerPath:'/basketball-club/vendor/score-import/worker.min.js',corePath:'/basketball-club/vendor/score-import/core',langPath:'/basketball-club/vendor/score-import/lang',cacheMethod:'none',logger:p=>{const el=$('#finance-read-status');if(el&&state.active)el.textContent='文字を読み取り中… '+Math.round((p.progress||0)*100)+'%';}});}return (await state.worker.recognize(canvas)).data.text;}
async function financeReadOne(file,state){if(file.size>10*1024*1024)throw Error('1件10MB以下にしてください。');let text='',rows=[],ext=file.name.split('.').pop().toLowerCase();const bytes=await file.arrayBuffer();
 if(ext==='csv'){try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{text=new TextDecoder('shift-jis').decode(bytes);}const matrix=parseScoreCsv(text.replace(/^\uFEFF/,'')),heads=matrix.shift()||[],find=(r,...labels)=>r[heads.findIndex(h=>labels.includes(h.trim()))]||'';if(!heads.some(h=>['金額','金額（円）','amount'].includes(h.trim())))throw Error('CSVに「金額」の見出しが必要です。');rows=matrix.map(r=>{const rawDate=find(r,'日付','date').replace(/\//g,'-'),parts=rawDate.split('-');return {account_type:find(r,'会計区分','account_type')||(financeAccountType==='全て'?'一般会計':financeAccountType),date:parts.length===3?parts.map((x,i)=>i?x.padStart(2,'0'):x).join('-'):rawDate,direction:find(r,'収支','direction')||'支出',category:find(r,'明細区分','category')||'その他支出',amount:find(r,'金額','金額（円）','amount')?Number(find(r,'金額','金額（円）','amount').replace(/[¥￥円,\s]/g,'')):null,description:find(r,'摘要','description'),note:find(r,'備考','note')};});if(rows.length>100)throw Error('CSVは100件以内に分けてください。');
 }else if(ext==='pdf'){const lib=await import('/basketball-club/vendor/score-import/pdf.mjs');lib.GlobalWorkerOptions.workerSrc='/basketball-club/vendor/score-import/pdf.worker.mjs';const pdf=await lib.getDocument({data:new Uint8Array(bytes),isEvalSupported:false,cMapUrl:'/basketball-club/vendor/score-import/cmaps/',cMapPacked:true,standardFontDataUrl:'/basketball-club/vendor/score-import/standard_fonts/',wasmUrl:'/basketball-club/vendor/score-import/wasm/'}).promise;try{if(pdf.numPages>5)throw Error('PDFは5ページ以下にしてください。');for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);let part=pdfScoreLines((await page.getTextContent()).items);if(part.replace(/\s/g,'').length<20){const v=page.getViewport({scale:2}),canvas=document.createElement('canvas');canvas.width=Math.min(2400,v.width);canvas.height=v.height*canvas.width/v.width;const viewport=page.getViewport({scale:2*canvas.width/v.width});await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;part=await financeOCR(canvas,state);}text+=part+'\n';}}finally{await pdf.destroy();}rows=[financeGuess(text)];
 }else if(['jpg','jpeg','png','webp'].includes(ext)){const bitmap=await createImageBitmap(file),scale=Math.min(1,2400/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=bitmap.width*scale;canvas.height=bitmap.height*scale;canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();text=await financeOCR(canvas,state);rows=[financeGuess(text)];}else throw Error('PDF・CSV・JPEG・PNG・WebPを選んでください。');
if(!rows.length)throw Error('読み取れる明細がありません。');rows[0].upload={name:file.name,content:await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(file);})};return rows;}
function renderFinanceImportRows(state){$('#finance-import-review').innerHTML=`<p class="hint">読み取り結果を確認・修正してから保存してください。</p>${state.rows.map((r,i)=>`<form class="card finance-import-row"><h3>明細 ${i+1}</h3>${financeFields(r)}</form>`).join('')}<button class="lime" onclick="saveFinanceImport(this)">確認した明細を保存</button><p class="error" role="alert"></p>`;}
async function readFinanceFile(ev){ev.preventDefault();const state=financeImport,files=[...ev.target.elements.receipt.files];ev.submitter.disabled=true;ev.target.querySelector('.error').textContent='';try{if(!files.length||files.length>30)throw Error('ファイルは1〜30件選択してください。');[...document.querySelectorAll('.finance-import-row')].forEach((f,i)=>Object.assign(state.rows[i],financeValues(f)));for(const [i,file] of files.entries()){if(!state.active)return;const key=uploadFileKey(file);if(state.readFiles.has(key))continue;$('#finance-read-status').textContent=`${i+1} / ${files.length}件を読み取り中：${file.name}`;const rows=await financeReadOne(file,state);if(!state.active)return;state.rows.push(...rows);state.readFiles.add(key);renderFinanceImportRows(state);}$('#finance-read-status').textContent='読み取り完了。内容を確認して保存してください。';}catch(e){if(state.active)ev.target.querySelector('.error').textContent=e.message;}finally{ev.submitter.disabled=false;await state.worker?.terminate().catch(()=>{});state.worker=null;}}
async function saveFinanceImport(button){button.disabled=true;try{const entries=[...document.querySelectorAll('.finance-import-row')].map((form,i)=>({...financeValues(form),...(financeImport.rows[i].upload?{upload:financeImport.rows[i].upload}:{})}));for(const r of entries)if(!r.date||!r.description||!Number.isInteger(r.amount)||r.amount<0)throw Error('日付・摘要・金額を確認してください。');const result=await api('finance_batch',{year:data.finance.year,entries});$('#modal').close();await changeFinanceYear(data.finance.year);toast(result.archive_error||'読み込んだ明細・領収書・帳票を保存しました。');}catch(e){button.nextElementSibling.textContent=e.message;}finally{button.disabled=false;}}

function financeTransportReports(f){return `<details class="card"><summary>配車担当からの交通費報告（${(f.transport_reports||[]).length}件）</summary><p class="hint">会計明細には自動計上されません。内容を確認して明細へ登録してください。</p>${(f.transport_reports||[]).map(r=>`<article class="logistics-card"><h3>${esc(r.date)} ${esc(r.title)}</h3><p>${esc(r.family_id)} ／ ${r.reviewed?'精算確認済み':'精算未確認'}</p><p>駐車場代：${financeMoney(r.body.parking)} ／ 追加費用：${financeMoney(r.body.additional)}</p><p>${esc(r.body.note)}</p></article>`).join('')||'<p>報告はありません。</p>'}</details>`;}

function financeSection(source){if(!source)return source;const entries=source.entries.filter(r=>financeAccountType==='全て'||r.account_type===financeAccountType),income=entries.filter(r=>r.direction==='収入').reduce((n,r)=>n+r.amount,0),expense=entries.filter(r=>r.direction==='支出').reduce((n,r)=>n+r.amount,0);return {...source,account_type:financeAccountType,entries,income,expense,balance:income-expense,member_reports:source.member_reports.filter(r=>financeAccountType==='全て'||r.account_type===financeAccountType),transport_reports:(source.transport_reports||[]).filter(r=>financeAccountType==='全て'||(r.body.account_type||'一般会計')===financeAccountType)};}
function financeTypeQuery(){return financeAccountType==='全て'?'':'&account_type='+encodeURIComponent(financeAccountType);}
