let pub={}, user=null, data={}, page='home', month=new Date(2026,9,1), selectedDate='', activeEvent='';
let selectedMember=sessionStorage.getItem('club_member')||'',switchingMember=false,reportDirty=false;
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function teamWordmark(name){if(/^(?:(?:MIKI|三木)\s*)?SHINING\s*CHEETAHS$/i.test(name.trim()))return '<strong class="team-wordmark miki-wordmark"><span class="team-name-white">MIKI </span><span class="team-name-yellow">S</span><span class="team-name-white">HINING C</span><span class="team-name-yellow">HEETAHS</span></strong>';return `<strong class="team-wordmark"><span class="team-name-white">${esc(name)}</span></strong>`;}
const brand=()=>{const name=pub.content?.name||'三木　SHINING CHEETAHS';return `<a class="brand" href="#home" aria-label="${esc(name)} トップページ"><img class="club-logo" src="/basketball-club/uploads/00000000000000000000000000000001.jpg" alt="三木 SHINING CHEETAHS ロゴ"><span>${teamWordmark(name)}<small>YOUTH BASKETBALL CLUB</small></span></a>`};
let renderEditToken='';
async function api(path,body){
 let payload=body?{...body}:null;
 if(payload&&user&&path!=='upload_stage'&&typeof stageUploadPayload==='function')payload=await stageUploadPayload(payload);
 if(payload&&user?.role!=='member'&&!['login','logout'].includes(path)&&!payload._edit_token)payload._edit_token=($('#modal')?.open?$('#modal').dataset.editToken:renderEditToken)||data.edit_token;
 const headers=selectedMember?{'X-Club-Member':selectedMember}:{};if(payload)headers['Content-Type']='application/json';
 const r=await fetch('/basketball-club/api/'+path,{method:payload?'POST':'GET',headers,...(payload?{body:JSON.stringify(payload)}:{})});const raw=await r.text();let v;try{v=JSON.parse(raw)}catch(e){throw Error('サーバーに接続できませんでした。少し待ってから、もう一度お試しください。')}
 if(r.status===409&&v.code==='edit_conflict'){
  const choice=await resolveEditConflict(v);
  if(choice==='mine'){
   const retry={...payload,_edit_token:v.token};
   if(path==='billing_plan') {const latest=await api('data');retry.revision=latest.billing_plan.revision;}
   return api(path,retry);
  }
  if(choice==='latest'){$('#modal').close();await refresh();throw Error('最新の保存内容を読み込みました。自分の変更は保存していません。');}
  throw Error('保存を中止しました。入力内容は残っています。');
 }
 if(r.status===401&&path!=='login'){user=null;data={};selectedMember='';sessionStorage.removeItem('club_member');document.querySelectorAll('dialog[open]').forEach(d=>d.close());page='login';location.hash='login';render();throw Error('ログインの有効期限が切れました。再ログインしてください。操作内容は保存されていません。');}
 if(!r.ok)throw Error(v.error||'読み込みに失敗しました。');return v;
}
function resolveEditConflict(info){return new Promise(resolve=>{
 const dialog=document.createElement('dialog');dialog.className='edit-conflict-dialog';
 const names={staff_activity:'スタッフ活動実績',staff_week_approval:'週ごとの承認',attendance_meta:'出欠予定の確認',event_details:'会場の地図',match_rosters:'参加メンバー',member_categories:'活動区分',member_families:'家族設定',survey_forms:'アンケート',survey_deadlines:'回答期限',shop_products:'商品',schedule_documents:'日程PDF',fee_adjustments:'会費の調整',trial_reviews:'体験申込の確認',events:'活動日程',reports:'実際の出欠',users:'会員・スタッフ',portal_items:'掲載内容',portal_entries:'報告の確認',results:'試合結果',game_stats:'スコア',event_briefings:'参加メンバー・詳細',meta:'会費設定'};
 dialog.innerHTML=`<h2>同じ項目が更新されています</h2><p>他のコーチ・管理者の操作などで、編集開始後に保存内容が変わりました。内容を比較して、どちらを優先するか選んでください。</p>${info.changes.map(c=>`<h3>${esc(names[c.item]||c.item)}</h3><details><summary>編集を始めた時の内容</summary><pre>${esc(conflictText(c.before))}</pre></details><h4>最新の保存内容</h4><pre>${esc(conflictText(c.latest))}</pre>`).join('')}<h3>自分が保存しようとしている内容</h3><pre>${esc(conflictText(info.proposed))}</pre><p>「自分の変更を優先して保存」は、この項目を自分の入力内容で上書きします。</p><div class="dialog-actions"><button class="outline" data-choice="cancel">編集に戻る</button><button class="outline" data-choice="latest">最新の内容を使う</button><button class="lime" data-choice="mine">自分の変更を優先して保存</button></div>`;
 const finish=choice=>{dialog.close();dialog.remove();resolve(choice)};dialog.addEventListener('cancel',e=>{e.preventDefault();finish('cancel')});dialog.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>finish(b.dataset.choice));document.body.append(dialog);dialog.showModal();
});}

function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>$('#toast').classList.remove('show'),4500)}
const dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('ja-JP',{month:'long',day:'numeric',weekday:'short'});
function headerSocialIcon(kind,url){const instagram=kind==='Instagram',facebook=kind==='Facebook',icon=facebook?'<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M14 22v-9h3l.5-4H14V7c0-1.2.3-2 2-2h2V1.4A24 24 0 0 0 15 1c-3 0-5 1.8-5 5v3H7v4h3v9z"/></svg>':instagram?'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="17.5" cy="6.5" r="1.2" fill="currentColor"/></svg>':'<svg viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M27 14c0-6-5-10-12-10S3 8 3 14c0 5 4 9 10 10l-1 5 7-5c5-2 8-5 8-10Z"/><text x="15" y="17" text-anchor="middle" font-family="Arial,sans-serif" font-size="8" font-weight="bold" fill="#06c755">LINE</text></svg>';const cls='header-social-icon '+(facebook?'facebook-icon':instagram?'instagram-icon':'line-icon');return url?`<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer" aria-label="${kind}（別タブで開く）">${icon}</a>`:`<button type="button" class="${cls}" aria-label="${kind}（URL準備中）" title="${kind}（URL準備中）" disabled>${icon}</button>`;}
function header(){const links='<a href="#philosophy">チームについて</a><a href="#trial">体験会・入会案内</a><a href="#location">活動場所</a><a href="#staff-introduction">スタッフ紹介</a><a href="#other-activities">その他の活動</a><a href="#faq">FAQ</a>',socials=`<span class="header-social">${headerSocialIcon('Instagram',pub.content.instagram)}${headerSocialIcon('Facebook',pub.content.facebook)}${headerSocialIcon('公式LINE',pub.content.line)}</span>`;return `<header class="header"><div class="wrap nav">${brand()}<nav class="navlinks" aria-label="メインメニュー">${links}${socials}<a class="btn lime small" href="#login">ログイン</a></nav><div class="public-mobile-actions"><button type="button" class="public-menu-trigger" aria-haspopup="dialog" onclick="openPublicMenu()"><span aria-hidden="true">☰</span> メニュー</button><a class="btn lime small" href="#login">ログイン</a></div></div></header>`}
function trialGroups(e){const g=e.group_name||'';return {elementary:/小学生|小中学生|U9|U12/i.test(g),junior:/中学生|U15/i.test(g)}}
function calendar(events){let y=month.getFullYear(),m=month.getMonth(),start=new Date(y,m,1).getDay(),n=new Date(y,m+1,0).getDate();return `<div class="card calendar-card"><div class="calendar-head"><strong>${y}. ${String(m+1).padStart(2,'0')}</strong><div><button onclick="changeMonth(-1)" aria-label="前の月">‹</button><button onclick="changeMonth(1)" aria-label="次の月">›</button></div></div><div class="calendar">${['日','月','火','水','木','金','土'].map(d=>`<div class="dow">${d}</div>`).join('')}${'<span></span>'.repeat(start)}${Array.from({length:n},(_,i)=>{const d=`${y}-${String(m+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`,es=events.filter(e=>e.date===d),elementary=es.some(e=>trialGroups(e).elementary),junior=es.some(e=>trialGroups(e).junior);return `<button class="day ${es.length?'event':''} ${selectedDate===d?'selected':''}" onclick="selectDay('${d}')" aria-label="${d}${elementary?' 小学生体験会':''}${junior?' 中学生体験会':''}" aria-pressed="${selectedDate===d}"><span>${i+1}</span><span class="day-dots" aria-hidden="true">${elementary?'<i class="trial-dot elementary"></i>':''}${junior?'<i class="trial-dot junior"></i>':''}</span></button>`}).join('')}</div><div class="calendar-legend"><span><i class="trial-dot elementary" aria-hidden="true"></i>小学生</span><span><i class="trial-dot junior" aria-hidden="true"></i>中学生</span></div><p class="hint calendar-help">日付を選ぶと、その日の体験会を表示します。</p></div>`}
function trialListings(events){return ['elementary','junior'].map(group=>{const es=events.filter(e=>trialGroups(e)[group]);return `<section class="trial-age-group" aria-label="${group==='elementary'?'小学生':'中学生'}の体験会"><div class="trial-age-heading"><h3><i class="trial-dot ${group}" aria-hidden="true"></i>${group==='elementary'?'小学生':'中学生'}の体験会</h3><span>${group==='elementary'?'U9・U12':'U15'}</span></div>${es.map(e=>eventCard(e,true)).join('')||'<p class="empty">選択した期間の体験会はありません。</p>'}</section>`}).join('')}
function faqSection(){return `<section class="section wrap faq-section" id="faq"><div class="section-title"><div><div class="eng">FAQ</div><h2>体験・入会についてのよくある質問</h2></div></div>${(pub.faq||[]).map(q=>`<details><summary>${esc(q.q)}</summary><p>${esc(q.a)}</p></details>`).join('')}</section>`}
function eventCard(e,trial=false,wholeCard=false){if(trial)return trialDetailCard(e);const d=new Date(e.date+'T12:00:00');return `${wholeCard?`<a class="event-card upcoming-event-link" href="#schedule?event=${encodeURIComponent(e.id)}">`:'<article class="event-card">'}<${wholeCard?'div':'a'} class="date-block" ${wholeCard?'':`href="${trial?'#trial-list':'#schedule?event='+encodeURIComponent(e.id)}"`} aria-label="${esc(e.date+' '+e.title+'の詳細を見る')}"><small>${d.getMonth()+1}月</small><strong>${d.getDate()}</strong><small>${['SUN','MON','TUE','WED','THU','FRI','SAT'][d.getDay()]}</small></${wholeCard?'div':'a'}><div><span class="tag">${esc(e.group_name)}</span><h3>${esc(e.title)}</h3><p>${esc(e.time)}<br>${esc(e.place)}</p></div>${trial?`<button class="outline small" onclick="trialForm('${e.id}')">参加する</button>`:''}</${wholeCard?'a':'article'}>`}
function publicPage(){let c=Object.fromEntries(Object.entries(pub.content).map(([k,v])=>[k,typeof v==='string'?v.replace(/年長[〜～]/g,'小学1年生〜').replace(/年長[・、]?/g,''):v]));const events=pub.events.filter(e=>e.date.startsWith(`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}`)&&(!selectedDate||e.date===selectedDate));$('#app').innerHTML=`${header()}<main><section class="hero"><div class="hero-media">${c.hero?`<img class="hero-photo" src="${esc(c.hero)}" alt="${esc(c.name)}のバスケットボール活動風景" width="640" height="640" fetchpriority="high" decoding="async">`:''}</div><div class="wrap"><div class="eyebrow">PLAY TOGETHER. GROW TOGETHER.</div><h1>${esc(c.headline)}</h1><p class="club-area">${esc(c.region||'兵庫県三木市')}の小学生・中学生バスケットボールクラブ</p><p>${esc(c.intro)}</p><div class="hero-bottom"><div class="hero-contact-actions"><div class="hero-trial-row"><a class="btn lime" href="#trial-list">体験会に参加する</a><div class="hero-small">小学生・中学生 ／ 初心者も大歓迎</div></div></div></div></div><div class="hero-num">CHEETAHS</div></section><div class="wrap"><div class="notice"><b>NEWS</b><time>2026.09</time><span>${esc(c.notice)}</span></div></div><section class="section wrap" id="philosophy"><div class="about-grid"><div><div class="eyebrow">OUR PHILOSOPHY</div><h2>バスケを通して、<br>「生きる力」を育てる。</h2></div><div><p>${esc(c.philosophy)}</p><div class="values"><div><span>01</span>挑戦する心</div><div><span>02</span>仲間への敬意</div><div><span>03</span>考える力</div></div></div></div></section><section class="section schedule-section" id="trial"><div class="wrap"><div class="section-title"><div><div class="eng">TRYOUT SCHEDULE</div><h2>その一歩が、夢中のはじまり。</h2></div><p class="tryout-intro">${esc(c.recruit)}</p></div><div class="schedule-grid"><div>${calendar(pub.events)}</div><div id="trial-list">${trialListings(events)}${selectedDate?'<button class="text-link" onclick="selectDay(\'\')">今月のすべての体験会を見る</button>':''}<p class="hint">持ち物：${esc(c.equipment)}</p></div></div></div></section>${trialReviewsSection()}<section class="section wrap" id="location"><div class="section-title"><div><div class="eng">OUR HOME COURT</div><h2>練習場所・練習風景</h2></div></div><div class="location-grid"><div>${c.gallery||c.hero?`<img src="${esc(c.gallery||c.hero)}" alt="SHINING CHEETAHSの活動風景" width="640" height="640" loading="lazy" decoding="async">`:'<div class="card empty">練習写真は管理画面から設定できます。</div>'}</div><div><h3>${esc(c.place)}</h3><p class="muted">${esc(c.address)}</p><div class="info-row"><b>練習日</b><span>${esc(c.practice)}</span></div><div class="info-row"><b>持ち物</b><span>${esc(c.equipment)}</span></div><div class="social">${social(c.instagram,'Instagram')}${social(c.facebook,'Facebook')}${social(c.line,'公式 LINE')}</div></div></div></section>${publicStaffSection()}${mikitivSection()}${faqSection()}</main><footer class="footer"><div class="wrap">${brand()}<p>${esc(c.subname)}<br>© 2026 ${esc(c.name)} BASKETBALL CLUB</p></div></footer><div class="demo-strip">操作体験用デモ ｜ 日程・人物・活動場所はサンプルです</div>`}
function social(url,label){const theme=label==='Instagram'?'social-instagram':label==='Facebook'?'social-facebook':'social-line';return url?`<a class="btn small ${theme}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${label}</a>`:`<button class="small ${theme}" onclick="toast('公式URLは管理画面から設定できます。')">${label}（準備中）</button>`}
function changeMonth(n){month=new Date(month.getFullYear(),month.getMonth()+n,1);selectedDate='';publicPage()}
function selectDay(d){selectedDate=d;publicPage()}
async function refresh(){pub=await api('public');user=(await api('me')).user;if(!user&&selectedMember){selectedMember='';sessionStorage.removeItem('club_member');user=(await api('me')).user;}if(user)data=await api('data');document.documentElement.style.setProperty('--lime',pub.content.accent);document.title=pub.content.seo_title||pub.content.name+' | バスケットボールクラブ';render()}
function render(){page=(location.hash.slice(1)||'home').split('?')[0];if(page==='schedule'){const eid=new URLSearchParams(location.hash.split('?')[1]||'').get('event'),e=data.events?.find(e=>e.id===eid);if(e){attendanceMonth=new Date(e.date+'T12:00:00');coachScheduleDay=e.date;categoryFilter='';setTimeout(()=>document.getElementById('plan-'+e.id)?.scrollIntoView({block:'start'}),0);}}if(page==='trial-review'){trialReviewPage();return}if(page==='finance-register'){financeRegistrationPage();return}if(page==='register'){registrationPage();return}if(page==='coach-register'){coachRegistrationPage();return}if(page==='forgot-password'){forgotPasswordPage();return}if(page==='password-reset'){passwordResetPage();return}if(page==='account-setup'){accountSetupPage();return}if(['philosophy','trial','trial-list','location','faq','staff-introduction','other-activities'].includes(page)){publicPage();setTimeout(()=>document.getElementById(page)?.scrollIntoView(),0);return}if(page==='all-staff'){staffIntroductionPage();return;}if(page==='home')publicPage();else if(page==='login'||!user)loginPage();else dashboard()}
function loginPage(){$('#app').innerHTML=`${header()}<div class="login-layout"><div class="login-brand"><div class="eyebrow">CHEETAHS CLUB PORTAL</div><div class="eng">ONE TEAM.<br>ONE DREAM.</div><h1>コートの外でも、<br>チームはひとつ。</h1><p>練習の予定、今日のコンディション。<br>次の一歩を、ここから。</p></div><div class="login-main"><span class="eyebrow">MEMBER & STAFF</span><h2>ログイン</h2><p class="hint">登録済みのID・パスワードを入力してください。</p><form onsubmit="login(event)"><label class="field">ログインID<input id="login-id" name="id" autocomplete="username" required placeholder="例：member01"></label><label class="field">パスワード<input id="login-pw" type="password" name="password" autocomplete="current-password" required></label><label class="check-row hint"><input type="checkbox" onchange="$('#login-pw').type=this.checked?'text':'password'">パスワードを表示</label><p id="login-error" class="error" role="alert"></p><button class="lime" style="width:100%" type="submit">ログイン</button></form><div class="account-login-links"><div class="registration-button-row"><a class="btn outline" href="#register">会員新規登録</a><a class="btn outline" href="#finance-register">役員新規登録</a><a class="btn outline" href="#coach-register">コーチ新規登録</a></div><a class="text-link" href="#forgot-password">パスワードをお忘れの方</a></div><div class="demo-accounts"><b>デモを試す</b><p>下のボタンで体験用のID・パスワードを入力できます。</p><button onclick="fillLogin('member01','Cheetahs123!')">会員</button><button onclick="fillLogin('coach01','Coach123!')">コーチ</button><button onclick="fillLogin('admin01','Admin123!')">管理者</button><button onclick="fillLogin('officer01','Officer123!')">役員</button><div class="hint">デモには実在するお子さまの情報を入力しないでください。</div></div></div></div>`}
function fillLogin(id,pw){$('#login-id').value=id;$('#login-pw').value=pw}
async function login(ev){ev.preventDefault();const b=ev.submitter;b.disabled=true;try{selectedMember='';sessionStorage.removeItem('club_member');const loginResult=await api('login',Object.fromEntries(new FormData(ev.target)));location.hash=['condition','schedule','attendance-list','admin-guide'].includes(page)?page:'dashboard';await refresh();window.scrollTo({top:0,behavior:'instant'})}catch(e){if($('#login-error'))$('#login-error').textContent=e.message;else toast(e.message)}finally{b.disabled=false}}
async function logout(){selectedMember='';sessionStorage.removeItem('club_member');await api('logout',{});user=null;data={};location.hash='login'}
const unreadTrials=()=> (data.trials||[]).filter(t=>!t.reviewed_at);
function trialNotice(){const n=unreadTrials().length;return n?`<aside class="trial-notice" role="status"><div><b>未確認の体験申込が ${n} 件あります</b><p>お名前・希望日程・連絡先をご確認ください。</p></div><a class="btn small" href="#trials">申込を確認</a></aside>`:''}
const adminManagementLinks=[['member-roster','▤','メンバー表'],['school-reports','▤','成績報告'],['settings','⚙','サイト編集'],['members','♧','会員一覧'],['staff-members','♧','コーチ・スタッフ一覧'],['schedule','▦','練習・試合日程'],['attendance-list','✓','出欠・体調報告'],['attendance-rates','▥','出席率'],['conditioning','♡','コンディショニングシート'],['basket-notes','▤','バスケノート'],['basket-note-settings','▤','バスケノート設定'],['worksheets','▤','ワークシート'],['billing-settings','¥','会費設定'],['staff-approvals','✓','コーチ・スタッフ活動の承認'],['results','◷','試合結果・動画'],['announcement-admin','✉','クラブからのお知らせ'],['survey-admin','✓','保護者アンケート'],['shop-admin','◇','スクール内物販'],['board-admin','☷','掲示板'],['payment-method-admin','¥','支払い方法変更者一覧'],['finance-admin','¥','会計・担当者管理'],['admin-guide','⚙','管理設定ガイド']];
const adminSettingsLinks=[['school-reports','▤','成績報告項目の編集'],['members','♧','会員一覧'],['staff-members','♧','スタッフ一覧'],['settings','⚙','サイト編集'],['schedule','▦','練習・試合日程編集'],['condition-settings','♡','体調報告編集'],['basket-note-settings','▤','バスケノート編集'],['worksheets','▤','ワークシート編集'],['announcement-admin','✉','クラブからのお知らせ設定'],['board-admin','☷','掲示板設定'],['injury-settings','♡','怪我報告設定'],['shop-admin','◇','スクール内物販設定'],['billing-settings','¥','会費設定'],['survey-admin','✓','保護者アンケート設定'],['finance-admin','¥','役員設定']];
const adminReviewLinks=[['member-roster','▤','メンバー表'],['school-reports','▤','成績報告'],['attendance-list','✓','出欠・体調報告'],['attendance-rates','▥','出席率'],['messages','✉','諸連絡'],['basket-notes','▤','バスケノート'],['worksheets','▤','ワークシート'],['billing-settings','¥','会費設定'],['staff-approvals','✓','スタッフ活動'],['survey-admin','✓','保護者アンケート'],['shop-admin','◇','スクール内物販'],['finance-admin','¥','役員設定']];
function adminNavigationLinks(){if(user.delegated_coach||user.delegated_officer)return delegatedNavigationLinks();return adminFull()&&!user.delegated_coach?[['schedule','▦','練習・試合日程'],['attendance-list','✓','出欠・体調報告'],['results','◷','試合結果・動画'],['skill-videos','▷','スキルアップ動画'],['staff-approvals','✓','スタッフ活動'],['survey-admin','✓','保護者アンケート'],['shop-admin','◇','スクール内物販'],['admin-settings','⚙','各種設定'],['admin-reviews','✓','各種確認'],['admin-guide','⚙','管理設定ガイド']]:adminManagementLinks.filter(l=>adminCan(adminSection(l[0]),!user?.delegated_coach));}
function adminMenuGroup(title,items){return heading(title,'項目を選択してください。')+`<div class="admin-home-links admin-settings-links">${items.map(([id,icon,label])=>`<a class="card" href="#${id}"><h2><span class="admin-shortcut-icon" aria-hidden="true">${icon}</span><span>${label}</span></h2><span class="text-link">開く →</span></a>`).join('')}</div>`;}
function adminHome(){return heading(user.delegated_officer?'役員ホーム':user.delegated_coach?'コーチホーム':'管理者ホーム','管理する項目を選んでください。',staffHomeContacts())+`<div class="admin-home-links dashboard-shortcuts">${adminNavigationLinks().map(([id,icon,label])=>`<a class="card" href="#${id}"><h2><span class="admin-shortcut-icon" aria-hidden="true">${icon}</span><span>${label}</span></h2></a>`).join('')}</div>`;}
function dashboard(){if(user?.role==='accountant'){accountingDashboard();return;}
 const staff=user.role!=='member',admin=user.role==='admin';
 const links=[['dashboard','⌂','ホーム'],['schedule','▦','練習・試合日程'],...(!staff?[['condition','♡','体調報告']]:[]),['results','◷','試合結果・動画'],['skill-videos','▷','スキルアップ動画'],...(staff?[['member-roster','▤','メンバー表'],['attendance-list','✓','出欠・体調報告'],['attendance-rates','▥','出席率'],['messages','✉','諸連絡'],['basket-notes','▤','バスケノート'],['worksheets','▤','ワークシート'],['trials','✉','体験会の申込'],['members','♧','会員一覧'],['staff-members','♧','コーチ・スタッフ一覧'],['excel','⇩','コーチ・スタッフ勤怠管理']]:[]),...(admin?[['admin-guide','⚙','管理・設定ガイド'],['billing-settings','¥','会費設定'],['settings','⚙','サイト編集']]:[])];
 if(admin){links.splice(0,links.length,['dashboard','⌂','ホーム'],...adminNavigationLinks());}else if(!staff){links.splice(0,links.length,...visibleMemberLinks());}else links.push(['portal-admin','✉','会員向けサービス管理']);
 if(data.staff_attendance?.available&&!links.some(l=>l[0]==='staff-attendance'))links.push(['staff-attendance','✓','スタッフ出欠']);
 if(user.delegated_coach&&!links.some(l=>l[0]==='excel'))links.push(['excel','⇩','コーチ・スタッフ勤怠管理']);
 if(user.role==='coach'||user.delegated_coach)coachHomeNavigation=links.filter(l=>l[0]!=='dashboard');
 if(staff&&page==='condition')page='attendance-list';
 if(staff&&page==='board')page='portal-admin';
 if(admin&&page!=='dashboard'&&!(page==='staff-attendance'&&data.staff_attendance?.available)&&!(user.delegated_coach&&page==='excel')&&!adminCan(adminSection(page)))page='dashboard';
 const groupedAdmin=adminFull()&&!user.delegated_coach;
 const navigationRoutes=groupedAdmin?[...links,...adminManagementLinks,...adminSettingsLinks,...adminReviewLinks,['admin-settings','⚙','各種設定'],['admin-reviews','✓','各種確認'],['staff-approval-settings','✓','スタッフ活動承認']]:links;
 if(admin&&!['billing-individual','scorecard','score-records','personal-history','team-history','excel'].includes(page)&&!navigationRoutes.some(l=>l[0]===page))page='dashboard';
 if(!navigationRoutes.some(l=>l[0]===page)&&!(page==='checkout'&&!staff)&&!['scorecard','score-records','personal-history','team-history',...(admin?['billing-individual','excel']:[])].includes(page))page='dashboard';
 renderEditToken=data.edit_token||'';
 $('#app').innerHTML=`<div class="app-shell ${page==='schedule'?'schedule-screen':''}"><aside class="sidebar">${brand()}<div class="side-label">${staff?'TEAM MANAGEMENT':'MEMBER PORTAL'}</div><nav>${links.map(([id,icon,label])=>`<a class="side-link ${page===id?'active':''}" href="#${id}">${icon}　${label}<span data-new-nav="${id}">${navNew(id)}</span>${id==='trials'&&unreadTrials().length?`<span class="notification-badge" aria-label="未確認${unreadTrials().length}件">${unreadTrials().length}</span>`:''}</a>`).join('')}</nav><details class="mobile-route"><summary><span>メニュー：${esc(['scorecard','score-records','personal-history','team-history'].includes(page)?'試合結果・動画':page==='billing-individual'?'会費の個別設定':page==='checkout'?'月謝支払い':navigationRoutes.find(l=>l[0]===page)?.[2]||'ホーム')}</span><span data-new-nav="${['scorecard','score-records','personal-history','team-history'].includes(page)?'results':page}">${navNew(['scorecard','score-records','personal-history','team-history'].includes(page)?'results':page)}</span></summary><div class="mobile-nav-options">${links.map(([id,icon,label])=>`<a class="mobile-nav-link ${page===id?'active':''}" href="#${id}"><span>${label}</span><span data-new-nav="${id}">${navNew(id)}</span></a>`).join('')}</div></details><div class="side-bottom"><a class="side-link" href="#account-setup">登録情報</a><p><span class="avatar">${esc(user.name[0])}</span>${esc(user.name)}</p><a class="side-link" href="#home">公開サイトを見る</a><button class="side-link" onclick="logout()">ログアウト</button></div></aside><main class="workspace"><div class="workspace-top"><span>${admin&&!user.delegated_coach&&!user.delegated_officer?'<a class="member-home-link" href="#dashboard">管理者</a>':staff?'<a class="member-home-link" href="#dashboard">スタッフページ</a>':'<a class="member-home-link" href="#dashboard">会員ページ</a>'}　/　${esc(page==='billing-individual'?'会費の個別設定':page==='checkout'?'お支払い手続き':page==='score-records'?'個人記録':page==='scorecard'?'スコアシート':page==='personal-history'?'個人のこれまでの記録':page==='team-history'?'チーム全体の過去の履歴':navigationRoutes.find(l=>l[0]===page)?.[2])}</span><span class="account-summary"><span class="account-family-names">${(user.role==='member'?(user.family_members||[user]):[user]).map(c=>`<span>${esc(c.name)}</span>`).join('')}</span><button class="text-link" onclick="logout()">ログアウト</button></span></div>${!staff&&page!=='member-guide'?familySwitcher():''}${staff&&!admin?trialNotice():''}${!staff&&page==='dashboard'?memberHomeLinks()+clubPhoneButton('コーチへ電話','mobile-phone-banner member-coach-phone'):''}${['schedule','results','surveys','messages','board'].includes(page)?'<p class="hint">NEWは未確認の新着・更新です。日程は「詳細を確認」を開くと既読になります。</p>':''}${portalContent(staff,admin)}</main></div>`;
 observeNewArticles();
}
const heading=(title,sub,action='')=>`<div class="page-heading"><div><h1>${title}</h1><p>${sub}</p></div>${action}</div>`;
const stats=items=>`<div class="stats">${items.map(([label,n,unit])=>`<div class="stat"><div class="label">${label}</div><div class="stat-value"><strong>${n}</strong><small>${unit}</small></div></div>`).join('')}</div>`;
function portalContent(staff,admin){
 const members=(data.users||[]).filter(u=>u.role==='member'&&u.active),events=data.events||[],reports=data.reports||[];
 const next=events.find(e=>e.date>=new Date().toLocaleDateString('sv-SE')&&e.kind!=='体験会')||events[0];
 if(!activeEvent||!events.some(e=>e.id===activeEvent))activeEvent=next?.id||'';
 if(page==='injury-settings'&&adminFull())return reportTemplatePage('injuries');
 if(page==='condition-settings'&&adminFull())return reportTemplatePage('condition');
 if(page==='admin-settings'&&adminFull())return adminMenuGroup('各種設定',adminSettingsLinks);
 if(page==='admin-reviews'&&adminFull())return adminMenuGroup('各種確認',adminReviewLinks);
 if(page==='staff-approval-settings'&&adminFull())return staffApprovalPage('スタッフ活動承認');
 if(page==='basket-note-settings'&&adminFull())return noteTemplateSettingsPage();
 if(page==='staff-attendance'&&data.staff_attendance?.available)return staffAttendancePage();
 if(page==='school-reports'&&data.school_reports?.available)return schoolReportsPage();
 if(page==='basket-notes')return basketNotesPage();
 if(page==='attendance-rates'&&staff)return attendanceRatesPage();
 if(page==='finance-report'&&!staff)return memberFinancePage();
 if(page==='worksheets'&&data.worksheets?.available)return worksheetPage();
 if(page==='conditioning'&&staff)return combinedReportsPage();
 if(page==='finance-admin'&&admin)return financePage();
 if(page==='dashboard'&&(user.role==='coach'||user.delegated_coach))return coachCardHome();
 if(page==='dashboard'&&admin)return adminHome();
 if(page==='staff-approvals'&&admin)return staffApprovalPage();
 if(page==='billing-individual'&&admin)return billingIndividualPage();
 if(page==='billing-settings'&&admin)return heading('会費設定','会費・支払い方法・返金と退会手続きを設定します。')+sheetSyncPanel()+collectionPanel()+billingAdminSettings()+feeAdjustmentsPanel()+(adminCan('payment-method-admin')?'<section class="card"><h2>支払い方法変更者一覧</h2>'+paymentMethodChangesPanel()+'</section>':'');
 if(page==='admin-guide'&&admin)return adminGuide();
 if(page==='attendance-list'&&staff)return combinedReportsPage();
 if(page==='member-roster'&&staff)return rosterPage();
 if(page==='schedule')return attendancePage(staff);
 if(page==='skill-videos')return skillVideosPage();
 if(page==='scorecard')return scorecardPage(staff);
 if(page==='score-records')return scoreRecordsPage(admin);
 if(page==='personal-history')return personalHistoryPage();
 if(page==='team-history')return teamHistoryPage();
 if(page==='condition'&&!staff)return conditionOnly();
 if(page==='checkout'&&!staff)return familyCheckout();
 if(page==='member-guide'&&!staff)return memberGuide();
 if(page==='board')return memberService('board');
 if(page==='announcement-admin'&&admin)return heading('クラブからのお知らせ','お知らせの掲載管理と既読・未読の確認ができます。')+publicationManager('announcements');
 if(page==='payment-method-admin'&&admin)return heading('支払い方法変更者一覧','支払い方法の変更状況と過去の履歴を確認できます。')+paymentMethodChangesPanel();
 if(page==='board-admin'&&admin)return heading('掲示板','投稿の掲載管理と既読・未読の確認ができます。')+(adminCan('board-admin',true)?'<p><button class="lime" onclick="boardEditForm()">＋ 掲示板の投稿を新規作成</button></p>':'')+boardList();
 if(page==='shop-admin'&&admin)return heading('スクール内物販','商品の掲載管理と注文・支払い・受け渡し状況を確認できます。')+publicationManager('shop')+shopAdmin();
 if(page==='survey-admin'&&admin)return heading('保護者アンケート','アンケートの掲載管理と回答結果の確認ができます。')+publicationManager('surveys');
 if(page==='messages'&&staff)return heading('諸連絡','会員への個別連絡・会員からの連絡を確認できます。')+staffMessagesPanel();
 if(page==='portal-admin')return portalAdmin();
 if(!staff&&memberLinks.some(l=>l[0]===page)&&!['dashboard','schedule','results'].includes(page))return memberService(page);
 const conditionEvent=events.find(e=>e.id===activeEvent),conditionMembers=members.filter(m=>conditionEvent&&(m.categories||'男子A').split(/[、,]/).some(c=>categoryNames(conditionEvent).includes(c.trim())));
 const selectedReports=reports.filter(r=>r.event_id===activeEvent&&conditionMembers.some(m=>m.id===r.user_id)),reported=selectedReports.filter(hasCondition),low=reported.filter(r=>['良くない','ダメ','悪い'].includes(r.body_condition)||['良くない','ダメ','悪い'].includes(r.mind_condition)||(!r.body_condition&&r.condition<=2));
 if(page==='dashboard')return (staff?heading('チームの今日を、ひと目で。','報告を確認して、一人ひとりに合った練習を。','<div class="toolbar home-contact-actions"><a class="btn outline" href="#members">会員一覧へ</a><a class="btn lime" href="#attendance-list">出欠を確認・入力</a><a class="btn outline" href="#condition">体調を確認</a></div>'):'')+

 (staff?homeAnnouncements()+coachHomeSummary():stats([['登録済みの活動',events.length,'件'],['体調報告済み',reports.filter(hasCondition).length,'回'],['出席予定（遅刻・早退を含む）',reports.filter(r=>['出席','遅刻・早退','遅刻','早退'].includes(r.attendance)).length,'回'],['掲載中の試合結果',data.results.length,'試合']]))+
 `<div class="two-col"><div class="stack">${next?`<div class="card next-event"><span class="tag">NEXT ${next.kind==='試合'?'GAME':'PRACTICE'}</span><h2>${esc(next.title)}</h2><p>${dateLabel(next.date)}　${esc(next.time)}<br>${esc(next.place)}</p><a class="btn lime small" href="#schedule">日程の詳細 →</a></div>`:''}${!staff?`<div class="card"><h2>体調報告の履歴</h2><details class="injury-report-history condition-report-history"><summary><span class="history-show">報告履歴を見る</span><span class="history-hide">報告履歴を閉じる</span></summary><div class="injury-history-content">${reportHistory(reports)}</div></details></div>`:''}</div><div class="card upcoming-activities"><h2>これからの活動</h2>${events.filter(e=>e.date>=new Date().toLocaleDateString('sv-SE')).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,5).map(e=>eventCard(e,false,true)).join('')||'<div class="empty">予定はありません。</div>'}<a class="text-link" href="#schedule">すべての日程を見る →</a></div></div>`;
 if(page==='schedule'&&!staff)return heading('練習・試合日程・体調・欠席報告','日程を選んで、体調と出欠予定を送信できます。')+eventList(events,false)+memberReport();
 if(page==='member-roster'&&staff)return rosterPage();
 if(page==='schedule')return heading('練習・試合日程','会場・集合時間を確認して、練習に備えよう。',staff?'<button class="lime" onclick="eventForm()">＋ 日程を追加</button>':'')+`<div class="toolbar"><label>種別 <select class="filter" onchange="filterEvents(this.value)"><option value="">すべて</option><option>練習</option><option>試合</option><option>体験会</option></select></label></div><div id="event-list">${eventList(events,staff)}</div>`;
 if(page==='condition'&&staff&&conditionEvent?.kind==='体験会')return heading('体験予約者一覧','選択した体験会への申込者を表示します。')+`<label class="field">対象日程<select onchange="activeEvent=this.value;dashboard()">${events.map(e=>`<option value="${e.id}" ${activeEvent===e.id?'selected':''}>${esc(e.date+' '+e.title)}</option>`).join('')}</select></label><div class="card">${trialBookingList(conditionEvent)}</div>`;
 if(page==='condition')return staff?heading('体調報告一覧・実出席管理','対象日程の全員分をまとめて確認できます。画面表示中は約15秒ごとに更新します（操作中は停止）。')+`<div class="toolbar"><label>対象日程 <select class="filter" onchange="activeEvent=this.value;dashboard()">${events.map(e=>`<option value="${e.id}" ${activeEvent===e.id?'selected':''}>${e.date} ${esc(e.title)}</option>`).join('')}</select></label></div>`+stats([['対象メンバー',conditionMembers.length,'人'],['体調報告済み',reported.length,'人'],['出席予定（遅刻・早退を含む）',selectedReports.filter(r=>['出席','遅刻・早退','遅刻','早退'].includes(r.attendance)).length,'人'],['実出席',selectedReports.filter(r=>r.actual==='出席').length,'人']])+`<div class="card"><h2>${esc(conditionEvent?.date||'')} ${esc(conditionEvent?.title||'日程なし')}</h2>${conditionEvent?categoryTags(conditionEvent):''}<p class="hint">この日程・所属区分に該当する会員だけを表示します。</p></div>`+coachConditionRows(conditionMembers,selectedReports):memberReport();
 if(page==='results')return heading('試合結果・動画','チームの成長を振り返ろう。',admin?'<button class="lime" onclick="resultForm()">＋ 結果を追加</button>':'')+resultsCalendar()+`<div id="selected-results" class="selected-game-results">${resultsForDate().map(r=>`<article class="card"><div class="toolbar"><span class="tag">${esc(r.group_name)}</span>${articleNew('results',r.id)}<span class="hint">${dateLabel(r.date)}</span>${admin?`<button class="lime result-edit-button" onclick="resultForm('${r.id}')">編集</button>`:''}</div><div class="score"><span>SHINING<br>CHEETAHS</span><strong>${r.ours} <span class="muted">–</span> ${r.theirs}</strong><span>${esc(r.opponent)}</span></div><p>${esc(r.note)}</p>${resultLinks(r)}</article>`).join('')||'<div class="card empty">カレンダーの試合名を押すと、その試合の結果・動画・記録が表示されます。</div>'}</div>`+resultHistoryLinks(staff)+(admin?'<section class="card stats-import-entry"><h2>個人の試合記録をファイルから登録</h2><p>Excel（.xlsx）またはCSVを選び、内容を確認してから取り込みます。</p><button class="btn lime" onclick="statsImportForm()">↑ Excel・CSVから個人記録を取り込む</button></section>':'');
 if(['members','staff-members'].includes(page))return memberDirectoryPage(admin);
 if(page==='trials')return heading('体験会の申込','申込はこの画面と、在籍生徒を含む同じExcelファイルに保存されます。','<a class="btn lime" href="/basketball-club/api/excel">在籍生徒・体験申込のExcel</a>')+`<p class="hint">未確認 ${unreadTrials().length} 件 ／ 全 ${data.trials.length} 件。確認状況はコーチ・管理者で共有します。画面を開いている間は約15秒ごとに更新します。</p><div class="card table-wrap"><table><thead><tr><th>確認状況</th><th>申込日時</th><th>お名前 / 学年</th><th>体験会・日時</th><th>保護者名</th><th>電話番号</th><th>メールアドレス</th><th>LINE ID</th><th>連絡事項</th><th>操作</th></tr></thead><tbody>${data.trials.map(t=>{const e=events.find(e=>e.id===t.event_id);return `<tr><td><span class="tag ${t.reviewed_at?'gray':'warn'}">${t.reviewed_at?'確認済み':'未確認'}</span></td><td>${esc(t.created)}</td><td><b>${esc(t.name)}</b><br>${esc(t.grade)}</td><td>${esc(e?.title||t.event_id)}<br>${esc(e?.date||'')} ${esc(e?.time||'')}</td><td>${esc(t.parent_name||'—')}</td><td>${esc(t.phone||'—')}</td><td>${esc(t.email||'—')}</td><td>${esc(t.line_id||'—')}</td><td style="white-space:pre-wrap;min-width:180px">${esc(t.note||'—')}</td><td>${t.reviewed_at?`<span class="hint">${esc(t.reviewer_name||t.reviewed_by)}<br>${esc(t.reviewed_at)}</span>`:`<button class="outline small" onclick="reviewTrial('${t.id}',this)">確認済みにする</button>`}</td></tr>`}).join('')}</tbody></table>${!data.trials.length?'<div class="empty">まだ申し込みはありません。公開ページから試せます。</div>':''}</div>`;
 if(page==='excel')return staffActivityPage();
 if(page==='settings')return settings();
 return '';
}
function eventList(events,staff){return events.map(e=>`<div class="card" style="margin-bottom:16px"><div class="page-heading" style="margin-bottom:12px"><div><span class="tag ${e.kind==='試合'?'warn':''}">${esc(e.kind)}</span><h2 style="margin:9px 0">${esc(e.title)}</h2><p>${dateLabel(e.date)}　${esc(e.time)} ／ ${esc(e.group_name)}</p></div>${staff?`<button class="outline small" onclick="eventForm('${e.id}')">編集</button>`:`<button class="lime small" onclick="activeEvent='${e.id}';location.hash='condition';render();document.getElementById('member-report')?.scrollIntoView()">出欠を報告</button>`}</div><p style="margin:0;font-size:14px">会場：${esc(e.place)}<br>${esc(e.note)}</p></div>`).join('')||'<div class="card empty">日程はありません。</div>'}
function filterEvents(kind){$('#event-list').innerHTML=eventList(data.events.filter(e=>!kind||e.kind===kind),user.role!=='member')}
function reportHistory(rs){const reports=rs.filter(hasCondition).slice().sort((a,b)=>{const date=r=>data.events.find(e=>e.id===r.event_id)?.date||r.updated||'';return date(b).localeCompare(date(a))||(b.updated||'').localeCompare(a.updated||'');});const card=r=>`<article class="card"><b>${esc(data.events.find(e=>e.id===r.event_id)?.date||'')} ${esc(data.events.find(e=>e.id===r.event_id)?.title||'')}</b><p>体の調子：${conditionValue(r,'body_condition')}<br>心の調子：${conditionValue(r,'mind_condition')}<br>朝ご飯：${conditionValue(r,'breakfast')}</p><p class="service-text">調子の悪いところ：${esc(r.unwell_area||'—')}<br>その他の連絡事項：${esc(r.note||'—')}</p></article>`;return reports.length?`<div class="stack condition-history">${reports.slice(0,3).map(card).join('')}</div>${reports.length>3?`<details class="condition-history-more"><summary><span class="when-closed">もっと見る（残り${reports.length-3}件）</span><span class="when-open">閉じる（最新3件）</span></summary><div class="stack">${reports.slice(3).map(card).join('')}</div></details>`:''}`:'<div class="empty">まだ報告はありません。</div>'}

function memberReport(){return conditionOnly();}
async function submitReport(ev){ev.preventDefault();await submit(ev,'report',Object.fromEntries(new FormData(ev.target)),'コーチに体調・出欠を送信しました。')}
async function saveActual(uid,value){try{const r=await api('actual',{user_id:uid,event_id:activeEvent,actual:value});await refresh();toast(r.excel.ok?'出欠を記録し、Excelを更新しました。':r.excel.message)}catch(e){toast(e.message);await refresh()}}
function memberTable(us,admin){return `<table class="member-directory-table"><thead><tr><th>氏名 / ID</th><th>${page==='staff-members'?'担当学年':'学年'}</th>${page==='staff-members'?'<th>スタッフ区分</th>':'<th>学校名</th><th>カテゴリー区分</th>'}<th>権限</th><th>在籍状況</th>${page==='staff-members'?'':'<th>実際の出欠</th>'}${admin&&page!=='staff-members'?'<th>ログイン承認</th><th>承認操作</th>':''}${admin?'<th>管理</th>':''}</tr></thead><tbody>${us.map(m=>`<tr><td>${page!=='staff-members'?guardianCallButton(m):''}<b>${esc(m.name)}</b><br><span class="hint">${esc(m.id)}</span></td><td>${page==='staff-members'?staffAssignmentTags(m.grade):esc(m.grade)}</td>${page==='staff-members'?`<td>${esc(m.staff_kind||'コーチ')}</td>`:`<td>${esc(m.school||'未登録')}</td><td>${staffAssignmentTags(m.categories)}</td>`}<td>${({member:'会員',coach:'コーチ',admin:'管理者'})[m.role]}</td><td><span class="tag ${m.active?'':'gray'}">${esc(enrollmentStatusText(m.enrollment)||(m.active?'在籍':'退会'))}</span></td>${page==='staff-members'?'':`<td>${m.role==='member'?`<button class="outline small" onclick="memberActualHistory('${m.id}')">出欠履歴を見る</button>`:'—'}</td>`}${admin&&page!=='staff-members'?`<td>${memberRegistrationStatus(m)}</td><td>${memberRegistrationControls(m)}</td>`:''}${admin?`<td><div class="member-management-actions"><button class="outline small" onclick="userForm('${m.id}')">編集</button>${adminFull()?`<button class="outline small" data-id="${esc(m.id)}" onclick="resetCredentialForm(this.dataset.id)">ID・PWをリセット</button>`:''}${page==='staff-members'?`<button class="outline small" data-id="${esc(m.id)}" onclick="staffIntroForMember(this.dataset.id)">紹介を編集</button>${adminFull()?`<button class="lime small" type="button" data-id="${esc(m.id)}" onclick="approvalPerson=this.dataset.id;location.hash='staff-approval-settings'">活動承認ページへ</button>${m.id!==user.id&&m.id!=='admin01'?`<button class="outline small" type="button" data-id="${esc(m.id)}" onclick="removeStaff(this.dataset.id)">削除</button>`:''}`:''}`:''}${m.role==='member'?`<button class="outline small" onclick="removeMember('${m.id}')">削除</button>`:''}</div></td>`:''}</tr>`).join('')}</tbody></table>`}
function filterMembers(q){const staffPage=page==='staff-members';$('#member-table').innerHTML=memberTable(data.users.filter(u=>(staffPage?['coach','admin'].includes(u.role):u.role==='member')&&(u.name+u.id).toLowerCase().includes(q.toLowerCase())),user.role==='admin')}
function memberDirectoryPage(admin){const staffPage=page==='staff-members',people=data.users.filter(u=>staffPage?['coach','admin'].includes(u.role):u.role==='member'),status=data.member_input_status;return (staffPage&&adminFull()?coachRegistrationPanel():'')+heading(staffPage?'コーチ・スタッフ一覧':'会員一覧',staffPage?'コーチ・スタッフの所属・権限・在籍状況を管理します。':'学年は毎年4月1日に自動更新します。休会中もログインできます。退会するとログインできなくなります。',admin?'<button class="lime" onclick="userForm()">＋ '+(staffPage?'スタッフ':'会員')+'を追加</button>':'')+`${adminFull()&&staffPage?adminAccessPanel():''}${admin&&!staffPage?registrationApprovals():''}${admin?`<details class="card"><summary>ローカルExcelからの反映</summary><p>固定PCの「data / 会員スタッフ入力.xlsx」の「${staffPage?'スタッフ入力':'会員入力'}」シートを編集して保存してください。デモサーバー起動中は約5秒ごとに確認します。</p><p>住所・電話番号・保護者氏名など「ローカルのみ」の列はサイトへ取り込みません。ログイン・日程表示に必要な氏名、ID、所属などを反映します。</p><p>行を削除してもアカウントは削除されません。「在籍状況」を「退会」または「停止」にするとログインを停止します。初期パスワードは新規IDのみ使用し、登録後はExcelの該当欄を空にできます。</p><p class="hint">${esc(status?.message||'入力Excelは未反映です。')} ${esc(status?.updated||'')}</p><p class="hint">本番WordPressと固定PC間の同期は、本番導入時に接続します。現在はこのデモを動かしているPCのExcelを読み込みます。</p></details>`:''}<div class="card"><div class="toolbar"><input class="filter" placeholder="名前・IDで検索" aria-label="会員検索" oninput="filterMembers(this.value)">${admin?(!staffPage?'<button type="button" class="lime" onclick="downloadMemberAttendance()">全会員の出欠履歴CSV</button>':'<button type="button" class="lime" onclick="downloadStaffDirectory()">コーチ・スタッフ一覧CSV</button>'):''}</div><div class="member-scroll-controls"><span>↔ 左右にスクロールできます</span><input type="range" min="0" max="100" value="0" aria-label="会員一覧の横スクロール" oninput="scrollMemberTable(this.value)"></div><div class="table-wrap" id="member-table" onscroll="syncMemberScroll(this)">${memberTable(people,admin)}</div></div>`;}

function selectField(label,name,values,current){return `<label class="field">${label}<select name="${name}">${values.map(v=>{const pair=Array.isArray(v)?v:[v,v];return `<option value="${esc(pair[0])}" ${String(current)===String(pair[0])?'selected':''}>${esc(pair[1])}</option>`}).join('')}</select></label>`}
function userForm(id){const m=data.users.find(u=>u.id===id)||{role:page==='staff-members'?'coach':'member',active:1};modal((page==='staff-members'?'スタッフ':'会員')+(id?'を編集':'を追加'),`<form onsubmit="saveUser(event,'${id||''}')"><div class="form-grid">${!id&&m.role==='member'?`<input type="hidden" name="id" value="player_${crypto.randomUUID().replaceAll('-','').slice(0,16)}"><p class="hint">選手を登録後、専用の登録コードを保護者へ案内してください。ログインID・パスワードは保護者が設定します。</p>`:field('会員ID（変更不可）','id',m.id||'')}${field('氏名','name',m.name||'')}${m.role==='member'?`<div class="full">${field('学校名','school',m.school||'','text',false)}</div>`:''}<div data-member-grade ${m.role!=='member'?'hidden':''}>${selectField('学年','grade',accountGrades,m.role==='member'?(m.grade||'年長'):'年長')}</div><fieldset class="staff-assignment-options" data-staff-assignment ${m.role==='member'?'hidden':''}><legend>担当学年・カテゴリー（複数選択可）</legend>${staffAssignmentGroups.map(group=>`<label class="check-row"><input type="checkbox" name="staff_assignments" value="${group}" ${splitStaffAssignments(m.grade).includes(group)?'checked':''}>${coachCategoryLabel(group)}</label>`).join('')}</fieldset><div data-member-only ${m.role!=='member'?'hidden':''}>${selectField('カテゴリー区分','categories',memberCategoryOptions(m.categories),m.categories||'男子A')+'<p class="hint">（会費用カテゴリーとは別）</p>'}</div>${selectField('権限','role',[['member','会員'],['coach','コーチ'],['admin','管理者']],m.role).replace('<select ','<select onchange="toggleStaffAssignment(this.value);staffRoleChanged(this)" ')}${m.role==='member'?enrollmentStatusField('enrollment_status',m.enrollment||{status:m.active?'在籍':'退会'}):selectField('在籍状況','active',[[1,'在籍'],[0,'退会']],m.active)}<div class="full" data-member-only ${m.role!=='member'?'hidden':''}>${field('兄弟の紐づけ用グループID（任意）','family_id',m.family_id||'','text',false)}</div></div>${m.role!=='member'?field(id?'新しいパスワード（変更時のみ）':'初期パスワード（任意・登録コードで本人が設定）','password','','password',false):''}<p class="hint">同じ家族IDを設定した会員は、1回のログインで相互に切り替えられます。別家庭には異なるIDを設定してください。スタッフには適用しません。退会者は切り替え対象から外れます。</p>${id&&m.role==='member'?`<section class="member-form-guardians"><h3>保護者情報</h3>${memberGuardianList(m)}</section>`:''}${id&&m.role==='member'?memberInvitePanel(id):''}<div class="error" role="alert"></div><div class="dialog-actions"><button class="lime">保存する</button></div></form>`);if(id)$('#modal [name=id]').readOnly=true;if(page==='staff-members')initStaffPermissions(m);}
async function saveUser(ev,id){ev.preventDefault();const formData=new FormData(ev.target),d=Object.fromEntries(formData);if(d.role!=='member')d.grade=formData.getAll('staff_assignments').join('、');delete d.staff_assignments;if(page==='staff-members'&&d.id!=='admin01'&&d.id!==user.id){d.staff_permissions=d.role==='admin'?(ev.target.staffPermissions||{}):{};d.staff_permission_revision=ev.target.staffPermissionRevision||0;d.role='coach';}if(d.enrollment_status)d.active=d.enrollment_status==='即日退会'?'0':'1';if(d.active==='0'){const ok=await confirmAction('退会・ログイン停止にしますか？','この会員のログインを停止します。過去の記録は残ります。');if(!ok)return;}await submit(ev,'user',d,'会員情報を保存しました。')}
async function confirmAction(title,message){return window.confirm(title+'\n'+message)}
function eventForm(id,duplicate=false){const sourceId=id;const e=data.events.find(e=>e.id===id)||{date:new Date().toLocaleDateString('sv-SE'),kind:'練習'};if(duplicate)id='';modal(duplicate?'日程を複製（日付を確認してください）':id?'日程を編集':'日程を追加',`${id&&e.kind==='練習'?`<p><button type="button" class="lime" onclick="openWeeklyRepeat('${id}')">毎週繰り返し登録</button></p>`:''}<form ${id?'data-existing-event="true"':''} onsubmit="saveEvent(event,'${id||''}')">${scheduleTitleField(e.title||'',e.kind)}<div class="form-grid">${field('日付','date',e.date,'date')}${field('時間','time',e.time||'09:00〜11:00')}${eventCategoryField(e.group_name||'男子A')}</div>${venueFields(e.place||'',e.address||'')}${field('地図URL（Googleマップなど・任意）','map_url',e.map_url||'','url',false)}<label class="field">詳細・集合時間<textarea name="note">${esc(e.note||'')}</textarea></label><div class="error" role="alert"></div><div class="dialog-actions">${id?`<button type="button" class="outline danger" onclick="deleteRecord('event','${id}')">日程を削除</button>`:''}<button class="lime">保存する</button></div></form>`)}
async function saveEvent(ev,id){ev.preventDefault();await submit(ev,'event',{...Object.fromEntries(new FormData(ev.target)),id},'日程を保存しました。')}
function resultForm(id){if(user?.role!=='admin'){toast('管理者のみ編集できます。');return;}const r=data.results.find(r=>r.id===id)||{date:new Date().toLocaleDateString('sv-SE'),group_name:page==='results'?resultsCategory:teamHistoryCategory};modal(id?'試合結果を編集':'試合結果を追加',`<form onsubmit="saveResult(event,'${id||''}')"><div class="form-grid">${field('日付','date',r.date,'date')}${selectField('対象チーム','group_name',[['','選択してください'],...[...new Set(['男子A','男子B','女子U９','女子U12','U15アドバンス','U15ベーシック',...(r.group_name?[r.group_name]:[])])].map(x=>[x,x])],r.group_name||'').replace('<select ','<select required ')}${field('対戦相手','opponent',r.opponent||'')}${field('自チームの得点','ours',r.ours??0,'number')}${field('相手の得点','theirs',r.theirs??0,'number')}</div><label class="field">試合の振り返り<textarea name="note">${esc(r.note||'')}</textarea></label>${field('YouTube限定公開URL','video',r.video||'','url',false)}<p class="hint">YouTubeで限定公開に設定した動画のURLを入力してください。URLを知っている人はYouTube上で視聴できます。</p><div class="error" role="alert"></div><div class="dialog-actions">${id?`<button type="button" class="outline danger" onclick="deleteRecord('result','${id}')">結果を削除</button>`:''}<button class="lime">保存する</button></div></form>`)}
async function saveResult(ev,id){ev.preventDefault();await submit(ev,'result',{...Object.fromEntries(new FormData(ev.target)),id},'試合結果を保存しました。')}
async function deleteRecord(type,id){if(!await confirmAction('削除しますか？',type==='event'?'この日程の出欠・体調報告・体験申込も削除されます。':'試合結果を削除します。'))return;try{await api(type,{id,delete:true});$('#modal').close();await refresh();toast('削除しました。')}catch(e){toast(e.message)}}
function youtubeEmbed(url){try{const u=new URL(url);let id=u.hostname==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.split('/').pop();return /^[\w-]{11}$/.test(id)?'https://www.youtube-nocookie.com/embed/'+id:''}catch{return ''}}
function settings(){const c=pub.content;const labels={region:'活動地域',seo_title:'検索結果のページタイトル',seo_description:'検索結果の説明文',name:'チーム名',subname:'日本語表記',headline:'トップの見出し',intro:'トップの紹介文',philosophy:'チーム理念',recruit:'募集案内',notice:'お知らせ',place:'練習場所',address:'住所・アクセス',equipment:'持ち物',instagram:'Instagram URL',facebook:'FacebookページのURL（未登録は空欄）',line:'公式LINEの友だち追加URL（未登録は空欄）',hero:'トップ写真のURL',gallery:'練習写真のURL',accent:'アクセントカラー'};return heading('サイト編集','公開ページの内容を編集して保存すると、すぐに反映されます。','<div class="site-edit-actions"><a class="btn outline" href="/#home" target="_blank" rel="noopener noreferrer">公開ページを見る</a><button type="button" class="outline" onclick="backFromSiteEditor()">一つ前の画面に戻る</button></div>')+`<div class="card"><form onsubmit="saveSettings(event)"><div class="form-grid">${Object.entries(labels).map(([k,label])=>['headline','intro','philosophy','recruit','seo_description'].includes(k)?`<label class="field full">${label}<textarea name="${k}">${esc(c[k])}</textarea></label>`:field(label,k,c[k],k==='accent'?'color':'text',false)).join('')}</div>${practiceScheduleEditor(c)}<p class="hint">写真は https:// の画像URLで指定します。Instagram投稿ページのURLでは画像を直接表示できません。公式写真が未設定の場合は、練習写真の案内を表示します。</p><div class="error" role="alert"></div><button class="lime">変更を保存する</button></form></div>`}
async function saveSettings(ev){ev.preventDefault();const payload=Object.fromEntries(new FormData(ev.target));if(ev.target.querySelector('.practice-schedule-editor'))payload.practice_slots=JSON.stringify([...ev.target.querySelectorAll('.practice-slot-row')].map(row=>({group:row.dataset.group,day:row.querySelector('[data-slot=day]').value,start:row.querySelector('[data-slot=start]').value,end:row.querySelector('[data-slot=end]').value})));await submit(ev,'content',payload,'公開ページを更新しました。')}
async function syncExcel(b){b.disabled=true;try{const r=await api('sync',{});await refresh();toast(r.excel.ok?'Excelを更新しました。':r.excel.message)}catch(e){toast(e.message)}finally{b.disabled=false}}
const originalSettings=settings;
settings=function(){return originalSettings().replace('<div class="form-grid">',`<div class="form-grid"><label class="field">トップ写真をアップロード<input type="file" accept="image/jpeg,image/png,image/webp" onchange="uploadPhoto(this,'hero')"></label><label class="field">練習写真をアップロード<input type="file" accept="image/jpeg,image/png,image/webp" onchange="uploadPhoto(this,'gallery')"></label>`).replace('写真は https:// の画像URLで指定します。','写真はアップロード、または https:// の画像URLで指定します。')+`<section class="card"><h2>コーチ・スタッフ紹介の編集</h2><p>写真・自己紹介・担当クラス・審判資格は、コーチ・スタッフ一覧から編集できます。</p><a class="btn outline" href="#staff-members">コーチ・スタッフを編集</a></section>`+otherActivitiesEditor()+trialReviewsEditor()};
async function uploadPhoto(input,target){const f=input.files[0];if(!f)return;if(f.size>5*1024*1024){toast('5MB以下の画像を選択してください。');return}input.disabled=true;try{const encoded=await new Promise((resolve,reject)=>{let r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(f)});const result=await api('upload',{image:encoded});document.querySelector(`[name="${target}"]`).value=result.url;toast('画像を読み込みました。「変更を保存する」で反映します。')}catch(e){toast(e.message)}finally{input.disabled=false}}
let polling=false;
setInterval(async()=>{if(document.querySelector('.edit-conflict-dialog')||switchingMember||polling||document.querySelector('.quick-actual button:disabled,.basket-note-status select[data-saving]')||document.hidden||document.querySelector('dialog[open]')||(page!=='attendance-list'&&document.activeElement?.matches('input,textarea,select'))||['settings','schedule','surveys','account-setup','register','forgot-password','password-reset','billing-settings','billing-individual','portal-admin','staff-approvals','finance-admin','accounting'].includes(page)||(page==='condition'&&user?.role==='member'))return;polling=true;try{if(user){const context=selectedMember;const fresh=await api('data');if(context!==selectedMember)return;if(JSON.stringify(fresh)!==JSON.stringify(data)){const oldIds=new Set((data.trials||[]).map(t=>t.id));const added=(fresh.trials||[]).filter(t=>!oldIds.has(t.id));data=fresh;if(user.role!=='member'&&added.length)toast(`新しい体験申込が${added.length}件届きました。`);if(!['home','philosophy','trial','trial-list','location','login'].includes(page))dashboard()}}else if(['home','philosophy','trial','trial-list','location'].includes(page)){const fresh=await api('public');if(JSON.stringify(fresh)!==JSON.stringify(pub)){pub=fresh;document.documentElement.style.setProperty('--lime',pub.content.accent);publicPage()}}}catch(e){if(e.message==='ログインしてください。'){user=null;data={};location.hash='login';toast('再ログインしてください。')}}finally{polling=false}},15000);
document.addEventListener('change',ev=>{if(ev.target.matches('#modal [name=group_name],#modal [name=kind]')){const form=ev.target.closest('form');const time=form?.querySelector('[name=time]');if(time&&form.querySelector('[name=group_name]')?.value==='中学生'&&form.querySelector('[name=kind]')?.value==='体験会'&&!form.dataset.existingEvent)time.value='19:00〜';}});
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'open_club_schedule',title:'活動日程を開く',description:'ログイン中の会員・スタッフの活動日程を開きます。記録は変更しません。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async input=>{if(!input||Object.keys(input).length)throw Error('入力は空のオブジェクトです。');if(!user)throw Error('ログインしてください。');location.hash='schedule';render();return {page:'schedule',events:data.events.length}}})}catch{}}
function modal(title,body){$('#modal').dataset.editToken=renderEditToken||data.edit_token||'';$('#modal').innerHTML=`<div class="dialog-head"><h2>${esc(title)}</h2><button onclick="$('#modal').close()" aria-label="閉じる">×</button></div>${body}<div class="modal-bottom-actions"><button type="button" class="outline" onclick="this.closest('dialog').close()">閉じる</button></div>`;$('#modal').showModal()}
function field(label,name,value='',type='text',required=true){const input=`<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}>`;return `<label class="field">${label}${type==='date'?`<span class="club-date-display">${input}<span class="club-date-text" aria-hidden="true">${esc(value?String(value).replaceAll('-','/'):'年 / 月 / 日')}</span><span class="club-date-icon" aria-hidden="true">▦</span></span>`:input}</label>`}
function trialForm(id){const e=pub.events.find(e=>e.id===id);modal('体験会に申し込む',`<p>${esc(e.title)}<br>${dateLabel(e.date)} ${esc(e.time)}</p><form onsubmit="submitTrial(event,'${id}')"><div class="form-grid">${field('お子さまのお名前','name')}${selectField('学年','grade',[['','選択してください'],'年長',...Array.from({length:6},(_,i)=>'小学'+(i+1)+'年'),...Array.from({length:3},(_,i)=>'中学'+(i+1)+'年')],'')}${field('保護者のお名前','parent_name')}${field('電話番号','phone','','tel')}</div><label class="field"><span>連絡先の種類 <small style="color:#687782;font-weight:normal">（メールアドレス または LINE IDを選択してください）</small></span><select name="contact_type" onchange="updateTrialContact(this)" required><option value="email">メールアドレス</option><option value="line">LINE ID</option></select></label><label class="field"><span id="trial-contact-label">メールアドレス</span><input name="contact" type="email" required maxlength="200" autocomplete="email"></label><label class="field">ご質問・連絡事項<textarea name="note"></textarea></label><div class="error" role="alert"></div><div class="dialog-actions"><button class="lime">申し込む</button></div></form>`)}
function updateTrialContact(select){const input=select.form.elements.contact,isEmail=select.value==='email';select.form.querySelector('#trial-contact-label').textContent=isEmail?'メールアドレス':'LINE ID';input.type=isEmail?'email':'text';input.autocomplete=isEmail?'email':'off';input.value='';input.placeholder=isEmail?'例：name@example.com':'例：cheetahs_parent';}

async function submitTrial(ev,id){ev.preventDefault();await submit(ev,'trial',{...Object.fromEntries(new FormData(ev.target)),event_id:id},'体験会の申し込みを受け付けました。')}
async function submit(ev,path,payload,message){const b=ev.submitter;b.disabled=true;try{const r=await api(path,payload);$('#modal').close();reportDirty=false;await refresh();toast(r.excel?.ok===false?r.excel.message:message)}catch(e){const err=ev.target.querySelector('.error');if(err)err.textContent=e.message;else toast(e.message)}finally{b.disabled=false}}
window.addEventListener('hashchange',()=>{render();if(['personal-history','team-history','scorecard','condition'].includes(page))window.scrollTo({top:0,behavior:'instant'});});refresh().catch(e=>{$('#app').innerHTML='<div class="wrap section"><h1>サイトを読み込めませんでした</h1><p>'+esc(e.message)+'</p><button onclick="location.reload()">再読み込み</button></div>'});

async function reviewTrial(id,button){button.disabled=true;try{const r=await api('trial_review',{id});await refresh();toast(r.excel?.ok?'確認済みにし、Excelにも反映しました。':r.excel?.message||'確認済みにしました。')}catch(e){toast(e.message)}finally{button.disabled=false}}

function memberAttendanceRows(id,month=''){
 return (data.reports||[]).filter(r=>(!id||r.user_id===id)&&r.actual).map(r=>({r,e:data.events.find(e=>e.id===r.event_id),m:(data.users||[]).find(m=>m.id===r.user_id)})).filter(x=>x.m?.role==='member'&&(!month||x.e?.date?.startsWith(month))).sort((a,b)=>(b.e?.date||'').localeCompare(a.e?.date||'')||(a.e?.time||'').localeCompare(b.e?.time||'')||a.r.user_id.localeCompare(b.r.user_id));
}
function memberActualHistory(id,month='',pageIndex=0){
 const m=data.users.find(u=>u.id===id);if(!m)return;
 const all=memberAttendanceRows(id),months=[...new Set(all.map(x=>x.e?.date?.slice(0,7)).filter(Boolean))].sort().reverse(),rows=memberAttendanceRows(id,month),pages=Math.max(1,Math.ceil(rows.length/10)),current=Math.min(Math.max(0,pageIndex),pages-1),visible=rows.slice(current*10,current*10+10);
 modal(m.name+'さんの実際の出欠',`<p>コーチが記録した実績です。事前の出欠予定とは分けて表示します。</p><div class="member-history-tools"><label class="field">表示する月<select onchange="memberActualHistory('${id}',this.value,0)"><option value="">全期間</option>${months.map(x=>`<option value="${x}" ${month===x?'selected':''}>${x.replace('-','年')}月</option>`).join('')}</select></label><button type="button" class="lime" onclick="downloadMemberAttendance('${id}','${month}')" ${rows.length?'':'disabled'}>この会員のCSVを出力</button></div><p class="hint">${rows.length}件${rows.length?` ／ ${current*10+1}〜${Math.min((current+1)*10,rows.length)}件を表示`:''}。CSVには${month?esc(month)+'の':'全期間の'}全件を出力します。</p><div class="stack">${visible.map(({r,e})=>`<article class="card"><b>${esc(e?.date||'')} ${esc(e?.title||'日程不明')}</b><p>${esc(e?.time||'')} ／ ${esc(e?.place||'')}<br>出欠予定：${esc(r.attendance||'未回答')}<br>実際の出欠：<strong>${esc(r.actual)}</strong></p></article>`).join('')||'<p>この期間の実際の出欠はまだ記録されていません。</p>'}</div>${pages>1?`<div class="member-history-paging"><button type="button" class="outline" ${current===0?'disabled':''} onclick="memberActualHistory('${id}','${month}',${current-1})">前の10件</button><span>${current+1} / ${pages}</span><button type="button" class="outline" ${current===pages-1?'disabled':''} onclick="memberActualHistory('${id}','${month}',${current+1})">次の10件</button></div>`:''}`);
}
function attendanceCsvText(rows){
 const cell=value=>{let s=String(value??'');if(/^[\s]*[=+\-@]/.test(s)||/^[\t\r\n]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};
 const header=['会員ID','氏名','学年（現在）','所属カテゴリー（現在）','日付','活動名','活動カテゴリー','種別','時間','会場','出欠予定','実際の出欠','出欠の連絡事項'];
 return '\uFEFF'+[header,...rows.map(({r,e,m})=>[r.user_id,m.name,m.grade,m.categories,e?.date||'',e?.title||'日程不明',e?.group_name||'',e?.kind||'',e?.time||'',e?.place||'',r.attendance||'未回答',r.actual,(data.scheduling?.attendance||[]).find(a=>a.user_id===r.user_id&&a.event_id===r.event_id)?.note||''])].map(row=>row.map(cell).join(',')).join('\r\n')+'\r\n';
}
function downloadMemberAttendance(id='',month=''){if(user.role!=='admin')return;
 if(!['coach','admin'].includes(user.role))return;
 const rows=memberAttendanceRows(id,month);if(!rows.length){toast('出力する出欠履歴がありません。');return;}
 if(!id)rows.sort((a,b)=>a.r.user_id.localeCompare(b.r.user_id)||(b.e?.date||'').localeCompare(a.e?.date||''));
 const blob=new Blob([attendanceCsvText(rows)],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='出欠履歴_'+(id||'全会員')+'_'+(month||'全期間')+'.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('出欠履歴CSVを出力しました。');
}


function conflictText(value){const labels={user_id:'会員',event_id:'日程',result_id:'試合ID',id:'ID',title:'題名',name:'氏名',date:'日付',time:'時間',place:'会場',kind:'種類',group_name:'活動区分',note:'連絡事項',actual:'実際の出欠',attendance:'出欠予定',reviewed:'確認済みにする',reviewed_at:'確認日時',updated:'更新日時',body:'内容',status:'状態',grade:'学年',categories:'活動区分',amount:'金額',delete:'削除',member_ids:'参加メンバー',published:'公開',publish:'公開する',map_url:'地図URL',visibility:'公開範囲',entries:'選手記録',points:'得点',rebounds:'リバウンド',assists:'アシスト',fouls:'ファウル',ours:'自チーム得点',theirs:'相手得点',opponent:'対戦相手',video:'動画URL'};const lines=(v,depth=0)=>{if(Array.isArray(v))return v.length?v.map((x,i)=>'【'+(i+1)+'】\n'+lines(x,depth+1)).join('\n'):'（なし）';if(v&&typeof v==='object')return Object.entries(v).map(([k,x])=>{if(k==='user_id')x=data.users?.find(u=>u.id===x)?.name||x;if(k==='event_id')x=data.events?.find(e=>e.id===x)?.title||x;return (labels[k]||k)+'：'+lines(x,depth+1)}).join('\n');if(v===true)return 'はい';if(v===false)return 'いいえ';if(v==null||v==='')return '（なし）';if(typeof v==='string'&&/^[{[]/.test(v)){try{return lines(JSON.parse(v),depth+1)}catch{}}return String(v)};return lines(value);}

const staffAssignmentGroups=['男子A','男子B','女子U９','女子U12','U15アドバンス','U15ベーシック'];
function splitStaffAssignments(value){return String(value||'').split(/[、,，\s]+/).filter(Boolean).map(x=>({'U15A':'U15アドバンス','U15B':'U15ベーシック','女子U9':'女子U９'})[x]||x);}
function staffAssignmentTags(value){const groups=splitStaffAssignments(value).filter(v=>staffAssignmentGroups.includes(v));return groups.length?`<div class="staff-assignment-tags">${groups.map(v=>`<span class="tag">${esc(coachCategoryLabel(v))}</span>`).join('')}</div>`:esc(value&&!['スタッフ','運営'].includes(value)?value:'未設定');}
function toggleStaffAssignment(role){document.querySelector('[data-member-grade]').hidden=role!=='member';document.querySelector('[data-staff-assignment]').hidden=role==='member';document.querySelector('[data-member-only]').hidden=role!=='member';}

function staffDirectoryCsv(people){const cell=value=>{let s=String(value??'');if(/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};return '\uFEFF'+[['ID','氏名','担当学年・カテゴリー','スタッフ区分','権限','在籍状況'],...people.filter(m=>m.role!=='member').map(m=>[m.id,m.name,m.grade,m.staff_kind||'コーチ',m.role==='admin'?'管理者':'コーチ',m.active?'在籍':'退会・停止'])].map(row=>row.map(cell).join(',')).join('\r\n')+'\r\n';}
function downloadStaffDirectory(){if(user.role!=='admin')return;const blob=new Blob([staffDirectoryCsv(data.users)],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='コーチ・スタッフ一覧_'+new Date().toLocaleDateString('sv-SE')+'.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('コーチ・スタッフ一覧CSVを出力しました。');}

function memberCategoryOptions(current){return current&&!staffAssignmentGroups.includes(current)?[[current,current+'（現在の登録）'],...staffAssignmentGroups]:staffAssignmentGroups;}

function backFromSiteEditor(){if(history.length>1)history.back();else location.hash="dashboard";}

function scrollMemberTable(value){const table=document.getElementById('member-table');if(table)table.scrollLeft=(table.scrollWidth-table.clientWidth)*Number(value)/100;}
function syncMemberScroll(table){const slider=document.querySelector('.member-scroll-controls input');if(slider)slider.value=table.scrollWidth>table.clientWidth?100*table.scrollLeft/(table.scrollWidth-table.clientWidth):0;}

function adminFull(){return user?.role==='admin'&&user.admin_rank===1;}
function adminSection(route){return ({'member-roster':'schedule','messages':'members','skill-videos':'results','admin-settings':'settings','admin-reviews':'attendance-list','staff-approval-settings':'staff-approvals','attendance-rates':'attendance-list','excel':'staff-approvals','billing-individual':'billing-settings','scorecard':'results','score-records':'results','personal-history':'results','team-history':'results'})[route]||route;}
function adminCan(key,write=false){return adminFull()||(user?.role==='admin'&&(write?['edit']:['view','edit']).includes(user.admin_permissions?.[key]));}
function enforcePagePermissions(){if(page==='staff-attendance'&&data.staff_attendance?.available)return;if(user?.role==='coach')document.querySelectorAll('[onclick*="downloadMemberAttendance"],[onclick*="downloadStaffDirectory"]').forEach(el=>el.hidden=true);const section=adminSection(page);if(user?.delegated_coach&&page==='excel')return;const readOnly=user?.role==='admin'?!adminCan(section,true):user?.role==='coach'&&['schedule','attendance-list','results'].includes(section);if(!readOnly||section==='dashboard')return;const root=document.querySelector('.workspace');if(!root)return;root.querySelectorAll('form input,form select,form textarea,form button').forEach(el=>el.disabled=true);const mutators=/staffIntroForMember|staffIntroForm|resultForm|statsImportForm|scoreImportForm|gameStatsForm|userForm\(|removeMember|memberApprovalForm|registrationReviewForm|eventForm|bulkEventForm|scheduleDocumentForm|removeScheduleDocument|activityDetailsForm|eventDetailsForm|matchRosterForm|confirmAttendance|saveActual|submitStaffApproval|setStaffApproval|approveStaffWeek|staffActivityForm|approvalForm|syncExcel|collectionReceiptForm|feeAdjustment|previewBilling|saveSettings/;root.querySelectorAll('[onclick],[onchange]').forEach(el=>{if(mutators.test((el.getAttribute('onclick')||'')+' '+(el.getAttribute('onchange')||''))){if(el.getAttribute('onclick')?.startsWith('userForm')){el.textContent='詳細';}else el.hidden=true;}});if(section==='schedule'||section==='attendance-list')root.querySelectorAll('button').forEach(el=>{if(/編集|公開|登録|削除|確認済みに|未確認に/.test(el.textContent))el.hidden=true;});root.querySelectorAll('[data-billing-profiles] select').forEach(el=>{if(el.getAttribute('onchange')?.includes('filterBillingMember'))el.disabled=false;});}
const dashboardWithPermissions=dashboard;dashboard=function(){const scrolls=new Map([...document.querySelectorAll('[data-attendance-event]')].map(el=>[el.dataset.attendanceEvent,el.querySelector('.table-wrap')?.scrollLeft||0]));dashboardWithPermissions();enforcePagePermissions();document.querySelectorAll('[data-attendance-event]').forEach(el=>{const table=el.querySelector('.table-wrap');if(table)table.scrollLeft=scrolls.get(el.dataset.attendanceEvent)||0;});};
const modalWithPermissions=modal;modal=function(title,body){modalWithPermissions(title,body);if(user?.role==='coach')document.querySelectorAll('#modal [onclick*="downloadMemberAttendance"],#modal [onclick*="downloadStaffDirectory"]').forEach(el=>el.hidden=true);if(user?.role==='admin'&&!adminCan(adminSection(page),true)&&page!=='dashboard'&&!(page==='staff-attendance'&&data.staff_attendance?.available)&&!(user.delegated_coach&&page==='excel'))document.querySelectorAll('#modal form input,#modal form select,#modal form textarea,#modal form button,#modal .member-form-guardians button').forEach(el=>el.disabled=true);};

function eventCategoryField(value){const selected=String(value).split(/[、,]/).map(x=>x.trim()==='年長・小学生'?'小学生':x.trim()).filter(Boolean),options=[...new Set(['男子A','男子B','女子U９','女子U12','U15アドバンス','U15ベーシック','小学生','中学生','合同合宿','イベント',...selected])];return `<div class="field event-category-field"><span>活動区分</span><input type="hidden" name="group_name" value="${esc(selected.join('、'))}"><details class="event-category-picker"><summary><span>${esc(selected.join('、')||'選択してください')}</span></summary><div>${options.map(x=>`<label class="check-row"><input type="checkbox" value="${esc(x)}" ${selected.includes(x)?'checked':''} onchange="updateEventCategories(this)">${esc(x)}</label>`).join('')}</div></details><small class="hint">（複数選択できます）</small></div>`;}
function updateEventCategories(input){const box=input.closest('.event-category-field'),values=[...box.querySelectorAll('input[type="checkbox"]:checked')].map(x=>x.value);box.querySelector('input[name="group_name"]').value=values.join('、');box.querySelector('summary span').textContent=values.join('、')||'選択してください';}


function openPublicMenu(){if(document.getElementById('public-menu-dialog'))return;const dialog=document.createElement('dialog');dialog.id='public-menu-dialog';dialog.setAttribute('aria-labelledby','public-menu-title');dialog.innerHTML=`<div class="public-menu-heading"><div><span>三木　SHINING CHEETAHS</span><h2 id="public-menu-title">メニュー</h2></div><button type="button" aria-label="メニューを閉じる" onclick="this.closest('dialog').close()">×</button></div><nav aria-label="スマホメニュー">${document.querySelector('.header .navlinks').innerHTML}</nav><div class="modal-bottom-actions"><button type="button" class="outline" onclick="this.closest('dialog').close()">閉じる</button></div>`;dialog.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>dialog.close()));dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});const overflow=document.body.style.overflow;dialog.addEventListener('close',()=>{document.body.style.overflow=overflow;dialog.remove();document.querySelector('.public-menu-trigger')?.focus({preventScroll:true});},{once:true});document.body.append(dialog);document.body.style.overflow='hidden';dialog.showModal();}

// Consistent, soft colors for document actions across pages and dialogs.
function styleDocumentActions(){document.querySelectorAll('a.btn,button').forEach(el=>{const label=el.textContent.replace(/\s/g,'');const spreadsheet=/Excel|エクセル|CSV/i.test(label),pdf=/PDF/i.test(label);el.classList.toggle('document-sheet-action',spreadsheet&&!pdf);el.classList.toggle('document-pdf-action',pdf&&!spreadsheet);});}
new MutationObserver(styleDocumentActions).observe(document.body,{childList:true,subtree:true,characterData:true});styleDocumentActions();

function otherActivitiesEditor(){const c=pub.content;const input=(key,label,area=false)=>area?`<label class="field">${label}<textarea name="${key}" rows="4">${esc(c[key]||'')}</textarea></label>`:field(label,key,c[key]||'','text',false);return `<details class="card other-activities-editor"><summary><b>その他の活動を編集</b></summary><p class="hint">トップページの「その他の活動」専用の編集欄です。</p><form onsubmit="saveSettings(event)"><h3>コンディショニングコーチ</h3>${input('conditioning_category','青いカテゴリラベル')}${input('conditioning_title','見出し')}${input('conditioning_intro','開催案内',true)}${input('conditioning_name','コーチ名')}<label class="field">コーチ写真をアップロード<input type="file" accept="image/jpeg,image/png,image/webp" onchange="uploadPhoto(this,'conditioning_photo')"></label>${input('conditioning_photo','写真URL（空欄はNO IMAGE）')}${input('conditioning_comment','自己紹介・サポート内容',true)}${input('conditioning_contact','連絡についての案内',true)}${input('conditioning_instagram','コーチのInstagram URL')}<hr><h3>みきティブ</h3>${input('mikitiv_category','青いカテゴリラベル')}${input('mikitiv_title','見出し')}${input('mikitiv_intro','認定登録の紹介',true)}${input('mikitiv_heading','説明の見出し')}${input('mikitiv_description','説明文',true)}${input('mikitiv_url','みきティブについてのURL')}${input('mikitiv_clubs_url','認定クラブ一覧のURL')}<div class="error" role="alert"></div><div class="registration-actions"><button class="lime">その他の活動を保存</button></div></form></details>`;}

function practiceSlotRow(group,row={}){return `<div class="practice-slot-row" data-group="${esc(group)}"><label class="field">曜日<select data-slot="day">${['月','火','水','木','金','土','日'].map(day=>`<option ${day===(row.day||'土')?'selected':''}>${day}</option>`).join('')}</select></label><label class="field">開始時間<input data-slot="start" type="time" value="${esc(row.start||'')}" required></label><label class="field">終了時間（任意）<input data-slot="end" type="time" value="${esc(row.end||'')}"></label><button type="button" class="outline" onclick="this.closest('.practice-slot-row').remove()">削除</button></div>`;}
function practiceScheduleEditor(c){let slots=[];try{slots=JSON.parse(c.practice_slots||'[]')}catch{}if(!slots.length&&c.practice){for(const part of c.practice.split('／')){const group=part.includes('中学生')?'中学生':'年長・小学生';for(const m of part.matchAll(/([月火水木金土日])曜日?\s*(\d{1,2}:\d{2})[〜～~－-](\d{1,2}:\d{2})?/g))slots.push({group,day:m[1],start:m[2].padStart(5,'0'),end:m[3]?.padStart(5,'0')||''});}}return `<section class="practice-schedule-editor"><h3>通常の練習日</h3><p class="hint">対象ごとに複数の曜日・時間を登録できます。</p>${['年長・小学生','中学生'].map(group=>`<fieldset class="card"><legend>${group}</legend><div class="practice-slot-list">${slots.filter(r=>r.group===group).map(r=>practiceSlotRow(group,r)).join('')}</div><button type="button" class="outline" data-group="${group}" onclick="this.previousElementSibling.insertAdjacentHTML('beforeend',practiceSlotRow(this.dataset.group))">＋ 練習日を追加</button></fieldset>`).join('')}</section>`;}

function adminTopGroups(){return '<div class="admin-top-groups"><a class="card" href="#admin-settings"><span class="admin-shortcut-icon">⚙</span><strong>各種設定</strong></a><a class="card" href="#admin-reviews"><span class="admin-shortcut-icon">✓</span><strong>各種確認</strong></a></div>';}

function clubPhoneButton(label,cls=''){return `<a class="btn lime club-phone ${cls}" href="tel:09032886636"><span aria-hidden="true">☎</span> ${label}</a>`;}
function staffHomeContacts(){return `<div class="toolbar home-contact-actions">${adminCan('members')?'<a class="btn outline" href="#members">会員一覧へ</a>':''}${adminCan('attendance-list')?'<a class="btn lime" href="#attendance-list">出欠を確認・入力</a>':''}</div>`;}
function guardianCallButton(m){const parents=data.guardian_contacts?.[m.id]||[];if(parents.length===1&&parents[0].phone)return `<a class="btn outline small guardian-call" href="tel:${esc(parents[0].phone)}" aria-label="${esc(m.name)}さんの${esc(parents[0].name)}へ電話">☎ 保護者へ連絡</a>`;return `<button type="button" class="outline small guardian-call" data-member="${esc(m.id)}" onclick="chooseGuardianContact(this.dataset.member)">☎ 保護者へ連絡</button>`;}
function chooseGuardianContact(id){const m=data.users.find(u=>u.id===id),parents=data.guardian_contacts?.[id]||[];modal('保護者へ連絡',`<p>${esc(m?.name||'')}さんの連絡先</p><div class="guardian-contact-options">${parents.map(p=>`<div class="card"><b>${esc(p.name)}</b>${p.phone?`<a class="btn lime" href="tel:${esc(p.phone)}">☎ ${esc(p.phone)}へ電話</a>`:'<p class="hint">電話番号未登録</p>'}</div>`).join('')||'<p>保護者が登録されていません。</p>'}</div>${parents.some(p=>!p.phone)?'<p class="hint">会員の「登録情報」または管理者の会員編集から、保護者の電話番号を登録できます。</p>':''}`);}

function trialDetailCard(e){const d=new Date(e.date+'T12:00:00');return `<button type="button" class="event-card trial-detail-card" data-event="${esc(e.id)}" onclick="trialForm(this.dataset.event)" aria-label="${esc(e.date+' '+e.title+'を予約する')}"><span class="date-block"><small>${d.getMonth()+1}月</small><strong>${d.getDate()}</strong><small>${['SUN','MON','TUE','WED','THU','FRI','SAT'][d.getDay()]}</small></span><span><span class="tag">${esc(e.group_name.replace(/年長[・、]?/g,''))}</span><strong class="trial-card-title">${esc(e.title)}</strong><span class="trial-card-meta">${esc(e.time)}<br>${esc(e.place)}</span></span><span class="btn lime trial-card-more">体験会を予約する</span></button>`;}
function openTrialDetails(id){const e=pub.events.find(e=>e.id===id);if(!e)return;modal('体験会の詳細',`<h3>${esc(e.title)}</h3><p>${esc(e.date)} ${esc(e.time)}</p><p>会場：${esc(e.place)}</p><p class="service-text">${esc((e.note||'').replace(/年長[・、]?/g,''))}</p><p>持ち物：${esc(pub.content.equipment||'')}</p><button type="button" class="lime" data-event="${esc(e.id)}" onclick="trialForm(this.dataset.event)">この体験会に参加する</button>`);}

let skillVideoCategory='';
function skillVideosPage(){const edit=adminCan('results',true),rows=(data.skill_videos||[]).filter(v=>!skillVideoCategory||v.group_name===skillVideoCategory),groups=[...new Set((data.skill_videos||[]).map(v=>v.group_name))];return heading('スキルアップ動画','練習や自主トレに役立つ動画を確認できます。',edit?'<button class="lime" onclick="skillVideoForm()">＋ 動画を追加</button>':'')+`<label class="field">対象カテゴリー<select onchange="skillVideoCategory=this.value;dashboard()"><option value="">すべて</option>${groups.map(g=>`<option ${g===skillVideoCategory?'selected':''}>${esc(g)}</option>`).join('')}</select></label><div class="skill-video-grid">${rows.map(v=>`<article class="card skill-video-card"><span class="tag">${esc(v.group_name)}</span><h2>${esc(v.title)}</h2><p class="hint">${esc(v.date)}</p><iframe src="${esc(youtubeEmbed(v.video))}" title="${esc(v.title)}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe><p class="service-text">${esc(v.note)}</p><div class="toolbar"><a class="text-link" href="${esc(v.video)}" target="_blank" rel="noopener noreferrer">YouTubeで見る</a>${edit?`<button class="outline" data-id="${esc(v.id)}" onclick="skillVideoForm(this.dataset.id)">編集</button>`:''}</div></article>`).join('')||'<div class="card empty">スキルアップ動画はまだ登録されていません。</div>'}</div>`;}
function skillVideoForm(id=''){if(!adminCan('results',true))return;const v=data.skill_videos.find(v=>v.id===id)||{id:'',date:new Date().toLocaleDateString('sv-SE'),group_name:'全員',revision:0};modal(id?'スキルアップ動画を編集':'スキルアップ動画を追加',`<form onsubmit="saveSkillVideo(event,'${esc(id)}',${v.revision})">${field('タイトル','title',v.title||'').replace('<input ','<input maxlength="120" ')}<div class="form-grid">${field('日付','date',v.date,'date')}</div><label class="field">説明・練習のポイント<textarea name="note">${esc(v.note||'')}</textarea></label>${field('YouTube限定公開URL','video',v.video||'','url')}<p class="hint">試合動画と同様、YouTubeのURLを登録します。限定公開動画もURLを知っている人は閲覧できます。</p><div class="error" role="alert"></div><div class="dialog-actions">${id?`<button type="button" class="outline danger" onclick="deleteSkillVideo('${esc(id)}',${v.revision})">動画を削除</button>`:''}<button class="lime">保存する</button></div></form>`);}
async function saveSkillVideo(ev,id,revision){ev.preventDefault();await submit(ev,'skill_video',{...Object.fromEntries(new FormData(ev.target)),group_name:data.skill_videos.find(v=>v.id===id)?.group_name||'全員',id,revision},'動画を保存しました。');}
async function deleteSkillVideo(id,revision){if(!await confirmAction('動画を削除しますか？','スキルアップ動画の掲載を削除します。'))return;try{await api('skill_video',{id,revision,delete:true});$('#modal').close();await refresh();toast('動画を削除しました。');}catch(e){toast(e.message);}}

const portalBeforeReceipts=portalContent;portalContent=function(staff,admin){const body=portalBeforeReceipts(staff,admin),kind=({'payments':'fees','checkout':'fees','billing-settings':'fees','shop':'shop','shop-admin':'shop','surveys':'lunch','survey-admin':'lunch','finance-report':'accounting','finance-admin':'accounting','messages':'refund'})[page];return body+(kind?receiptPanel(kind):'')+(page==='billing-settings'?receiptPanel('refund'):'');};

let coachHomeNavigation=[];
function coachCardHome(){return heading('コーチホーム','確認する項目を選んでください。')+homeAnnouncements()+coachHomeSummary()+`<div class="admin-home-links dashboard-shortcuts">${coachHomeNavigation.filter((x,i,all)=>all.findIndex(y=>y[0]===x[0])===i).map(([id,icon,label])=>`<a class="card" href="#${id}"><h2><span class="admin-shortcut-icon" aria-hidden="true">${icon}</span><span>${esc(label)}</span></h2><span class="text-link">開く →</span></a>`).join('')}</div>`;}
