function masterSelectValues(label,name,values,current){const original=values.map(v=>Array.isArray(v)?v:[v,v]);const masters=typeof data==='object'&&data?.choice_masters||[];const spec=masters.find(s=>s.labels.includes(label)||(name.startsWith('permission_')&&s.kind==='permission')||s.kind===({role:'role',attendance:'attendance',actual:'attendance',status:label==='出欠'?'attendance':'',method:'method',enrollment_status:'enrollment',grade:'grade',categories:'category',group_name:'category',title_activity:'activity',notification:'notification'}[name]));if(!spec)return values;if(spec.kind==='extra'){const choices=spec.options.map(o=>{const source=original.find(v=>String(v[0])===o.base||String(v[1])===o.base);return source?[source[0],o.label]:null;}).filter(Boolean);if(!choices.length)return values;const placeholder=original.filter(v=>String(v[0])==='');const old=original.find(v=>String(v[0])===String(current));if(old&&!choices.some(v=>String(v[0])===String(current)))choices.push([old[0],old[1]+'（現在の設定）']);return [...placeholder,...choices];}const allowed=new Set(original.map(v=>String(v[0]))),known=new Set(spec.defaults.map(v=>String(v.value)));const fixed=original.filter(v=>!known.has(String(v[0]))),choices=spec.options.filter(o=>allowed.has(String(o.value))).map(o=>[o.value,o.label]);if(current!==undefined&&!choices.some(v=>String(v[0])===String(current))&&!fixed.some(v=>String(v[0])===String(current))){const old=original.find(v=>String(v[0])===String(current));if(old)fixed.push([old[0],old[1]+'（現在の設定）']);}return [...fixed,...choices];}
function choiceMasterPanel(){return `<details class="card"><summary><b>Excelの選択肢マスター</b></summary><p>「選択肢マスター」の黄色い欄を追加・編集・削除して保存します。備品と会場は名称を追加するだけで選択できます。権限・出欠などは右欄で既存の処理区分を選びます。同じ処理区分の名称は、保存・集計では同じ扱いになります。共通欄にない選択欄は「追加選択肢」に画面の項目名・表示名・元の選択肢を入力します。会員名・日付・商品サイズなどは、元の登録情報から候補が作られます。</p><a class="btn outline" href="member-registration.xlsx" download>会員・マスター登録Excel</a><label class="field">保存したローカルExcel<input type="file" accept=".xlsx" onchange="uploadChoiceMasters(this.files[0])"></label><div class="toolbar"><button class="outline" onclick="watchChoiceMasters()">Excelの継続読込を開始</button><button class="outline" onclick="stopChoiceMasters()">継続読込を停止</button></div><p class="hint">対応PCブラウザでは画面を開いている間、保存後約5秒で反映します。削除した候補でも過去の記録・既存アカウントは残ります。新しい権限処理・決済サービス自体は作成しません。</p><p role="status" id="choice-master-status"></p></details>`;}
let choiceMasterTimer=null,choiceMasterBusy=false,choiceMasterDigest='';
function choiceMasterMessage(text){const node=document.getElementById('choice-master-status');if(node)node.textContent=text;}
async function uploadChoiceMasters(file){if(!file||choiceMasterBusy)return false;choiceMasterBusy=true;try{if(file.size>5*1024*1024)throw Error('Excelは5MB以内にしてください。');const bytes=new Uint8Array(await file.arrayBuffer());const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).join(',');if(digest===choiceMasterDigest)return true;let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));await api('choice_masters',{content:btoa(raw)});choiceMasterDigest=digest;await refresh();choiceMasterMessage('Excelマスターを反映しました：'+new Date().toLocaleTimeString('ja-JP'));toast('選択肢マスターを反映しました。');return true;}catch(e){choiceMasterMessage(e.message);toast(e.message);return false;}finally{choiceMasterBusy=false;}}
function stopChoiceMasters(){clearInterval(choiceMasterTimer);choiceMasterTimer=null;choiceMasterMessage('継続読込を停止しました。');}
async function watchChoiceMasters(){if(!window.showOpenFilePicker){toast('このブラウザでは保存したExcelを再度選択してください。');return;}try{const [handle]=await window.showOpenFilePicker({types:[{description:'Excel',accept:{'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':['.xlsx']}}]});stopChoiceMasters();choiceMasterDigest='';const read=async()=>{if(document.hidden||document.querySelector('dialog[open]')||choiceMasterBusy)return;const ok=await uploadChoiceMasters(await handle.getFile());if(!ok)stopChoiceMasters();};await read();choiceMasterTimer=setInterval(()=>read().catch(()=>{stopChoiceMasters();choiceMasterMessage('ファイルを再選択してください。');}),5000);}catch(e){if(e.name!=='AbortError')toast(e.message);}}
// Include hand-written selects as well as the shared form component.
const choiceMasterOriginals=new WeakMap();
function applyChoiceMasterSelects(){if(typeof data!=='object'||!data?.choice_masters)return;const stamp=JSON.stringify(data.choice_masters);for(const select of document.querySelectorAll('#app select,#modal select')){if(select.dataset.choiceMasterStamp===stamp)continue;let label='';const parent=select.closest('label');if(parent)label=[...parent.childNodes].filter(n=>n.nodeType===3).map(n=>n.textContent).join('').trim();if(!label)label=select.getAttribute('aria-label')||select.name||'';const original=choiceMasterOriginals.get(select)||[...select.options].map(o=>[o.value,o.textContent]);choiceMasterOriginals.set(select,original);const values=masterSelectValues(label,select.name||'',original,select.value),current=select.value;select.dataset.choiceMasterStamp=stamp;if(JSON.stringify(values)!==JSON.stringify(original)){select.innerHTML=values.map(v=>`<option value="${esc(v[0])}">${esc(v[1])}</option>`).join('');select.value=current;}}}
new MutationObserver(applyChoiceMasterSelects).observe(document.documentElement,{childList:true,subtree:true});
setInterval(async()=>{if(typeof user==='undefined'||!user||document.hidden||document.querySelector('dialog[open]'))return;try{const result=await api('choice_masters');if(JSON.stringify(result.choice_masters)!==JSON.stringify(data.choice_masters)){data.choice_masters=result.choice_masters;data.equipment_master=result.equipment_master;data.venues=result.venues;applyChoiceMasterSelects();}}catch{}},15000);
