// Shared picker retains native date values and form validation.
(function(){let active=null;
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function open(input){if(active||input.disabled||input.readOnly)return;let shown=new Date((input.value||iso(new Date()))+'T12:00:00');if(isNaN(shown))shown=new Date();const dialog=document.createElement('dialog');dialog.className='club-date-picker';dialog.setAttribute('aria-label','日付を選択');active=dialog;document.body.append(dialog);const valid=value=>(!input.min||value>=input.min)&&(!input.max||value<=input.max);const choose=value=>{if(!valid(value))return;input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));dialog.close();};function paint(){const y=shown.getFullYear(),m=shown.getMonth(),start=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate();dialog.innerHTML='<div class="date-picker-month"><button type="button" data-shift="-1" aria-label="前月">‹</button><label>年<input class="date-picker-year" type="number" min="1900" max="2099" value="'+y+'"></label><label>月<select class="date-picker-month-select">'+Array.from({length:12},(_,i)=>'<option value="'+i+'" '+(i===m?'selected':'')+'>'+(i+1)+'</option>').join('')+'</select></label><button type="button" data-shift="1" aria-label="翌月">›</button></div><div class="date-picker-grid">'+['月','火','水','木','金','土','日'].map((x,i)=>'<b class="'+(i===6?'calendar-red':i===5?'calendar-blue':'')+'">'+x+'</b>').join('')+'<span></span>'.repeat(start)+Array.from({length:days},(_,i)=>{const v=iso(new Date(y,m,i+1)),cls=typeof scheduleDayColor==='function'?scheduleDayColor(v):'';return '<button type="button" class="'+cls+(input.value===v?' selected':'')+'" data-date="'+v+'" '+(!valid(v)?'disabled':'')+'>'+(i+1)+'</button>';}).join('')+'</div><div class="date-picker-shortcuts">'+[-1,0,1].map((offset,i)=>{const d=new Date();d.setDate(d.getDate()+offset);return '<button type="button" data-date="'+iso(d)+'" '+(!valid(iso(d))?'disabled':'')+'>'+['前日','今日','明日'][i]+'</button>';}).join('')+'</div><button type="button" class="outline date-picker-close">閉じる</button>';dialog.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>choose(b.dataset.date));dialog.querySelectorAll('[data-shift]').forEach(b=>b.onclick=()=>{shown=new Date(y,m+Number(b.dataset.shift),1);paint();});dialog.querySelector('.date-picker-month-select').onchange=e=>{shown=new Date(y,Number(e.target.value),1);paint();};dialog.querySelector('.date-picker-year').onchange=e=>{const n=Number(e.target.value);if(n>=1900&&n<=2099){shown=new Date(n,m,1);paint();}};dialog.querySelector('.date-picker-close').onclick=()=>dialog.close();}dialog.addEventListener('close',()=>{active=null;dialog.remove();if(input.isConnected)input.focus();},{once:true});paint();dialog.showModal();}
for(const kind of ['pointerdown','click'])document.addEventListener(kind,e=>{if(e.target.matches('input[type=date]')&&!e.target.disabled&&!e.target.readOnly){e.preventDefault();open(e.target);}},true);
document.addEventListener('keydown',e=>{if(e.target.matches('input[type=date]')&&['Enter',' ','ArrowDown'].includes(e.key)){e.preventDefault();open(e.target);}},true);
function syncDisplay(event){const input=event.target;if(!input.matches('input[type=date]'))return;const display=input.closest('.club-date-display')?.querySelector('.club-date-text');if(display)display.textContent=input.value?input.value.replaceAll('-','/'):'年 / 月 / 日';}
document.addEventListener('input',syncDisplay,true);
document.addEventListener('change',syncDisplay,true);
})();
