function activityBrief(id, draft=false){
 const item=(data.event_briefings||[]).find(b=>b.event_id===id);
 return user.role==='member'?item:(draft?item?.draft:item?.published);
}
function activityAttachmentUrl(f,download=false){return '/basketball-club/api/event_attachment?id='+encodeURIComponent(f.id)+'&member='+encodeURIComponent(user.id)+(download?'&download=1':'');}
function activityMap(url){
 if(!url)return '';
 return `<p><a class="btn outline" href="${esc(url)}" target="_blank" rel="noopener noreferrer">会場の地図を開く</a></p>`;
}
async function openActivityDetails(id){
 const e=data.events.find(x=>x.id===id);if(!e)return;
 const b=activityBrief(id),roster=(data.scheduling?.rosters||[]).find(r=>r.event_id===id&&r.published);
 const chosen=b?.mode==='selected',names=b?.names||roster?.names||[];
 const members=b?(chosen?names.map(n=>esc(n.name)).join(' ／ ')||'選出メンバーなし':'この活動区分の全員が対象です。'):roster?names.map(n=>esc(n.name)).join(' ／ '):'コーチからのメンバー案内は準備中です。';
 modal('日程の詳細',`<div class="activity-detail"><h3>${esc(e.title)}</h3><p>${dateLabel(e.date)}　${esc(e.time)}<br>会場：${esc(e.place)}${b?.address||e.address?'<br>住所：'+esc(b?.address||e.address):''}</p>${e.kind==='体験会'?'':'<h3>参加メンバー</h3><p>'+members+'</p>'}${chosen&&user.role==='member'?`<p class="tag">${b.member_ids.includes(user.id)?'あなたは参加メンバーです':'今回は参加メンバーに含まれていません'}</p>`:''}${eventEquipmentDisplay(id)}<h3>注意事項・集合案内</h3><p class="service-text">${esc(b?.note||e.note||'追加の注意事項はありません。')}</p>${activityMap(b?.map_url||e.map_url)}${(b?.files||[]).length?'<h3>写真・資料</h3>':''}${(b?.files||[]).map(f=>`<div class="activity-attachment">${f.mime.startsWith('image/')?`<a href="${activityAttachmentUrl(f)}" target="_blank" rel="noopener"><img src="${activityAttachmentUrl(f)}" alt="${esc(f.name)}" loading="lazy"></a>`:''}<a class="text-link" href="${activityAttachmentUrl(f)}" target="_blank" rel="noopener">${esc(f.name)}を開く${f.mime==='application/pdf'?'（PDF）':''}</a> <a class="text-link" href="${activityAttachmentUrl(f,true)}">ダウンロード</a></div>`).join('')}${b?`<p class="hint">更新：${esc(b.updated)}</p>`:''}</div>`);
 // Details must actually be opened before the activity is considered read.
 const item=newItems('schedule').find(x=>x.id===id),owner=user.id;
 if(item&&isNewItem('schedule',item)){
  const key=newItemKey('schedule',item);
  try{await api('new_seen',{keys:[key]});if(user.id!==owner)return;data.new_seen=[...new Set([...(data.new_seen||[]),key])];
   document.querySelectorAll('[data-new-section="schedule"]').forEach(el=>{if(el.dataset.newId===id)el.remove();});
   document.querySelectorAll('[data-new-nav]').forEach(el=>el.innerHTML=navNew(el.dataset.newNav));
   document.querySelectorAll('.mobile-route option').forEach(el=>{el.textContent=el.textContent.replace(/ NEW$/,'')+(newCount(el.value)?' NEW':'');});
  }catch{toast('既読状態を保存できませんでした。もう一度詳細を開いてください。');}
 }
}
function activityDetailsForm(id){
 const e=data.events.find(x=>x.id===id),b=activityBrief(id,true),r=(data.scheduling?.rosters||[]).find(x=>x.event_id===id);
 const trial=e.kind==='体験会',schedule={...e,...b?.schedule};
 const selected=b?.member_ids||r?.member_ids||[],mode=b?.mode||(r?'selected':'all');
 const people=data.users.filter(u=>u.role==='member'&&u.active);
 modal('詳細を編集・公開',`<p>${esc(e.date)} ${esc(e.title)}</p>${logisticsManager()?`<div class="logistics-actions"><button type="button" class="outline" onclick="openLogisticsSetup('${id}','ride')">配車依頼を設定</button><button type="button" class="outline" onclick="openLogisticsSetup('${id}','film')">撮影依頼を設定</button></div>`:''}${e.kind==='練習'&&adminCan('schedule',true)?`<p><button type="button" class="lime" onclick="openWeeklyRepeat('${id}')">毎週繰り返し登録</button></p>`:''}<form onsubmit="saveActivityDetails(event,'${id}')"><fieldset class="combined-schedule-fields" ${adminCan('schedule',true)?'':'disabled'}>${scheduleTitleField(schedule.title,schedule.kind)}<div class="form-grid">${field('日付','date',schedule.date,'date')}${field('時間','time',schedule.time)}${eventCategoryField(schedule.group_name)}</div>${venueFields(schedule.place,b?.address??e.address??'')}</fieldset>${selectField('参加対象','mode',[['all','活動区分の全員'],['selected','指定したメンバーのみ']],mode)}<fieldset class="activity-member-choices" ${mode==='all'?'hidden':''}><legend>出欠回答を確認して選出</legend>${people.map(u=>{const report=data.reports.find(x=>x.event_id===id&&x.user_id===u.id),meta=data.scheduling.attendance.find(x=>x.event_id===id&&x.user_id===u.id);return `<label class="check-row"><input type="checkbox" name="members" value="${esc(u.id)}" ${selected.includes(u.id)?'checked':''}><span>${esc(u.name)}：${esc(report?.attendance||'未回答')}${meta?.note?`<small class="service-text">${esc(meta.note)}</small>`:''}</span></label>`}).join('')}</fieldset>${eventEquipmentEditor(b)}<label class="field">注意事項・集合案内<textarea name="note" maxlength="10000">${esc(b?.note??e.note??'')}</textarea></label>${field('地図URL（Googleマップなど）','map_url',b?.map_url??e.map_url??'','url',false)}<fieldset><legend>添付済みの写真・PDF（残すものにチェック）</legend>${(b?.files||[]).map(f=>`<label class="check-row"><input type="checkbox" name="keep_files" value="${esc(f.id)}" checked>${esc(f.name)}</label>`).join('')||'<p class="hint">添付はありません。</p>'}</fieldset><label class="field">写真・PDFを追加<input type="file" name="files" accept="application/pdf,image/jpeg,image/png,image/webp" multiple></label><p class="hint">1件5MB以下、合計30件まで。下書き保存は会員に通知されません。「公開してNEWを付ける」で内容を反映します。</p><div class="error" role="alert"></div><div class="dialog-actions activity-publish-actions">${adminCan('schedule',true)?`<button type="button" class="outline danger" onclick="deleteRecord('event','${id}')">日程を削除</button>`:''}<button type="submit" class="outline" name="action" value="draft">下書き保存</button><button type="submit" class="lime" name="action" value="publish">公開してNEWを付ける</button></div></form>`);
 if(e.kind==='体験会'){const select=document.querySelector('#modal select[name="mode"]');select.value='all';select.closest('label').hidden=true;document.querySelector('#modal .activity-member-choices').hidden=true;}
 const form=document.querySelector('#modal form');form.addEventListener('input',()=>form.dataset.changed='true');form.addEventListener('change',()=>filterActivityMemberChoices(form));filterActivityMemberChoices(form);
}
async function saveActivityDetails(ev,id){
 ev.preventDefault();const form=ev.target,button=ev.submitter,f=new FormData(form),publish=button.value==='publish';
 const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);
 try{
  const files=[...form.elements.files.files],keep=f.getAll('keep_files');
  if(files.length+keep.length>30)throw Error('添付は合計30件までです。');
  const uploads=[];
  for(const file of files){if(file.size>5*1024*1024)throw Error('添付は1件5MB以下にしてください。');uploads.push({name:file.name,content:await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=()=>reject(Error('ファイルを読み込めません。'));r.readAsDataURL(file);})});}
  const trial=data.events.find(e=>e.id===id)?.kind==='体験会';
  await api('event_briefing',{event_id:id,...(adminCan('schedule',true)?{schedule:{title:f.get('title'),date:f.get('date'),time:f.get('time'),place:f.get('place'),kind:f.get('kind'),group_name:f.get('group_name')}}:{}),equipment_items:[...form.querySelectorAll('.event-equipment-row')].map(row=>({name:row.querySelector('[data-equipment-name]').value,required:row.querySelector('[data-equipment-required]').checked})),mode:f.get('mode'),member_ids:f.getAll('members'),note:f.get('note'),address:f.get('address'),map_url:f.get('map_url'),keep_files:keep,uploads,publish});
  $('#modal').close();await refresh();toast(publish?'日程の詳細を公開し、NEWを付けました。':'下書きを保存しました。');
 }catch(e){form.querySelector('.error').textContent=e.message;}finally{buttons.forEach(b=>b.disabled=false);}
}

function filterActivityMemberChoices(form){const groups=(form.elements.group_name?.value||'').split(/[、,]/),trial=form.elements.kind?.value==='体験会',mode=form.elements.mode;mode.closest('label').hidden=trial;if(trial)mode.value='all';form.querySelector('.activity-member-choices').hidden=trial||mode.value==='all';form.querySelectorAll('input[name="members"]').forEach(input=>{const person=data.users.find(u=>u.id===input.value),eligible=(person?.categories||'U12').split(/[、,]/).some(c=>groups.includes(c.trim()));input.disabled=!eligible||!adminCan(adminSection(page),true);if(!eligible)input.checked=false;input.closest('label').hidden=!eligible;});}

function openLogisticsSetup(id,kind){const form=document.querySelector('#modal form');if(form?.dataset.changed==='true'&&!confirm('日程の変更が未保存です。変更を破棄して依頼設定を開きますか？'))return;openLogistics(id,kind,'settings');}

function venueMapUrl(address){return address?'https://www.google.com/maps?q='+encodeURIComponent(address.trim()):'';}
function scheduleChoiceOptions(kind,current){const stored=kind==='title'?data.schedule_titles||[]:data.venues||[];const values=[...new Set([...stored.map(r=>r.name),...(current?[current]:[])])];return '<option value="">選択してください</option>'+values.map(v=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(v)}</option>`).join('');}
function scheduleTitleField(title='',kind='練習',video=false){
 const clean=title.replace(/[\s　]+/g,'').replace(/(?:vs|VS|ＶＳ).*$/,'');
 const teams=['男子Aチーム','男子Bチーム','女子U９','女子U12','U15アドバンス','U15ベーシック',video?'全員':'体験'];
 const aliases={'男子Aチーム':'男子A','男子Bチーム':'男子B','U15アドバンス':'U15アドバンス','U15ベーシック':'U15ベーシック'};
 const selected=teams.filter(t=>clean.includes(t)||(aliases[t]&&clean.includes(aliases[t])));
 if(!selected.length&&!video&&kind==='体験会')selected.push('体験');
 const team=selected.join('・'),trial=team==='体験';
 const activity=trial?'':clean.includes('練習試合')?'練習試合':clean.includes('試合')||kind==='試合'?'試合':'練習';
 const composed=trial?'体験会':team?team+activity:'';
 return `<div class="schedule-title-composer"><fieldset><legend>チーム・クラス（複数選択可）</legend><div class="schedule-team-choices">${teams.map(t=>`<label class="check-row"><input type="checkbox" name="title_team" value="${esc(t)}" ${selected.includes(t)?'checked':''} onchange="composeScheduleTitle(this)">${esc(t)}</label>`).join('')}</div></fieldset><label class="field">活動内容<select name="title_activity" ${team==='体験'?'':'required'} onchange="composeScheduleTitle(this)"><option value="">選択してください</option>${['練習','練習試合','試合'].map(t=>`<option ${t===activity?'selected':''}>${t}</option>`).join('')}</select>${video?'':'<small>体験のみの場合は空欄で構いません。</small>'}</label><input type="hidden" name="title" value="${esc(composed)}"><input type="hidden" name="kind" value="${team==='体験'?'体験会':activity==='練習'?'練習':'試合'}"><p class="hint">表示タイトル：<strong data-title-preview>${esc(composed||'チーム・クラスを選択してください')}</strong></p></div>`;
}
function composeScheduleTitle(select){const box=select.closest('.schedule-title-composer'),team=[...box.querySelectorAll('[name=title_team]:checked')].map(x=>x.value).join('・'),activity=box.querySelector('[name=title_activity]');activity.required=team!=='体験';if(team==='体験')activity.value='';const title=team==='体験'?'体験会':team?team+(activity.value||''):'';box.querySelector('[name=title]').value=title;box.querySelector('[name=kind]').value=team==='体験'?'体験会':activity.value==='練習'?'練習':'試合';box.querySelector('[data-title-preview]').textContent=title||'チーム・クラスを選択してください';if(select.form?.querySelector('.activity-member-choices'))filterActivityMemberChoices(select.form);}

function venueFields(place,address){return `<div class="venue-fields"><label class="field">会場<select name="place" required onchange="selectScheduleVenue(this)">${scheduleChoiceOptions('venue',place)}</select></label>${adminFull()?'<button type="button" class="outline small" onclick="openScheduleChoices(\'venue\')">会場を管理</button>':''}<label class="field">住所<input name="address" value="${esc(address)}" maxlength="500" oninput="updateVenueMap(this)"><small>住所からGoogleマップを自動設定します。</small></label></div>`;}
function venueFormScope(el){return el.closest('fieldset.card')||el.closest('form');}
function selectScheduleVenue(select){const row=(data.venues||[]).find(v=>v.name===select.value),input=select.closest('.venue-fields').querySelector('[name=address]');input.value=row?.address||'';updateVenueMap(input);}
function updateVenueMap(input){const map=venueFormScope(input)?.querySelector('[name=map_url]');if(map)map.value=venueMapUrl(input.value);}
let scheduleChoiceKind='venue';
function openScheduleChoices(kind){scheduleChoiceKind=kind;document.getElementById('schedule-choice-dialog')?.remove();const dialog=document.createElement('dialog');dialog.id='schedule-choice-dialog';dialog.className='schedule-choice-dialog';document.body.append(dialog);renderScheduleChoices();dialog.showModal();}
function renderScheduleChoices(editId=''){const kind=scheduleChoiceKind,rows=kind==='title'?data.schedule_titles||[]:data.venues||[],r=rows.find(r=>r.id===editId)||{},label=kind==='title'?'タイトル':'会場';const dialog=document.getElementById('schedule-choice-dialog');dialog.innerHTML=`<div class="dialog-head"><h2>${label}を管理</h2><button type="button" class="outline" onclick="document.getElementById('schedule-choice-dialog').close()">閉じる</button></div><p class="hint">候補を編集・削除しても、保存済みの日程の内容は変わりません。</p><form onsubmit="saveScheduleChoice(event)"><input type="hidden" name="id" value="${esc(r.id||'')}"><input type="hidden" name="revision" value="${esc(r.revision||'')}">${field(label+'名','name',r.name||'')}${kind==='venue'?field('住所','address',r.address||''):''}<div class="error" role="alert"></div><div class="toolbar"><button class="lime">${r.id?'変更を保存':'追加する'}</button>${r.id?'<button type="button" class="outline" onclick="renderScheduleChoices()">新しく追加</button>':''}</div></form><div class="schedule-choice-list">${rows.map(row=>`<article><b>${esc(row.name)}</b>${row.address?`<p>${esc(row.address)}</p>`:''}<div class="toolbar"><button type="button" class="outline" onclick="renderScheduleChoices('${row.id}')">編集</button><button type="button" class="outline danger" onclick="deleteScheduleChoice('${row.id}','${row.revision}',this)">削除</button></div></article>`).join('')||'<p>候補はまだ登録されていません。</p>'}</div><div class="modal-bottom-actions"><button type="button" class="outline" onclick="this.closest('dialog').close()">閉じる</button></div>`;}
async function refreshScheduleChoices(){const result=await api('venues');data.venues=result.venues;data.schedule_titles=result.schedule_titles;document.querySelectorAll('#modal select[name=place],#modal select[name=title]').forEach(select=>{const current=select.value;select.innerHTML=scheduleChoiceOptions(select.name==='title'?'title':'venue',current);});}
async function saveScheduleChoice(ev){ev.preventDefault();const button=ev.submitter;button.disabled=true;try{await api('venues',{kind:scheduleChoiceKind,...Object.fromEntries(new FormData(ev.target))});await refreshScheduleChoices();renderScheduleChoices();toast('候補を保存しました。');}catch(e){ev.target.querySelector('.error').textContent=e.message;button.disabled=false;}}
async function deleteScheduleChoice(id,revision,button){if(!confirm('この候補を削除しますか？ 保存済みの日程は残ります。'))return;button.disabled=true;try{await api('venues',{kind:scheduleChoiceKind,id,revision,delete:true});await refreshScheduleChoices();renderScheduleChoices();}catch(e){toast(e.message);button.disabled=false;}}

function openWeeklyRepeat(id){const e=data.events.find(e=>e.id===id);if(!e||e.kind!=='練習')return;const form=document.querySelector('#modal form');if(form?.dataset.changed==='true'){toast('編集した内容を先に保存してから、繰り返し登録してください。');return;}const end=new Date(e.date+'T12:00:00');end.setDate(end.getDate()+84);const d=document.createElement('dialog');d.className='schedule-choice-dialog';d.innerHTML=`<h2>毎週繰り返し登録</h2><p>${esc(e.title)}<br>${esc(e.date)}をもとに、翌週から7日ごとに登録します。</p><form><label class="field">繰り返し終了日<input type="date" name="end" min="${esc(e.date)}" value="${end.toLocaleDateString('sv-SE')}" required></label><p class="hint">最大50回。作成後は日程ごとに修正・削除できます。添付資料・配車・撮影設定は複製しません。</p><div class="error" role="alert"></div><div class="registration-actions"><button type="button" class="outline" data-close>閉じる</button><button class="lime">毎週の日程を登録する</button></div></form>`;d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove(),{once:true});d.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const button=ev.submitter;button.disabled=true;try{const end=d.querySelector('[name=end]').value,rows=[],date=new Date(e.date+'T12:00:00');date.setDate(date.getDate()+7);while(date.toLocaleDateString('sv-SE')<=end){if(rows.length>=50)throw Error('繰り返しは50回以内になる終了日を選択してください。');rows.push({...e,date:date.toLocaleDateString('sv-SE')});date.setDate(date.getDate()+7);}if(!rows.length)throw Error('翌週以降の終了日を選択してください。');await api('events_bulk',{events:rows});d.close();$('#modal').close();await refresh();toast(rows.length+'件の日程を登録しました。');}catch(error){d.querySelector('.error').textContent=error.message;button.disabled=false;}};document.body.append(d);d.showModal();}

document.addEventListener('input',event=>{const form=event.target.closest('form');if(form?.getAttribute('onsubmit')?.startsWith('saveEvent('))form.dataset.changed='true';});

function eventEquipmentRow(item={name:'',required:true}){const choices=[...new Set([...(data.equipment_master||[]).map(x=>x.name),...(item.name?[item.name]:[])])];return `<div class="event-equipment-row"><label class="check-row"><input type="checkbox" data-equipment-required ${item.required?'checked':''}>必要</label><select data-equipment-name aria-label="備品名" required><option value="">選択してください</option>${choices.map(name=>`<option value="${esc(name)}" ${name===item.name?'selected':''}>${esc(name)}</option>`).join('')}</select><button type="button" class="outline" onclick="this.closest('.event-equipment-row').remove()">削除</button></div>`;}
function collectEventEquipment(form){return [...form.querySelectorAll('.event-equipment-row')].map(row=>({name:row.querySelector('[data-equipment-name]').value,required:row.querySelector('[data-equipment-required]').checked}));}
function eventEquipmentEditor(b){const items=b?.equipment_items||[];return `<fieldset><legend>必要なチーム備品</legend><p class="hint">備品を選択して「必要」にチェックすると会員に表示されます。</p><div id="event-equipment-items">${items.map(eventEquipmentRow).join('')}</div><button type="button" class="outline" onclick="document.getElementById('event-equipment-items').insertAdjacentHTML('beforeend',eventEquipmentRow())">備品を追加</button>${adminFull()?`<details><summary>Excelの備品マスターを読み込む</summary><a class="text-link" href="member-registration.xlsx" download>会員・マスター登録Excel</a><label class="field">ローカルExcel<input type="file" accept=".xlsx" onchange="uploadEquipmentMaster(this)"></label><button type="button" class="outline" onclick="watchEquipmentMaster()">Excelの継続読込を開始</button><button type="button" class="outline" onclick="clearInterval(equipmentWatchTimer);equipmentWatchTimer=null;toast('継続読込を停止しました。')">停止</button><p class="hint">「備品マスター」に項目を追加し、保存したExcelを読み込んでください。行を削除すると候補から外れます。過去の日程は変更しません。</p></details>`:''}</fieldset>`;}
async function uploadEquipmentMaster(input){const file=input.files[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error('Excelは5MB以内にしてください。');const bytes=new Uint8Array(await file.arrayBuffer());let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));const result=await api('equipment_master',{content:btoa(raw)});data.equipment_master=result.equipment_master;document.querySelectorAll('.event-equipment-row').forEach(row=>{const item={name:row.querySelector('[data-equipment-name]').value,required:row.querySelector('[data-equipment-required]').checked};row.outerHTML=eventEquipmentRow(item);});toast('備品マスターを反映しました。');}catch(e){toast(e.message);}}
function eventEquipmentDisplay(id){const b=activityBrief(id),items=(b?.equipment_items||[]).filter(x=>x.required);return items.length?`<section class="event-equipment-display"><h3>必要なチーム備品</h3><ul>${items.map(x=>`<li>${esc(x.name)}</li>`).join('')}</ul></section>`:'';}

let equipmentWatchTimer=null,equipmentWatchHash='';
async function watchEquipmentMaster(){if(!window.showOpenFilePicker){toast('このブラウザは継続読込に未対応です。Excelを再度選択してください。');return;}try{const [handle]=await window.showOpenFilePicker({types:[{description:'Excel',accept:{'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':['.xlsx']}}]});clearInterval(equipmentWatchTimer);equipmentWatchHash='';const read=async()=>{if(document.visibilityState!=='visible')return;const file=await handle.getFile(),hash=file.lastModified+':'+file.size;if(hash===equipmentWatchHash)return;await uploadEquipmentMaster({files:[file]});equipmentWatchHash=hash;};await read();equipmentWatchTimer=setInterval(()=>read().catch(()=>{clearInterval(equipmentWatchTimer);toast('Excelを再選択してください。');}),5000);toast('画面を開いている間、Excelの保存を約5秒ごとに確認します。');}catch(e){if(e.name!=='AbortError')toast(e.message);}}
