let lunchPdfLibrary;
function saveDownload(bytes,type,name){const url=URL.createObjectURL(new Blob([bytes],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();if(type==='application/pdf'){modal('PDFを作成しました',`<p>下のボタンからPDFを開いて確認・保存・印刷できます。</p><a class="btn lime" href="${url}" target="_blank" rel="noopener">作成したPDFを開く</a> <a class="btn outline" href="${url}" download="${esc(name)}">PDFを保存</a>`);document.querySelector('#modal').addEventListener('close',()=>setTimeout(()=>URL.revokeObjectURL(url),60000),{once:true});}else setTimeout(()=>URL.revokeObjectURL(url),30000);}
function lunchFamilies(id){const groups=new Map();for(const a of (data.surveys?.answers||[]).filter(a=>a.item_id===id).sort((a,b)=>String(b.updated||'').localeCompare(String(a.updated||'')))){const member=(data.users||[]).find(u=>u.id===a.user_id),key=member?.family_id?'family:'+member.family_id:'member:'+a.user_id;if(!groups.has(key))groups.set(key,{key,answers:[],total:0,quantity:0});const g=groups.get(key);g.answers.push(a);g.total+=Number(a.total)||0;g.quantity+=(a.meals||[]).length;}return [...groups.values()].map(g=>({...g,label:g.answers.map(a=>a.name).join('・')+' の家庭'}));}
const lunchMoney=value=>Number(value||0).toLocaleString('ja-JP');
function lunchExportRows(id){return lunchFamilies(id).flatMap(g=>{let first=true;return g.answers.flatMap(a=>(a.meals.length?a.meals:[null]).map((m,i)=>{const familyFirst=first;first=false;return [g.label,a.name,a.order,m?.group||'',m?.name||'',m?lunchMoney(m.price):'',i===0?lunchMoney(a.total):'',familyFirst?lunchMoney(g.total):'',familyFirst?g.quantity:'',familyFirst&&g.quantity?'□':'',familyFirst&&g.quantity?'□':'','',a.updated];}));});}
async function downloadLunch(id,format){if(!['coach','admin'].includes(user.role))return;const f=data.surveys.forms.find(f=>f.item_id===id)||data.portal.items.find(f=>f.id===id&&f.kind==='surveys');if(!f)return;const isLunch=f.kind==='lunch',headers=isLunch?['家庭','回答者','注文','区分','お弁当','単価（円）','回答者合計（円・先頭行のみ）','家庭合計（円・先頭行のみ）','家庭注文数（先頭行のみ）','集金済み','受け渡し済み','確認者','回答日時']:['回答者','回答内容','回答日時'],rows=isLunch?lunchExportRows(id):surveyTextAnswers(id).map(a=>[a.name,a.answer,a.created]),filename=f.title.replace(/[\\/:*?"<>|]/g,'_');try{if(format==='csv'){const cell=x=>'"'+String(x??'').replace(/^[\s]*[=+@-]/,m=>"'"+m).replace(/"/g,'""')+'"';saveDownload('\ufeff'+[headers,...rows].map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8',filename+'.csv');return;}
 if(!window.PDFLib){if(!lunchPdfLibrary)lunchPdfLibrary=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='/basketball-club/vendor/pdf-lib.min.js';s.onload=resolve;s.onerror=()=>{lunchPdfLibrary=null;reject(Error('PDF生成を読み込めません。'));};document.head.append(s);});await lunchPdfLibrary;}
 await document.fonts.ready;const pdf=await PDFLib.PDFDocument.create();let canvas,ctx,y,page=0;
 const begin=()=>{canvas=document.createElement('canvas');canvas.width=1240;canvas.height=1754;ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,1240,1754);ctx.fillStyle='#17263d';ctx.font='bold 30px sans-serif';ctx.fillText(isLunch?'お弁当アンケート 回答一覧':'保護者アンケート 回答一覧',65,70);ctx.font='22px sans-serif';y=110;page++;};
 const flush=async()=>{ctx.font='18px sans-serif';ctx.fillText(String(page),600,1710);const image=await pdf.embedPng(canvas.toDataURL('image/png'));pdf.addPage([595.28,841.89]).drawImage(image,{x:0,y:0,width:595.28,height:841.89});};
 const line=async(text,bold=false)=>{ctx.font=(bold?'bold ':'')+'22px sans-serif';let chunk='';for(const char of String(text)){if(ctx.measureText(chunk+char).width>1100){if(y>1620){await flush();begin();}ctx.fillText(chunk,65,y);y+=34;chunk='';}chunk+=char;}if(y>1620){await flush();begin();}ctx.font=(bold?'bold ':'')+'22px sans-serif';ctx.fillText(chunk,65,y);y+=34;};
 begin();await line(f.title,true);const answers=isLunch?(data.surveys.answers||[]).filter(a=>a.item_id===id).sort((a,b)=>String(b.updated||'').localeCompare(String(a.updated||''))):surveyTextAnswers(id);await line(isLunch?`回答 ${answers.length}名 ／ 合計 ${answers.reduce((s,a)=>s+a.meals.length,0)}個・${answers.reduce((s,a)=>s+a.total,0).toLocaleString()}円`:`回答 ${answers.length}名`);y+=20;
 if(isLunch){await line('メニュー別の注文合計',true);for(const r of lunchMenuTotals(id))await line(`${r.name} ／ 単価 ${r.price.toLocaleString()}円 × ${r.quantity}個 ＝ ${r.total.toLocaleString()}円`);y+=20;}
 if(isLunch){await line('家庭ごとの注文・確認欄',true);for(const g of lunchFamilies(id)){if(y>1400){await flush();begin();}await line(g.label,true);await line(`家庭合計：${lunchMoney(g.total)}円 ／ ${g.quantity}個`,true);for(const a of g.answers){await line(`${a.name} ／ 注文：${a.order} ／ ${lunchMoney(a.total)}円`);for(const m of a.meals)await line(`・${m.group}：${m.name}　${lunchMoney(m.price)}円`);}if(g.quantity){if(y>1480){await flush();begin();await line(g.label+' ／ 家庭合計 '+lunchMoney(g.total)+'円',true);}await line('集金：□ 未集金　□ 集金済み');await line('受け渡し：□ 未受け渡し　□ 受け渡し済み');await line('確認者：________________　確認日：________________');}y+=24;}}
 else{for(const a of answers){await line(a.name,true);for(const paragraph of a.answer.split(/\r?\n/))await line(paragraph);await line('回答日時：'+a.created);y+=22;}}
 if(!answers.length)await line('まだ回答はありません。');await flush();saveDownload(await pdf.save(),'application/pdf',filename+'.pdf');
 }catch(e){toast(e.message||'ダウンロードに失敗しました。');}}
