// Rosters stay in memory or in a file explicitly saved on this device. No API writes.
let rosterDraft={title:'',date:'',rows:[]};
function rosterPage(){if(!user||!['coach','admin'].includes(user.role)||user.role==='admin'&&!adminCan('schedule'))return '<p>閲覧権限がありません。</p>';return heading('メンバー表','日程から大会名・日付を入力し、選手と番号を編集してA4で印刷できます。')+`<section class="card roster-editor"><p class="hint">入力内容はサーバーやGoogleドライブへ送信しません。「端末に保存」で編集用ファイルを保存し、次の試合でも読み込んで使えます。画面を閉じる前に保存してください。</p><label class="field">日程から選択<select onchange="rosterChooseEvent(this.value)"><option value="">日程を選択してください</option>${(data.events||[]).map(e=>`<option value="${esc(e.id)}">${esc(e.date+' '+e.title)}</option>`).join('')}</select></label>${field('大会名','roster_title',rosterDraft.title)}${field('開催日','roster_date',rosterDraft.date,'date')}<div class="toolbar"><label class="field">選手を追加<select onchange="rosterAddMember(this.value);this.value='' "><option value="">選手を選択してください</option>${(data.users||[]).filter(m=>m.role==='member'&&m.active).map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('')}</select></label><button type="button" class="outline" onclick="rosterAddMember('')">手入力の行を追加</button></div><div id="roster-rows">${rosterRowsHtml()}</div><div class="dialog-actions"><button type="button" class="lime" onclick="printRoster()">A4で印刷・PDF保存</button><button type="button" class="outline" onclick="saveRosterFile()">端末に保存</button><label class="btn outline">保存した表を開く<input type="file" accept=".json,application/json" onchange="loadRosterFile(this)" hidden></label></div></section>`;}
function rosterRowsHtml(){return rosterDraft.rows.map((r,i)=>`<div class="roster-entry" data-roster-row="${i}"><label class="field">選手名<input name="player" value="${esc(r.name)}" maxlength="80"></label><label class="field">ビブス<input name="bib" value="${esc(r.bib)}" maxlength="12"></label><label class="field">背番号<input name="number" value="${esc(r.number)}" maxlength="12"></label><button class="outline" type="button" onclick="rosterRemove(${i})">削除</button></div>`).join('')||'<p class="hint">選手を追加してください。</p>';}
function rosterCapture(){const root=document.querySelector('.roster-editor');if(!root)return;rosterDraft.title=root.querySelector('[name=roster_title]').value.trim();rosterDraft.date=root.querySelector('[name=roster_date]').value;rosterDraft.rows=[...root.querySelectorAll('[data-roster-row]')].map(r=>({name:r.querySelector('[name=player]').value.trim(),bib:r.querySelector('[name=bib]').value.trim(),number:r.querySelector('[name=number]').value.trim()}));}
function rosterChooseEvent(id){rosterCapture();const e=data.events.find(e=>e.id===id);if(!e)return;rosterDraft.title=e.title;rosterDraft.date=e.date;dashboard();}
function rosterAddMember(id){rosterCapture();if(rosterDraft.rows.length>=60){toast('1つの表は60名までです。');return;}const m=data.users.find(m=>m.id===id);rosterDraft.rows.push({name:m?.name||'',bib:'',number:''});document.querySelector('#roster-rows').innerHTML=rosterRowsHtml();}
function rosterRemove(i){rosterCapture();rosterDraft.rows.splice(i,1);document.querySelector('#roster-rows').innerHTML=rosterRowsHtml();}
function saveRosterFile(){rosterCapture();const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({format:'club-member-roster-v1',...rosterDraft},null,2)],{type:'application/json'}));a.href=url;a.download='メンバー表_'+(rosterDraft.date||'未定')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function loadRosterFile(input){const f=input.files[0];if(!f)return;try{if(f.size>1024*1024)throw Error('ファイルが大きすぎます。');const d=JSON.parse(await f.text());if(d.format!=='club-member-roster-v1'||!Array.isArray(d.rows)||d.rows.length>60||typeof d.title!=='string'||d.title.length>200||typeof d.date!=='string'||d.date&&!/^\d{4}-\d{2}-\d{2}$/.test(d.date)||d.rows.some(r=>!r||['name','bib','number'].some(k=>typeof r[k]!=='string'||r[k].length>(k==='name'?80:12))))throw Error('この画面で保存したメンバー表を選択してください。');rosterCapture();if((rosterDraft.rows.length||rosterDraft.title)&&!confirm('編集中の内容を、選んだファイルの内容に置き換えますか？'))return;rosterDraft={title:d.title,date:d.date,rows:d.rows};dashboard();}catch(e){toast(e.message);}finally{input.value='';}}
function rosterPrintHtml(d){const pages=[];for(let i=0;i<d.rows.length;i+=20)pages.push(d.rows.slice(i,i+20));return `<!doctype html><html lang="ja"><meta charset="utf-8"><title>メンバー表</title><style>@page{size:A4 portrait;margin:15mm}*{box-sizing:border-box}body{margin:0;color:#111;font:12pt sans-serif}section{break-after:page}section:last-child{break-after:auto}h1{font-size:21pt;margin:0 0 5mm}h2{font-size:15pt;margin:0 0 4mm;overflow-wrap:anywhere}p{margin:0 0 6mm}table{border-collapse:collapse;width:100%;table-layout:fixed}th,td{border:1px solid #222;padding:3mm;overflow-wrap:anywhere;height:10mm}th{background:#eee}th:first-child{width:12mm}th:nth-child(3),th:nth-child(4){width:28mm}footer{text-align:right;margin-top:4mm;font-size:10pt}</style>${pages.map((rows,p)=>`<section><h1>メンバー表</h1><h2>${esc(d.title)}</h2><p>開催日：${esc(d.date.replaceAll('-','/'))}</p><table><thead><tr><th>No.</th><th>選手名</th><th>ビブス</th><th>背番号</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${p*20+i+1}</td><td>${esc(r.name)}</td><td>${esc(r.bib)}</td><td>${esc(r.number)}</td></tr>`).join('')}</tbody></table><footer>${p+1} / ${pages.length}</footer></section>`).join('')}</html>`;}
function printRoster(){rosterCapture();if(!rosterDraft.title||!rosterDraft.date||!rosterDraft.rows.length||rosterDraft.rows.some(r=>!r.name)){toast('大会名・開催日・選手名を入力してください。');return;}let frame=document.getElementById('roster-print-frame');if(frame)frame.remove();frame=document.createElement('iframe');frame.id='roster-print-frame';frame.title='メンバー表の印刷';frame.style.cssText='position:fixed;width:1px;height:1px;left:-10000px;border:0';frame.onload=()=>{frame.contentWindow.focus();frame.contentWindow.print();};frame.srcdoc=rosterPrintHtml(rosterDraft);document.body.append(frame);}
document.addEventListener('input',e=>{if(e.target.closest('.roster-editor'))rosterCapture();});
