let attendanceMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1), categoryFilter='';
let coachScheduleDay='';
function familySwitcher(){const children=user.family_members||[user];return `<div class="card family-switcher"><label class="field family-select">報告するお子さま<select aria-label="報告するお子さま" onchange="switchFamilyMember(this.value)">${children.map(c=>`<option value="${esc(c.id)}" ${c.id===user.id?'selected':''}>${esc(c.name)}（${esc(c.grade)}）</option>`).join('')}</select></label><div class="family-mobile"><div class="family-mobile-heading"><span class="family-mobile-label">報告するお子さま</span>${page==='dashboard'?'':''}</div><div class="family-member-buttons" role="group" aria-label="報告するお子さま">${children.map(c=>`<button type="button" class="family-member-button" aria-pressed="${c.id===user.id}" data-member-id="${esc(c.id)}"><strong>${esc(c.name)}</strong><small>${esc(c.grade)}</small></button>`).join('')}</div></div>${page==='dashboard'?clubPhoneButton('コーチへ電話','family-condition-entry'):''}<p class="hint">現在は <strong>${esc(user.name)}</strong> さんの画面です。${['payments','checkout'].includes(page)?'会費のお支払いはご家庭単位のため、切り替えても請求内容は変わりません。':'各報告・申込みはこのお子さまの記録になります。'}</p></div>`;}
async function switchFamilyMember(id){
 if(switchingMember||id===user.id)return;
 if(reportDirty&&!await confirmAction('お子さまを切り替えますか？','入力中の未送信内容は保存されません。')){$('.family-select select').value=user.id;return;}
 switchingMember=true;const previous=selectedMember,previousUser=user,previousData=data;
 try{selectedMember=id;const nextUser=(await api('me')).user;if(!nextUser)throw Error('ログインの有効期限が切れました。再ログインしてください。');const nextData=await api('data');user=nextUser;data=nextData;sessionStorage.setItem('club_member',id);activeEvent='';categoryFilter='';reportDirty=false;render();toast(user.name+'さんの画面に切り替えました。');}
 catch(e){selectedMember=previous;user=previousUser;data=previousData;const select=$('.family-select select');if(select)select.value=user.id;toast(e.message);}
 finally{switchingMember=false;}
}
document.addEventListener('input',e=>{if(user?.role==='member'&&e.target.closest('form'))reportDirty=true;});
document.addEventListener('change',e=>{if(user?.role==='member'&&e.target.closest('form'))reportDirty=true;});
let coachAttendanceDate='', coachAttendanceCategory='';
function coachAttendanceList(){
 const dates=[...new Set(data.events.map(e=>e.date))].sort(),today=new Date().toLocaleDateString('sv-SE');
 if(!dates.includes(coachAttendanceDate))coachAttendanceDate=dates.find(d=>d>=today)||dates[dates.length-1]||'';
 const categories=[...new Set(data.events.flatMap(categoryNames))],events=data.events.filter(e=>e.date===coachAttendanceDate&&(!coachAttendanceCategory||categoryNames(e).includes(coachAttendanceCategory)));
 return heading('出欠・体調報告','事前の出欠予定と当日の体調報告を同じ一覧で確認し、点呼の結果を記録できます。')+`<div class="card form-grid"><label class="field">日付<select onchange="coachAttendanceDate=this.value;dashboard()">${dates.map(d=>`<option ${d===coachAttendanceDate?'selected':''}>${esc(d)}</option>`).join('')}</select></label><label class="field">カテゴリー<select onchange="coachAttendanceCategory=this.value;dashboard()"><option value="">すべて</option>${categories.map(c=>`<option ${c===coachAttendanceCategory?'selected':''}>${esc(c)}</option>`).join('')}</select></label></div><div class="toolbar attendance-day-detail-action"><button class="lime" onclick="openAttendanceDayDetails()" ${!coachAttendanceDate?'disabled':''}>出欠・体調の詳細を見る</button></div><p class="hint">出欠予定は事前回答、体調は当日の報告です。体調未報告でも点呼できます。実際の出欠はボタンを押すと保存され、押し直して変更できます。新しい回答は自動で反映します。</p><div class="stack">${events.map(e=>{
 if(e.kind==='体験会')return `<article class="card"><h2>${esc(e.title)}</h2><p>${esc(e.time)} ／ ${esc(e.place)}</p>${trialBookingList(e)}</article>`;
 const members=data.users.filter(u=>u.role==='member'&&u.active&&((u.categories||'U12').split(/[、,]/).some(c=>categoryNames(e).includes(c.trim()))||data.reports.some(r=>r.event_id===e.id&&r.user_id===u.id)));
 return `<article class="card" data-attendance-event="${esc(e.id)}">${categoryTags(e)}<h2>${esc(e.title)}</h2><p>${esc(e.time)} ／ ${esc(e.place)}</p><div class="attendance-counts" data-rollcall-counts>${rollcallCounts(e.id,members)}</div>${unifiedAttendanceTable(e,members)}${user.role==='admin'&&adminCan('attendance-list',true)?`<p><button class="lime" onclick="matchRosterForm('${e.id}')">詳細を編集・公開</button></p>`:''}</article>`;
 }).join('')||'<div class="card">該当する予定はありません。</div>'}</div>`;
}
function rollcallCounts(id,members){return ['出席','欠席','遅刻','未確認'].map(s=>`<span class="tag">${s} ${members.filter(u=>(data.reports.find(r=>r.event_id===id&&r.user_id===u.id)?.actual||'未確認')===s).length}人</span>`).join(' ');}
function unifiedAttendanceTable(e,members,readOnly=false){const canMark=!readOnly&&(user.role==='coach'||adminCan('attendance-list',true));return `<div class="condition-results"><div class="member-scroll-controls condition-scroll-controls"><span>↔ 横にスクロールして事前回答・体調を確認</span><input type="range" min="0" max="100" value="0" aria-label="出欠と体調一覧の横スクロール" oninput="scrollConditionTable(this)"></div><div class="table-wrap condition-overview unified-attendance" onscroll="syncConditionScroll(this)" tabindex="0" role="region" aria-label="出欠・体調報告一覧"><table><thead><tr>${['選手','実際の出欠（点呼）','学年','カテゴリー','出欠予定（事前）','事前の連絡事項','体の調子（当日）','心の調子（当日）','朝ご飯','調子の悪いところ','当日の連絡事項'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${members.map(u=>{const r=data.reports.find(r=>r.event_id===e.id&&r.user_id===u.id),meta=data.scheduling?.attendance?.find(r=>r.event_id===e.id&&r.user_id===u.id);return `<tr><td><b>${esc(u.name)}</b></td><td>${canMark?quickActualControls(e.id,u,r?.actual||''):`<span class="tag">${esc(r?.actual||'未確認')}</span>`}</td><td>${esc(u.grade||'未設定')}</td><td>${esc(u.categories||'未設定')}</td><td><span class="tag">${esc(r?.attendance||'未回答')}</span></td><td class="attendance-note">${esc(meta?.note||'—')}</td>${['body_condition','mind_condition','breakfast'].map(k=>`<td><span class="tag ${['良くない','ダメ'].includes(r?.[k])?'warn':''}">${conditionValue(r,k)}</span></td>`).join('')}<td class="attendance-note">${esc(r?.unwell_area||'—')}</td><td class="attendance-note">${esc(r?.note||'—')}</td></tr>`;}).join('')||'<tr><td colspan="11">対象の選手はいません。</td></tr>'}</tbody></table></div></div>`;}

function adminGuide(){const descriptions={members:'会員を追加して登録コードを発行します。登録申請の承認、在籍状況、学校名、ログイン情報の再設定を管理します。','staff-members':'スタッフを追加して登録コードを発行します。個別の編集権限、紹介内容、ログイン情報の再設定、削除を管理します。紹介編集の隣から活動承認へ進めます。',schedule:'日程カード上部の「詳細を編集・公開」で日程・参加メンバーを設定します。配車・撮影の依頼設定もここから開きます。','attendance-list':'日付・会員で絞り込み、事前出欠・当日の体調・実際の出欠をまとめて確認します。','condition-settings':'体調報告の質問文と選択肢を編集します。','injury-settings':'怪我報告の質問文と選択肢を編集します。','billing-settings':'今回・次回の会費、個別の請求停止理由、納入状況と支払い方法変更者を確認・設定します。','finance-admin':'役員を年度ごとに追加し、登録コードと操作権限を設定します。会計明細・領収書・交通費報告を確認できます。',settings:'公開ページの文章・画像・SNS・通常の練習日を編集します。その他の活動は専用の編集欄から更新します。','staff-approvals':'コーチ・スタッフの活動内容と実績を確認し、承認・取り消しを行います。'};return heading('管理設定ガイド','現在のメニューに合わせた操作ガイドです。')+[['各種設定',adminSettingsLinks],['各種確認',adminReviewLinks]].map(([title,links])=>`<section class="card"><h2>${title}</h2>${links.filter(([key])=>adminCan(key)).map(([key,icon,label])=>`<details><summary>${esc(label)}</summary><p>${esc(descriptions[key]||label+'の内容を確認・管理します。個別に権限を設定したスタッフ・役員は、許可された操作だけを利用できます。')}</p><a class="btn outline" href="#${key}">${esc(label)}を開く</a></details>`).join('')}</section>`).join('')+`<section class="card"><h2>配車・撮影</h2><p>日程ごとに別々に依頼を設定します。会員は家庭単位で回答し、管理者が割り振り案を調整・確定します。コーチは閲覧のみです。LINE未連携の場合、通知は送信されず未送信として履歴に残ります。</p></section>`;}

const categoryNames=e=>e.kind==='体験会'?['体験']:[...new Set((e.group_name||'未分類').split(/[、,]/).map(x=>x.trim()).filter(x=>x&&!/^U\d+$/i.test(x)))];
function attendanceFields(e,r,meta){const value=r.attendance==='遅刻'?'遅刻・早退':r.attendance||'',hidden=!value||value==='出席',required=value==='遅刻・早退';return `<div class="form-grid"><label class="field">出欠予定<select name="attendance_${e.id}" onchange="toggleAttendanceNote(this)">${['','出席','欠席','遅刻・早退','未定'].map(x=>`<option value="${x}" ${value===x?'selected':''}>${x||'未回答（選択してください）'}</option>`).join('')}</select></label><label class="field attendance-note" ${hidden?'hidden':''}><span>${required?'遅刻・早退の理由（必須）':'出欠の連絡事項'}</span><input name="note_${e.id}" maxlength="2000" value="${esc(meta?.note||'')}" placeholder="理由、到着・退出予定時刻など" ${hidden?'disabled':''} ${required?'required':''}></label></div>`;}
function toggleAttendanceNote(select){const label=select.closest('.form-grid').querySelector('.attendance-note'),input=label.querySelector('input'),hidden=!select.value||select.value==='出席',required=select.value==='遅刻・早退';label.hidden=hidden;input.disabled=hidden;input.required=required;label.querySelector('span').textContent=required?'遅刻・早退の理由（必須）':'出欠の連絡事項';}
function categoryTags(e){return categoryNames(e).filter(x=>user?.role!=='member'||(user.categories||'U12').split(/[、,]/).map(c=>c.trim()).includes(x)).map(x=>`<span class="tag category-tag" data-category="${esc(x)}">${esc(x)}</span>`).join(' ');}
function shiftAttendanceMonth(n){attendanceMonth=new Date(attendanceMonth.getFullYear(),attendanceMonth.getMonth()+n,1);dashboard();}
function publishedRoster(e){const r=(data.scheduling?.rosters||[]).find(r=>r.event_id===e.id);if(e.kind!=='試合')return '';if(!r?.published)return '<p class="hint">試合メンバー：選定中</p>';return `<div class="roster-published"><b>選出メンバー（公開済み）</b><p>${r.names.map(n=>esc(n.name)).join(' ／ ')||'選出メンバーなし'}</p>${user.role==='member'?`<span class="tag">${r.member_ids.includes(user.id)?'あなたは選出メンバーです':'今回は選出されていません'}</span>`:''}</div>`;}
function attendancePage(staff){
 const prefix=`${attendanceMonth.getFullYear()}-${String(attendanceMonth.getMonth()+1).padStart(2,'0')}`;
 const categories=staff?[...new Set(['男子A','女子A','男子B','女子B',...data.events.flatMap(categoryNames)])]:(user.categories||'U12').split(/[、,]/).map(x=>x.trim());
 const events=data.events.filter(e=>e.date.startsWith(prefix)&&(!categoryFilter||categoryNames(e).includes(categoryFilter)));
 const availableDays=[...new Set(events.map(e=>e.date))];
 if(staff&&(!coachScheduleDay||!coachScheduleDay.startsWith(prefix)))coachScheduleDay=availableDays.find(d=>d>=new Date().toLocaleDateString('sv-SE'))||availableDays[0]||'';
 const visibleEvents=staff?events.filter(e=>e.date===coachScheduleDay):events;
 const start=new Date(attendanceMonth.getFullYear(),attendanceMonth.getMonth(),1).getDay(),days=new Date(attendanceMonth.getFullYear(),attendanceMonth.getMonth()+1,0).getDate();
 return heading(staff?'月間日程・出欠確認・試合メンバー選定':'練習・試合日程・出欠報告',staff?'出欠を確認し、試合の選出メンバーを公開できます。':'1か月分の予定を確認して、事前に出欠を送信してください。下の日程ごとに、体調も練習前に報告できます。',staff?'<div class="toolbar schedule-create-actions"><button class="lime" onclick="eventForm()">＋ 日程を追加</button><button class="outline" onclick="bulkEventForm()">＋ 日程を一括登録</button></div>':'')+
 `<div class="toolbar month-toolbar"><button class="outline small" onclick="shiftAttendanceMonth(-1)" aria-label="前月">‹</button><h2>${attendanceMonth.getFullYear()}年 ${attendanceMonth.getMonth()+1}月</h2><button class="outline small" onclick="shiftAttendanceMonth(1)" aria-label="翌月">›</button><label>カテゴリー <select class="filter" onchange="categoryFilter=this.value;dashboard()"><option value="">すべて</option>${categories.map(x=>`<option ${categoryFilter===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label></div>
 ${!staff?'<p class="hint">青：✓ 回答済み　／　黄：● 未回答（保存済みの回答状況を表示）</p>':''}<div class="month-scroll"><div class="attendance-calendar">${['日','月','火','水','木','金','土'].map(x=>`<div class="calendar-weekday">${x}</div>`).join('')}${'<div class="calendar-blank"></div>'.repeat(start)}${Array.from({length:days},(_,i)=>{const day=prefix+'-'+String(i+1).padStart(2,'0');return `<div class="calendar-date ${staff&&coachScheduleDay===day?'coach-selected-day':''}">${staff?`<button type="button" class="calendar-day-select" aria-label="${day}の日程を表示" aria-pressed="${coachScheduleDay===day}" onclick="selectCoachScheduleDay('${day}')">${i+1}</button>`:`<b>${i+1}</b>`}${events.filter(e=>e.date===day).map(e=>{const r=data.reports.find(r=>r.event_id===e.id&&r.user_id===user.id);return `<button class="calendar-activity ${!staff?(r?.attendance?'answer-sent':'answer-missing'):''}" aria-label="${esc(e.date+' '+e.time+' '+e.title+' '+e.place+(!staff?(r?.attendance?' 回答済み '+r.attendance:' 未回答'):''))}" onclick="${staff?`selectCoachScheduleDay('${e.date}')`:`document.getElementById('plan-${e.id}').scrollIntoView({behavior:'smooth',block:'start'})`}"><span class="mobile-cal-summary"><span>${e.kind==='試合'?'試合':'練習'}</span><span>${esc(e.time.match(/\d{1,2}:\d{2}/)?.[0]||e.time)}</span>${!staff?`<span>${r?.attendance?'✓ 済':'● 未'}</span>`:''}</span>${articleNew('schedule',e.id)}${categoryTags(e)}<strong>${esc(e.time)}</strong><span>${esc(e.title)}</span><small>${e.kind==='練習'?'通常練習':esc(e.kind)}</small><small>${esc(e.place)}</small>${!staff?`<small class="attendance-label">${r?.attendance?'✓ 回答済み · '+esc(r.attendance):'● 未回答'}</small>`:''}</button>`}).join('')}</div>`;}).join('')}</div></div>${scheduleDocumentsPanel(staff,prefix)}<p class="hint">予定を押すと、下の詳細・出欠欄へ移動します。カテゴリーはコーチが日程編集画面で変更できます。</p>
 ${!staff?'<form onsubmit="saveMonthAttendance(event)"><div class="page-heading"><h2>この月の出欠予定</h2><button class="lime" '+(events.length?'':'disabled')+'>変更した出欠をまとめて送信</button></div>':''}${staff?`<div class="card form-grid" id="coach-schedule-filters"><label class="field">表示する日付<input type="date" value="${coachScheduleDay}" onchange="changeCoachScheduleDate(this.value)"></label><label class="field">表示するカテゴリー<select onchange="categoryFilter=this.value;dashboard()"><option value="">すべて</option>${categories.map(x=>`<option ${categoryFilter===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label></div><h2>${coachScheduleDay?esc(dateLabel(coachScheduleDay)):''}の回答結果</h2>`:''}<div class="stack">${visibleEvents.map(e=>{const r=data.reports.find(r=>r.event_id===e.id&&r.user_id===user.id)||{},meta=(data.scheduling?.attendance||[]).find(r=>r.event_id===e.id&&r.user_id===user.id);return `<article class="card plan-card" id="plan-${e.id}"><div class="page-heading"><div>${categoryTags(e)} <span class="tag">${e.kind==='練習'?'通常練習':esc(e.kind)}</span><h2>${esc(e.title)} ${articleNew('schedule',e.id)}</h2><p>${dateLabel(e.date)}　${esc(e.time)}<br>会場：${esc(e.place)}</p></div>${staff?`<div class="schedule-card-actions"><button type="button" class="outline small" onclick="eventForm('${e.id}',true)">複製する</button>${adminCan('schedule',true)||adminCan('attendance-list',true)?`<button type="button" class="lime small" onclick="matchRosterForm('${e.id}')">詳細を編集・公開</button>`:''}</div>`:''}</div>${!staff?`<div class="schedule-condition-action"><span class="tag ${hasCondition(r)?'':'warn'}">体調報告：${hasCondition(r)?'報告済み':'未報告'}</span><button type="button" class="lime" data-event="${esc(e.id)}" onclick="goToScheduleCondition(this.dataset.event)">${hasCondition(r)?'体調報告を確認・変更':'体調を報告する'}</button></div>`:''}${scheduleInlineMap(e)}${isPracticeDisplay(e)?practiceAddendum(e,staff):`<p><button type="button" class="outline" onclick="openActivityDetails('${e.id}')">詳細を確認する</button></p>`}${staff?`<p><button type="button" class="lime attendance-day-entry" onclick="openAttendanceDayDetails('${e.date}','','${e.id}')">出欠・体調の詳細を見る</button></p>`+staffAttendance(e):`${attendanceFields(e,r,meta)}<p class="actual-attendance-label">コーチ確認による実際の出欠：<strong>${esc(r.actual||'未確認')}</strong></p><button type="button" class="lime individual-attendance" onclick="saveIndividualAttendance('${e.id}',this)">この日の出欠を報告する</button><p class="error individual-attendance-error" role="alert"></p><div class="schedule-report-status"><p><b>出欠報告：</b>${r.attendance?'回答済み':'未回答'}${meta?.updated?'<br>最終送信：'+esc(meta.updated):''}</p><p><b>体調報告：</b>${hasCondition(r)?'報告済み':'未報告'}${hasCondition(r)?'<br>最終送信：'+(r.condition_updated?esc(r.condition_updated):'以前の報告（日時未記録）'):''}</p></div>`}${logisticsCards(e)}</article>`;}).join('')||'<div class="card empty">この月・カテゴリーの予定はありません。</div>'}</div>${!staff?'<div class="error" role="alert"></div></form>':''}`;
}
function staffAttendance(e){if(e.kind==='体験会')return trialBookingList(e,false);const members=data.users.filter(u=>u.role==='member'&&u.active&&(u.categories||'U12').split(/[、,]/).some(c=>categoryNames(e).includes(c.trim()))),rs=data.reports.filter(r=>r.event_id===e.id);return `<div class="table-wrap"><table><thead><tr><th>選手</th><th>出欠予定</th><th>出欠の連絡事項</th></tr></thead><tbody>${members.map(u=>{const r=rs.find(r=>r.user_id===u.id),m=data.scheduling.attendance.find(r=>r.event_id===e.id&&r.user_id===u.id);return `<tr><td>${esc(u.name)}<br><small>${esc(u.grade)}</small></td><td>${esc(r?.attendance||'未回答')}</td><td class="service-text">${esc(m?.note||'—')}</td></tr>`;}).join('')}</tbody></table></div>`;}
async function saveMonthAttendance(ev){ev.preventDefault();if(savingIndividualAttendance)return;const values=Object.fromEntries(new FormData(ev.target)),entries=[];for(const [key,value] of Object.entries(values)){if(!key.startsWith('attendance_')||!value)continue;const id=key.slice(11),old=data.reports.find(r=>r.event_id===id&&r.user_id===user.id),meta=data.scheduling.attendance.find(r=>r.event_id===id&&r.user_id===user.id),note=value==='出席'?'':(values['note_'+id]||'').trim();if(value!==old?.attendance||note!==(meta?.note||''))entries.push({event_id:id,attendance:value,note});}if(!entries.length){toast('変更した出欠予定がありません。');return;}await submit(ev,'attendance_batch',{entries},'出欠予定を送信しました。コーチが確認できます。');}
async function confirmAttendance(event_id,user_id,reviewed=true){try{await api('attendance_review',{event_id,user_id,reviewed});await refresh();toast(reviewed?'出欠予定を確認しました。':'未確認に戻しました。');}catch(e){toast(e.message);}}
function matchRosterForm(id){activityDetailsForm(id);}
async function saveMatchRoster(ev,id){ev.preventDefault();const f=new FormData(ev.target);await submit(ev,'roster',{event_id:id,member_ids:f.getAll('members'),published:f.get('published')==='1'},'試合メンバーを保存しました。');}
const hasCondition=r=>!!r.body_condition||r.condition!=null;
function conditionChoice(label,name,choices,value){return `<label class="field">${label}<select name="${name}" required><option value="">選択してください</option>${choices.map(v=>`<option ${value===v?'selected':''}>${v}</option>`).join('')}</select></label>`;}
function conditionOnly(){const r=data.reports.find(r=>r.event_id===activeEvent&&r.user_id===user.id)||{};return heading('体調報告','練習前に、その日のコンディションを送信してください。','<a class="btn lime" href="#schedule">日程・出欠報告へ</a>')+`<div class="two-col"><div class="card"><form onsubmit="saveConditionOnly(event)">${selectField('対象の練習・試合','event_id',data.events.map(e=>[e.id,e.date+' '+e.title]),activeEvent)}${reportQuestions('condition').map(q=>reportInput(q,r[q.id]||'',q.type==='select')).join('')}<div class="error" role="alert"></div><button class="lime" ${data.events.length?'':'disabled'}>体調を送信</button></form></div><div class="card"><h2>これまでの体調報告</h2><details class="injury-report-history condition-report-history"><summary><span class="history-show">報告履歴を見る</span><span class="history-hide">報告履歴を閉じる</span></summary><div class="injury-history-content">${reportHistory(data.reports)}</div></details></div></div>`;}
function conditionValue(r,key){return esc(r?.[key]||(r?.condition!=null?(key==='body_condition'?'旧形式：'+r.condition+' / 5':'旧形式では未収集'):'未報告'));}
function coachConditionRows(members,reports){return `<div class="card condition-results"><div class="member-scroll-controls condition-scroll-controls"><span>↔ 左右にスクロールして回答を確認できます</span><input type="range" min="0" max="100" value="0" aria-label="体調回答一覧の横スクロール" oninput="scrollConditionTable(this)"></div><div class="table-wrap condition-overview" tabindex="0" role="region" aria-label="選手ごとの体調回答一覧" onscroll="syncConditionScroll(this)"><table><thead><tr>${['選手','学年','カテゴリー','体の調子','心の調子','朝ご飯','調子の悪いところ','その他の連絡事項','出欠予定','実際の出欠'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${members.map(m=>{const r=reports.find(r=>r.user_id===m.id);return `<tr><td><b>${esc(m.name)}</b></td><td>${esc(m.grade||'未設定')}</td><td><span class="tag">${esc(m.categories||'未設定')}</span></td>${['body_condition','mind_condition','breakfast'].map(k=>`<td><span class="tag ${['良くない','ダメ','悪い'].includes(r?.[k])?'warn':''}">${conditionValue(r,k)}</span></td>`).join('')}<td>${esc(r?.unwell_area||'—')}</td><td>${esc(r?.note||'—')}</td><td>${esc(r?.attendance||'未回答')}</td><td><select aria-label="${esc(m.name)}の実際の出欠" onchange="saveActual('${m.id}',this.value)">${['','出席','欠席','遅刻'].map(x=>`<option ${r?.actual===x?'selected':''} value="${x}">${x||'未確認'}</option>`).join('')}</select></td></tr>`;}).join('')}</tbody></table></div></div>`;}
async function saveConditionOnly(ev){ev.preventDefault();await submit(ev,'condition',Object.fromEntries(new FormData(ev.target)),'体調をコーチに送信しました。');}
document.addEventListener('change',e=>{if(page==='condition'&&user?.role==='member'&&e.target.name==='event_id'){activeEvent=e.target.value;dashboard();}});
function scheduleDocumentsPanel(staff,month){const docs=(data.schedule_documents||[]).filter(d=>d.month===month);return `<section class="schedule-documents" aria-label="日程PDF"><div class="schedule-pdf-heading"><strong>日程PDF</strong>${staff?`<button class="outline small" onclick="scheduleDocumentForm('${month}')">＋ PDFを添付</button>`:''}</div>${docs.map(d=>{const url='/basketball-club/api/schedule_pdf?id='+encodeURIComponent(d.id)+'&member='+encodeURIComponent(user.id);return `<div class="schedule-pdf-link"><a class="text-link" href="${url}" target="_blank" rel="noopener">${esc(d.title)}（PDFを開く）</a><a class="text-link" href="${url}&download=1">ダウンロード</a>${staff?`<span>${d.categories?.length?esc(d.categories.join('・')):d.member_ids.length+'人'}に公開 <button class="text-link" onclick="removeScheduleDocument('${d.id}')">削除</button></span>`:''}</div>`}).join('')||'<p class="hint">この月の日程PDFはまだ添付されていません。</p>'}${docs.length?'<p class="hint">別タブでPDFが開きます。印刷はPDF画面の印刷メニュー、スマホでは共有メニューから行えます。</p>':''}</section>`;}

function scheduleDocumentForm(month){modal('会員向け日程PDFを添付',`<form onsubmit="saveScheduleDocument(event)">${field('タイトル','title',month+' 月間日程')}${field('対象月','month',month,'month')}<label class="field">PDFファイル（最大30件・1件5MB以下）<input type="file" name="pdf" multiple accept="application/pdf,.pdf" required></label><fieldset><legend>閲覧できるカテゴリ（複数選択可）</legend>${['男子A','男子B','女子A','女子B','U15A','U15B'].map(g=>`<label class="check-row"><input type="checkbox" name="categories" value="${g}">${g}</label>`).join('')}</fieldset><p class="hint">選択したカテゴリに登録されている会員が閲覧できます。</p><div class="error" role="alert"></div><button class="lime">PDFを保存</button></form>`);}
async function saveScheduleDocument(ev){ev.preventDefault();const f=new FormData(ev.target),input=ev.target.elements.pdf,files=[...input.files],button=ev.submitter;button.disabled=true;try{if(!files.length||files.length>30||files.some(file=>file.size>5*1024*1024))throw Error('PDFは最大30件・1件5MB以下にしてください。');for(const file of files){const content=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});await api('schedule_document',{title:String(f.get('title')+(files.length>1?'：'+file.name:'')).slice(0,100),month:f.get('month'),categories:f.getAll('categories'),content});setUploadSelection(input,[...input.files].filter(x=>uploadFileKey(x)!==uploadFileKey(file)));data=await api('data');$('#modal').dataset.editToken=data.edit_token||'';}$('#modal').close();await refresh();toast('日程PDFを添付しました。');}catch(e){ev.target.querySelector('.error').textContent=e.message+' 保存済みのファイルは選択一覧から除いています。';}finally{button.disabled=false;}}
async function removeScheduleDocument(id){if(!await confirmAction('PDFを削除しますか？','この添付PDFが閲覧できなくなります。'))return;try{await api('schedule_document',{id,delete:true});await refresh();toast('PDFを削除しました。');}catch(e){toast(e.message);}}

document.addEventListener('click',e=>{const b=e.target.closest('.family-member-button');if(b)switchFamilyMember(b.dataset.memberId);});

function scheduleInlineMap(e){
 const address=activityBrief(e.id)?.address||e.address||'';
 const url=address?venueMapUrl(address):activityBrief(e.id)?.map_url||e.map_url;
 if(!url)return '';
 const sample=url==='https://www.google.com/maps?q=34.7968,134.9902';
 return `<div class="schedule-inline-map">${address?`<p>住所：${esc(address)}</p><iframe title="${esc(e.place)}の地図" src="https://maps.google.com/maps?q=${encodeURIComponent(address)}&output=embed" width="100%" height="220" style="border:0;border-radius:12px" loading="lazy"></iframe>`:''}${sample?`<p class="hint">地図サンプル（三木市周辺・実際の会場ではありません）</p><iframe title="${esc(e.title)}の地図サンプル：三木市周辺" src="https://maps.google.com/maps?q=34.7968,134.9902&z=14&output=embed" width="100%" height="220" style="border:0;border-radius:12px" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`:''}<p><a class="text-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">会場の地図を開く</a></p></div>`;
}

function isPracticeDisplay(e){return e.kind==='練習'||e.title.includes('練習');}
function practiceAddendum(e,staff){return `<p><button type="button" class="outline" onclick="openActivityDetails('${e.id}')">詳細を確認する</button></p>`;}

async function savePracticeAddendum(ev,id){ev.preventDefault();const button=ev.submitter,b=activityBrief(id,true)||activityBrief(id),e=data.events.find(e=>e.id===id);button.disabled=true;try{await api('event_briefing',{event_id:id,mode:b?.mode||'all',member_ids:b?.member_ids||[],note:new FormData(ev.target).get('note'),map_url:b?.map_url||e.map_url||'',keep_files:(b?.files||[]).map(f=>f.id),uploads:[],publish:true});await refresh();toast('追記事項を公開し、NEWを付けました。');}catch(error){ev.target.querySelector('.error').textContent=error.message;}finally{button.disabled=false;}}

let savingIndividualAttendance=false;
async function saveIndividualAttendance(id,button){
 if(savingIndividualAttendance)return;
 const card=button.closest('.plan-card'),select=card.querySelector('select[name="attendance_'+id+'"]'),noteInput=card.querySelector('input[name="note_'+id+'"]'),error=card.querySelector('.individual-attendance-error');
 error.textContent='';
 if(!select.value){error.textContent='出欠予定を選択してください。';select.focus();return;}
 if(!noteInput.disabled&&!noteInput.reportValidity())return;
 const note=select.value==='出席'?'':noteInput.value.trim();
 if(select.value==='遅刻・早退'&&!note){error.textContent='遅刻・早退の理由を入力してください。';noteInput.focus();return;}
 const owner=user.id,attendance=select.value; savingIndividualAttendance=true;button.disabled=true;button.textContent='送信中…';
 try{
  const result=await api('attendance_batch',{entries:[{event_id:id,attendance,note}]});
  const fresh=await api('data');if(user.id!==owner)return;data=fresh;
  if(page==='schedule'){
   const drafts=[...document.querySelectorAll('.plan-card select[name^="attendance_"],.plan-card input[name^="note_"]')].filter(el=>el.name!=='attendance_'+id&&el.name!=='note_'+id).map(el=>({name:el.name,value:el.value}));
   const scroll=window.scrollY;dashboard();
   for(const draft of drafts){const el=document.getElementsByName(draft.name)[0];if(el){el.value=draft.value;if(el.tagName==='SELECT')toggleAttendanceNote(el);}}
   reportDirty=[...document.querySelectorAll('.plan-card select[name^="attendance_"]')].some(el=>{const eid=el.name.slice(11),saved=data.reports.find(r=>r.event_id===eid&&r.user_id===owner),meta=data.scheduling.attendance.find(r=>r.event_id===eid&&r.user_id===owner),input=document.getElementsByName('note_'+eid)[0];return el.value!==(saved?.attendance==='遅刻'?'遅刻・早退':saved?.attendance||'')||(el.value&&el.value!=='出席'&&input.value.trim()!==(meta?.note||''));});
   window.scrollTo({top:scroll,behavior:'instant'});
  }
  toast(result.excel?.ok===false?result.excel.message:'この日の出欠を送信しました。');
 }catch(e){if(error.isConnected)error.textContent=e.message;else toast(e.message);}
 finally{savingIndividualAttendance=false;button.disabled=false;button.textContent='この日の出欠を報告する';}
}

function quickActualControls(eventId,member,value){return `<div class="quick-actual" data-event-id="${esc(eventId)}" data-user-id="${esc(member.id)}"><strong>実際の出欠：<span class="actual-value">${esc(value||'未確認')}</span></strong><div class="quick-actual-buttons" role="group" aria-label="${esc(member.name)}の実際の出欠">${['出席','欠席','遅刻',''].map(v=>`<button type="button" class="${value===v?'lime':'outline'}" aria-pressed="${value===v}" data-value="${v}" onclick="saveQuickActual(this)">${v||'未確認'}</button>`).join('')}</div><p class="quick-actual-status hint" role="status" aria-live="polite"></p></div>`;}
async function saveQuickActual(button){const box=button.closest('.quick-actual'),buttons=[...box.querySelectorAll('button')],status=box.querySelector('.quick-actual-status'),eventId=box.dataset.eventId,uid=box.dataset.userId,value=button.dataset.value;if(buttons.some(b=>b.disabled))return;buttons.forEach(b=>b.disabled=true);status.textContent='保存中…';try{const result=await api('actual',{user_id:uid,event_id:eventId,actual:value,_edit_token:box.dataset.editToken||renderEditToken});const fresh=await api('data');box.dataset.editToken=fresh.edit_token||'';const r=data.reports.find(r=>r.event_id===eventId&&r.user_id===uid);if(r)r.actual=value;else data.reports.push({event_id:eventId,user_id:uid,actual:value});box.querySelector('.actual-value').textContent=value||'未確認';const card=box.closest('[data-attendance-event]');if(card){const ids=[...card.querySelectorAll('.quick-actual')].map(x=>x.dataset.userId);card.querySelector('[data-rollcall-counts]').innerHTML=rollcallCounts(eventId,data.users.filter(u=>ids.includes(u.id)));}buttons.forEach(b=>{const chosen=b.dataset.value===value;b.className=chosen?'lime':'outline';b.setAttribute('aria-pressed',String(chosen));});status.textContent=result.excel?.ok?'保存しました。Excelにも反映済みです。':'出欠を保存しました。'+(result.excel?.message||'');}catch(e){status.textContent='保存できませんでした：'+e.message;}finally{buttons.forEach(b=>b.disabled=false);}}

function selectCoachScheduleDay(day){coachScheduleDay=day;dashboard();document.getElementById('coach-schedule-filters')?.scrollIntoView({behavior:'smooth',block:'start'});}
function changeCoachScheduleDate(day){if(!/^\d{4}-\d{2}-\d{2}$/.test(day))return;coachScheduleDay=day;attendanceMonth=new Date(day+'T12:00:00');dashboard();}

function trialBookingList(event,editDate=true){const bookings=(data.trials||[]).filter(t=>t.event_id===event.id);return `<h3>体験予約者（${bookings.length}名）</h3><div class="trial-edit-actions"><button class="lime" onclick="activityDetailsForm('${event.id}')">日程・詳細を編集・公開</button></div><div class="attendance-people">${bookings.map(t=>`<div class="attendance-person"><div><strong>${esc(t.name)}</strong><small> ${esc(t.grade)}</small></div><span class="tag">体験予約</span><p>保護者：${esc(t.parent_name||'—')}</p>${t.note?`<p>連絡事項：${esc(t.note)}</p>`:''}<div class="attendance-review">${t.reviewed_at?'申込確認済み':`<button class="outline small" onclick="reviewTrial('${t.id}',this)">申込を確認する</button>`}</div></div>`).join('')||'<p class="hint">この体験会への予約はまだありません。</p>'}</div>`;}

function toggleCoachRoster(button,count){const panel=document.getElementById(button.getAttribute("aria-controls"));const open=button.getAttribute("aria-expanded")!=="true";panel.hidden=!open;button.setAttribute("aria-expanded",String(open));button.textContent=open?"− 選手の出欠一覧を閉じる":"＋ 選手の出欠一覧を開く（"+count+"名）";}


function bulkEventForm(){modal('練習・試合日程を一括登録',`<p>日程ごとに内容を入力してください。「前の内容で追加」で、日付以外の内容をコピーできます。最大50件までまとめて登録できます。</p><form onsubmit="saveBulkEvents(event)"><div id="bulk-event-rows" class="stack"></div><div class="error" role="alert"></div><div class="dialog-actions"><button type="button" class="outline" onclick="addBulkEventRow()">＋ 前の内容で追加</button><button class="lime">まとめて登録</button></div></form>`);addBulkEventRow();}
function bulkEventValues(row){return Object.fromEntries([...row.querySelectorAll('input:not([type=checkbox]),select,textarea')].map(el=>[el.name,el.value]).concat([['group_name',[...row.querySelectorAll('[name=group]:checked')].map(el=>el.value).join('、')]]));}
function addBulkEventRow(){const area=$('#bulk-event-rows'),last=area.lastElementChild;if(area.children.length>=50){toast('一度に50件まで登録できます。');return;}const v=last?bulkEventValues(last):{kind:'練習',time:'09:00〜12:00',group_name:categoryFilter||'男子A'};const row=document.createElement('fieldset');row.className='card';row.innerHTML=`<legend>登録する日程</legend>${scheduleTitleField(v.title||'',v.kind)}<div class="form-grid">${field('日付','date','','date')}${field('時間','time',v.time)}${venueFields(v.place||'',v.address||'')}</div><fieldset><legend>カテゴリー（複数選択可）</legend>${['男子A','男子B','女子A','女子B','U15A','U15B'].map(g=>`<label class="check-row"><input type="checkbox" name="group" value="${g}" ${(v.group_name||'').split('、').includes(g)?'checked':''}>${g}</label>`).join('')}</fieldset>${field('地図URL（任意）','map_url',v.map_url||'','url',false)}<label class="field">詳細・集合時間<textarea name="note">${esc(v.note||'')}</textarea></label><button type="button" class="outline small" onclick="this.closest('fieldset.card').remove()">この日程を外す</button>`;area.append(row);row.querySelector('[name=date]').focus();}
async function saveBulkEvents(ev){ev.preventDefault();const rows=[...ev.target.querySelector('#bulk-event-rows').children].map(bulkEventValues);await submit(ev,'events_bulk',{events:rows},rows.length+'件の日程を登録しました。');}

function scrollConditionTable(slider){const table=slider.closest(".condition-results").querySelector(".table-wrap");table.scrollLeft=(table.scrollWidth-table.clientWidth)*Number(slider.value)/100;}
function syncConditionScroll(table){const slider=table.closest(".condition-results").querySelector(".condition-scroll-controls input");slider.value=table.scrollWidth>table.clientWidth?100*table.scrollLeft/(table.scrollWidth-table.clientWidth):0;}

let conditioningMember='',conditioningDate='';
function conditioningPage(){const members=data.users.filter(u=>u.role==='member'),rows=data.reports.filter(r=>hasCondition(r)&&(!conditioningMember||r.user_id===conditioningMember)&&(!conditioningDate||data.events.find(e=>e.id===r.event_id)?.date===conditioningDate)).sort((a,b)=>(data.events.find(e=>e.id===b.event_id)?.date||'').localeCompare(data.events.find(e=>e.id===a.event_id)?.date||''));const query='member='+encodeURIComponent(conditioningMember)+'&date='+encodeURIComponent(conditioningDate);return heading('コンディショニングシート','会員・日付で過去の体調報告を確認できます。')+`<div class="card form-grid"><label class="field">会員名<select onchange="conditioningMember=this.value;conditioningDate='';dashboard()"><option value="">すべて</option>${members.map(m=>`<option value="${esc(m.id)}" ${m.id===conditioningMember?'selected':''}>${esc(m.name)}</option>`).join('')}</select></label><label class="field">日付（空欄は全期間）<input type="date" value="${esc(conditioningDate)}" onchange="conditioningDate=this.value;dashboard()"></label><button class="outline" onclick="conditioningMember='';conditioningDate='';dashboard()">すべての報告を表示</button></div><div class="toolbar"><a class="btn outline" href="/basketball-club/api/conditioning_export?format=csv&${query}">CSVをダウンロード</a><a class="btn outline" href="/basketball-club/api/conditioning_export?format=pdf&${query}">PDFをダウンロード</a></div><details class="card"><summary><b>PCの固定ファイルから反映</b></summary><p>サーバーを動かしているPCの「data / コンディショニング入力.csv」を編集して保存してください。約5秒ごとに読み込みます。ダウンロードしたCSVをこの名前で保存して編集することもできます。</p><p>会員ID・日程IDで照合し、体調の項目だけ更新します。CSVから行を削除しても、報告は削除されません。変更していない行で後から届いた報告を上書きすることもありません。</p><p class="hint">${esc(data.conditioning_status?.message||'入力待ち')} ${esc(data.conditioning_status?.updated||'')}</p></details><p>${rows.length}件の報告</p><div class="condition-results"><div class="member-scroll-controls condition-scroll-controls"><span>↔ 左右にスクロールできます</span><input type="range" min="0" max="100" value="0" aria-label="体調履歴の横スクロール" oninput="scrollConditionTable(this)"></div><div class="table-wrap conditioning-history-table" onscroll="syncConditionScroll(this)"><table><thead><tr>${['会員名','日付','日程','学年','体の調子','心の調子','朝ご飯','調子の悪いところ','連絡事項'].map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>{const m=members.find(m=>m.id===r.user_id),e=data.events.find(e=>e.id===r.event_id);return `<tr><td>${esc(m?.name||r.user_id)}</td><td>${esc(e?.date||'')}</td><td>${esc(e?.title||'')}</td><td>${esc(m?.grade||'')}</td>${['body_condition','mind_condition','breakfast'].map(k=>`<td>${conditionValue(r,k)}</td>`).join('')}<td>${esc(r.unwell_area||'—')}</td><td>${esc(r.note||'—')}</td></tr>`;}).join('')||'<tr><td colspan="9">該当する体調報告はありません。</td></tr>'}</tbody></table></div></div>`;}

async function goToScheduleCondition(id){if(reportDirty&&!await confirmAction('体調報告へ移動しますか？','入力中の出欠はまだ送信されていません。移動すると未送信の入力は失われます。'))return;reportDirty=false;activeEvent=id;location.hash='condition';}

function attendanceDayMembers(event){return data.users.filter(u=>u.role==='member'&&u.active&&((u.categories||'U12').split(/[、,]/).some(c=>categoryNames(event).includes(c.trim()))||data.reports.some(r=>r.event_id===event.id&&r.user_id===u.id)));}
async function openAttendanceDayDetails(selectedDay=coachAttendanceDate,selectedCategory=coachAttendanceCategory,selectedEvent=''){
 if(user?.role!=='coach'&&!adminCan('attendance-list'))return;
 const date=selectedDay,category=selectedCategory;if(!date)return;
 modal(date+'の出欠・体調報告','<p>最新の報告を読み込んでいます…</p>');const dialog=$('#modal');dialog.classList.add('attendance-day-dialog');dialog.addEventListener('close',()=>dialog.classList.remove('attendance-day-dialog'),{once:true});
 try{const fresh=await api('data');if(!dialog.open)return;data=fresh;const events=data.events.filter(e=>e.date===date&&(!selectedEvent||e.id===selectedEvent)&&(!category||categoryNames(e).includes(category)));const sections=events.map(e=>{
  if(e.kind==='体験会'){const bookings=(data.trials||[]).filter(t=>t.event_id===e.id);return `<section class="attendance-day-section"><h3>${esc(e.title)}</h3><p>${esc(e.time)} ／ ${esc(e.place)}</p><p class="hint">体験予約者は会員の出欠・体調報告の対象外です。</p>${bookings.map(t=>`<p>${esc(t.name)} ／ ${esc(t.grade)} ／ 体験予約</p>`).join('')||'<p>予約者はいません。</p>'}</section>`;}
  const members=attendanceDayMembers(e),reported=members.filter(m=>data.reports.some(r=>r.event_id===e.id&&r.user_id===m.id&&hasCondition(r))).length;
  return `<section class="attendance-day-section"><h3>${esc(e.title)}</h3><p>${esc(e.time)} ／ ${esc(e.place)}</p><div class="attendance-counts">${rollcallCounts(e.id,members)} <span class="tag">体調報告 ${reported} / ${members.length}人</span></div>${attendanceDayCompact(e,members)}</section>`;
 }).join('');dialog.querySelector('.dialog-head').insertAdjacentHTML('afterend',`<div class="attendance-day-content"><p>欠席予定・未回答も表示。${category?'対象：'+esc(category):''}</p>${sections||'<p>該当する日程はありません。</p>'}<div class="dialog-actions"><button class="outline" onclick="$('#modal').close()">閉じる</button></div></div>`);dialog.querySelector(':scope > p')?.remove();
 }catch(e){const p=dialog.querySelector(':scope > p');if(p)p.textContent=e.message;}
}

function attendanceDayCompact(event,members){return `<div class="attendance-compact"><div class="attendance-compact-head"><span>名前</span><span>事前出欠</span><span>実際の出欠</span><span>体の調子</span><span>心の調子</span><span>朝ご飯</span></div>${members.map(m=>{const r=data.reports.find(r=>r.event_id===event.id&&r.user_id===m.id),meta=data.scheduling?.attendance?.find(r=>r.event_id===event.id&&r.user_id===m.id),notes=[['事前の連絡',meta?.note],['調子の悪いところ',r?.unwell_area],['当日の連絡',r?.note]].filter(([,v])=>v&&v.trim()&&v.trim()!=='—');const values=[r?.attendance||'未回答',r?.actual||'未確認',...['body_condition','mind_condition','breakfast'].map(k=>r?.[k]||(r?.condition!=null?(k==='body_condition'?'旧形式：'+r.condition+'/5':'未収集'):'未報告'))];return `<article class="attendance-compact-person"><div class="attendance-compact-row"><strong class="attendance-compact-name">${esc(m.name)}</strong>${values.map((v,i)=>`<div class="attendance-compact-value ${['ダメ','悪い','良くない','欠席'].includes(v)?'needs-care':''}"><small>${['事前出欠','実際の出欠','体の調子','心の調子','朝ご飯'][i]}</small><span>${esc(v)}</span></div>`).join('')}</div>${notes.length?`<details class="attendance-compact-notes"><summary>連絡・体調の補足（${notes.length}件）</summary>${notes.map(([k,v])=>`<p><b>${k}：</b>${esc(v)}</p>`).join('')}</details>`:''}</article>`;}).join('')||'<p>対象の選手はいません。</p>'}</div>`;}

function combinedReportsPage(){
 const members=data.users.filter(u=>u.role==='member'),events=data.events.filter(e=>e.kind!=='体験会'&&(!conditioningDate||e.date===conditioningDate)).slice().sort((a,b)=>b.date.localeCompare(a.date));
 const rows=events.flatMap(e=>members.filter(m=>(!conditioningMember||m.id===conditioningMember)&&((m.active&&categoryNames(e).some(k=>(m.categories||'').split(/[、,]/).includes(k)))||data.reports.some(r=>r.event_id===e.id&&r.user_id===m.id))).map(m=>({e,m,r:data.reports.find(r=>r.event_id===e.id&&r.user_id===m.id)||{}})));
 const canMark=user.role==='coach'||adminCan('attendance-list',true),query='member='+encodeURIComponent(conditioningMember)+'&date='+encodeURIComponent(conditioningDate);
 return heading('出欠・体調報告','事前の出欠予定・当日の体調・実際の出欠をまとめて確認できます。')+`<div class="card form-grid"><label class="field">会員名<select onchange="conditioningMember=this.value;dashboard()"><option value="">すべて</option>${members.map(m=>`<option value="${esc(m.id)}" ${m.id===conditioningMember?'selected':''}>${esc(m.name)}</option>`).join('')}</select></label><label class="field">日付（空欄は全期間）<input type="date" value="${esc(conditioningDate)}" onchange="conditioningDate=this.value;dashboard()"></label><button class="outline" onclick="conditioningMember='';conditioningDate='';dashboard()">すべての報告を表示</button></div><div class="toolbar"><a class="btn outline" href="/basketball-club/api/conditioning_export?format=csv&${query}">体調報告CSV</a><a class="btn outline" href="/basketball-club/api/conditioning_export?format=pdf&${query}">体調報告PDF</a>${conditioningDate?`<button class="lime" onclick="openAttendanceDayDetails('${conditioningDate}','')">当日の詳細を見る</button>`:''}</div><details class="card"><summary>PCの固定ファイルから反映</summary><p>体調は「data / コンディショニング入力.csv」、実際の出欠は「data / 出欠入力.xlsx」を編集すると自動反映されます。</p></details><p>${rows.length}件 ／ 体調未報告の会員も表示します。</p><div class="condition-results"><div class="member-scroll-controls condition-scroll-controls"><span>左右にスクロールして確認</span><input type="range" min="0" max="100" value="0" aria-label="報告一覧の横スクロール" oninput="scrollConditionTable(this)"></div><div class="table-wrap conditioning-history-table" onscroll="syncConditionScroll(this)"><table><thead><tr>${['会員名','日付・日程','事前の出欠','実際の出欠','バスケノート','体調報告','体の調子','心の調子','朝ご飯','調子の悪いところ','連絡事項'].map(t=>`<th>${t}</th>`).join('')}</tr></thead><tbody>${rows.map(({e,m,r})=>`<tr><td style="white-space:nowrap">${esc(m.name)}</td><td>${esc(e.date)}<br>${esc(e.title)}</td><td>${esc(r.attendance||'未回答')}</td><td>${canMark?quickActualControls(e.id,m,r.actual||''):esc(r.actual||'未確認')}</td><td>${basketNoteStatusControl(e.id,m,canMark)}</td><td><span class="tag ${hasCondition(r)?'':'warn'}">${hasCondition(r)?'報告済み':'未報告'}</span></td>${['body_condition','mind_condition','breakfast'].map(k=>`<td>${conditionValue(r,k)}</td>`).join('')}<td>${esc(r.unwell_area||'—')}</td><td>${esc(r.note||'—')}</td></tr>`).join('')||'<tr><td colspan="11">対象の日程・会員はありません。</td></tr>'}</tbody></table></div></div>`;
}

function basketNoteStatusControl(eid,m,edit){const r=(data.basket_note_statuses||[]).find(r=>r.event_id===eid&&r.user_id===m.id),status=r?.status||'未提出';return `<div class="basket-note-status"><select aria-label="${esc(m.name)}のバスケノート提出状況" data-user="${esc(m.id)}" data-event="${esc(eid)}" onchange="saveBasketNoteStatus(this)" ${edit?'':'disabled'}>${['提出','未提出','報告有忘','報告無忘','提出未記入'].map(s=>`<option ${s===status?'selected':''}>${s}</option>`).join('')}</select><p class="hint" role="status"></p></div>`;}
async function saveBasketNoteStatus(select){const old=(data.basket_note_statuses||[]).find(r=>r.event_id===select.dataset.event&&r.user_id===select.dataset.user),status=select.nextElementSibling;select.disabled=true;select.dataset.saving='true';try{await api('basket_note_status',{user_id:select.dataset.user,event_id:select.dataset.event,revision:old?.revision||null,status:select.value});const fresh=await api('data');data.basket_note_statuses=fresh.basket_note_statuses;data.basket_notes=fresh.basket_notes;status.textContent='保存しました。';}catch(e){select.value=old?.status||'未提出';status.textContent=e.message;}finally{select.disabled=false;delete select.dataset.saving;}}
