function shopIcon(title){const name=shopTitle(title);if(/靴下|ソックス/.test(name))return '🧦';if(/パンツ|ショーツ/.test(name))return '🩳';if(/ウェア|ウエア|シャツ|服|ユニフォーム/.test(name))return '👕';if(/シューズ|靴/.test(name))return '👟';if(/ボール/.test(name))return '🏀';return '🏅';}
function shopTitle(value){return String(value||'').replace(/[（(]デモ[）)]/g,'').trim();}
function shopGallery(p){return p.images.length?`<div class="shop-gallery"><img class="shop-main-photo" src="${esc(p.images[0])}" alt="${esc(shopTitle(p.title))}の商品写真" loading="lazy"><div class="shop-thumbnails">${p.images.map((url,i)=>`<button type="button" class="outline" aria-label="写真${i+1}を表示" onclick="this.closest('.shop-gallery').querySelector('.shop-main-photo').src=this.querySelector('img').src"><img src="${esc(url)}" alt="写真${i+1}"></button>`).join('')}</div></div>`:'<p class="hint">商品写真は準備中です。</p>';}
function shopPage(){return `<div id="shop-cart-panel">${shopCartPanel()}</div><div class="shop-grid">${(data.shop?.products||[]).map(p=>`<article class="card shop-product">${shopGallery(p)}<h2><span aria-hidden="true">${shopIcon(p.title)}</span> ${esc(shopTitle(p.title))}</h2><p class="service-text">${esc(p.body)}</p><p class="service-price">¥${p.amount.toLocaleString()} <small>税込・1点</small></p><form onsubmit="addShopCart(event,'${p.id}')">${selectField('サイズ・種類','size',p.sizes,p.sizes[0])}${selectField('数量','quantity',Array.from({length:20},(_,i)=>[i+1,String(i+1)]),1)}<label class="field">連絡事項（任意）<textarea name="note" maxlength="1000"></textarea></label><div class="dialog-actions"><button class="lime">カートに入れる</button><button type="button" class="outline" onclick="document.querySelector('#shop-cart-panel').scrollIntoView({behavior:'smooth'})">カートを見る</button></div></form></article>`).join('')}</div><details class="shop-purchase-history"><summary><span class="history-show">購入履歴を見る</span><span class="history-hide">購入履歴を閉じる</span></summary><div class="shop-history-content"><h2>ご注文・支払い履歴</h2>${shopOrderHistory(false)}</div></details>`;}
let shopDraft=null;
function shopSummary(b){const items=b.items||[b];return items.map(i=>`<div class="shop-summary-line"><h3>${esc(shopTitle(i.title))}</h3><p>${esc(i.size)} ／ ${i.quantity}点 × ¥${i.unit_price.toLocaleString()}（税込）</p><p>小計：<strong>¥${i.subtotal.toLocaleString()}</strong></p>${i.note?`<p class="service-text">連絡事項：${esc(i.note)}</p>`:''}</div>`).join('')+`<dl class="shop-summary"><dt>受け取り</dt><dd>練習時に手渡し</dd><dt>送料</dt><dd>¥0</dd><dt><strong>お支払い合計金額</strong></dt><dd><strong>¥${b.total.toLocaleString()}</strong></dd></dl>`;}
function cartKey(){return 'club_shop_cart_v1_'+user.id;}
function readShopCart(){try{const c=JSON.parse(localStorage.getItem(cartKey()));if(c&&Array.isArray(c.items)&&c.token)return c;}catch{}return {items:[],token:crypto.randomUUID()};}
function writeShopCart(c){localStorage.setItem(cartKey(),JSON.stringify(c));const box=document.querySelector('#shop-cart-panel');if(box)box.innerHTML=shopCartPanel();}
function shopCartPanel(){const c=readShopCart(),total=c.items.reduce((n,i)=>n+i.unit_price*i.quantity,0);return `<section class="card shop-cart"><div class="toolbar"><h2>カート（${c.items.reduce((n,i)=>n+i.quantity,0)}点）</h2><span class="hint">${esc(user.name)}さんのカート</span></div>${c.items.length?c.items.map((i,n)=>`<div class="shop-cart-row"><div><strong>${esc(shopTitle(i.title))}</strong><p>${esc(i.size)} ／ 税込単価 ¥${i.unit_price.toLocaleString()}</p>${i.note?`<p class="hint">${esc(i.note)}</p>`:''}</div><div class="shop-cart-controls"><label class="field">数量<select aria-label="${esc(shopTitle(i.title))} ${esc(i.size)}の数量" onchange="changeShopCart(${n},this.value)">${Array.from({length:20},(_,q)=>`<option value="${q+1}" ${q+1===i.quantity?'selected':''}>${q+1}</option>`).join('')}</select></label><strong class="shop-cart-line-total">¥${(i.unit_price*i.quantity).toLocaleString()}</strong><button class="outline small" onclick="removeShopCart(${n})">削除</button></div></div>`).join('')+`<p class="shop-cart-total">お支払い合計金額：<strong>¥${total.toLocaleString()}</strong><small>（税込・送料0円）</small></p><button class="lime" onclick="confirmShopCart()">ご注文内容を確認</button>`:'<p>カートは空です。下の商品からサイズ・数量を選んで追加してください。</p>'}</section>`;}
function addShopCart(ev,id){ev.preventDefault();const f=new FormData(ev.target),p=data.shop.products.find(p=>p.id===id),c=readShopCart(),quantity=Number(f.get('quantity')),size=f.get('size'),note=f.get('note'),old=c.items.find(i=>i.item_id===id&&i.size===size&&i.note===note&&i.revision===p.revision);if(old&&old.quantity+quantity>20){toast('同じ商品の数量は20点までです。');return;}if(!old&&c.items.length>=30){toast('カートは30種類までです。');return;}if(old)old.quantity+=quantity;else c.items.push({item_id:id,revision:p.revision,title:p.title,size,quantity,note,unit_price:p.amount});c.token=crypto.randomUUID();writeShopCart(c);toast('カートに追加しました。ほかの商品も続けて追加できます。');}
function changeShopCart(index,value){const qty=Number(value);if(!Number.isInteger(qty)||qty<1||qty>20){toast('数量は1〜20点で入力してください。');document.querySelector('#shop-cart-panel').innerHTML=shopCartPanel();return;}const c=readShopCart();c.items[index].quantity=qty;c.token=crypto.randomUUID();writeShopCart(c);}
function removeShopCart(index){const c=readShopCart();c.items.splice(index,1);c.token=crypto.randomUUID();writeShopCart(c);}
function confirmShopCart(){const c=readShopCart();if(!c.items.length)return;const items=c.items.map(i=>({...i,subtotal:i.unit_price*i.quantity}));shopDraft={items,token:c.token,member:user.id};modal('カートのご注文内容を確認',shopSummary({items,total:items.reduce((n,i)=>n+i.subtotal,0)})+`<p><strong>支払い方法：現金</strong></p><p class="hint">コーチに購入金額をお渡しください。</p><p class="hint">デモ注文です。実際の発送や請求はありません。</p><div class="error" role="alert"></div><div class="dialog-actions"><button class="outline" onclick="$('#modal').close()">カートを修正する</button><button class="lime" onclick="startShopCheckout(this)">購入する</button></div>`);}
async function startShopCheckout(button){button.disabled=true;try{if(shopDraft.member!==user.id)throw Error('お子さまを切り替えたため、注文内容を確認し直してください。');await api('shop_order',shopDraft);if(readShopCart().token===shopDraft.token)writeShopCart({items:[],token:crypto.randomUUID()});$('#modal').close();await refresh();toast('購入を受け付けました。購入履歴でご確認いただけます。');}catch(e){$('#modal .error').textContent=e.message;button.disabled=false;}}
const shopHistoryPeriods=new Map(),shopHistorySchoolGroups=new Map();
function shopHistoryKey(staff){return `${user.id}:${staff?'staff':'member'}`;}
function shopHistoryRange(period,now=new Date()){const year=now.getFullYear(),month=now.getMonth();if(period==='recent')return {start:new Date(year,month-2,1),end:new Date(year,month+1,1)};const fiscal=Number(period);return {start:new Date(fiscal,3,1),end:new Date(fiscal+1,3,1)};}
function shopHistoryDate(value){const m=String(value||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return m?new Date(Number(m[1]),Number(m[2])-1,Number(m[3])):null;}
function shopHistoryRows(staff,now=new Date()){const period=shopHistoryPeriods.get(shopHistoryKey(staff))||'recent',range=shopHistoryRange(period,now);return (data.shop?.orders||[]).filter(o=>{const date=shopHistoryDate(o.created);const group=staff?(shopHistorySchoolGroups.get(shopHistoryKey(staff))||'all'):'all',grade=o.grade||(data.users||[]).find(u=>u.id===o.user_id)?.grade||'';return date&&date>=range.start&&date<range.end&&(group==='all'||(group==='elementary'?/小学/.test(grade):/中学/.test(grade)));});}
function shopOrderHistory(staff){const now=new Date(),currentYear=now.getFullYear()-(now.getMonth()<3?1:0),period=shopHistoryPeriods.get(shopHistoryKey(staff))||'recent',years=new Set([currentYear]);for(const o of data.shop?.orders||[]){const d=shopHistoryDate(o.created);if(d)years.add(d.getFullYear()-(d.getMonth()<3?1:0));}for(let year=Math.min(2026,...years);year<=currentYear;year++)years.add(year);if(period!=='recent')years.add(Number(period));const range=shopHistoryRange(period,now),end=new Date(range.end.getTime()-1),label=d=>`${d.getFullYear()}年${d.getMonth()+1}月`;return `<div class="shop-history-filter"><div class="shop-history-filter-row"><label class="field">注文履歴の表示期間<select onchange="changeShopHistoryPeriod(this,${staff})"><option value="recent" ${period==='recent'?'selected':''}>直近3か月（今月を含む）</option>${[...years].sort((a,b)=>b-a).map(y=>`<option value="${y}" ${String(y)===period?'selected':''}>${y}年度（${y}年4月〜${y+1}年3月）</option>`).join('')}</select></label>${staff?`<label class="field">会員区分<select onchange="changeShopHistorySchoolGroup(this)">${[['all','全て'],['elementary','小学生'],['junior','中学生']].map(([v,t])=>`<option value="${v}" ${(shopHistorySchoolGroups.get(shopHistoryKey(true))||'all')===v?'selected':''}>${t}</option>`).join('')}</select></label>`:''}</div><p class="hint">${label(range.start)}〜${label(end)}の注文</p></div><div class="shop-history-orders">${shopOrderHistoryCards(staff)}</div>`;}
function changeShopHistoryPeriod(select,staff){shopHistoryPeriods.set(shopHistoryKey(staff),select.value);const area=select.closest(staff?'.service-admin-content':'.shop-history-content');area.innerHTML=(staff?'':'<h2>ご注文・支払い履歴</h2>')+shopOrderHistory(staff);}
function shopOrderHistoryCards(staff){return [...shopHistoryRows(staff)].sort((a,b)=>String(b.created||'').localeCompare(String(a.created||''))).map(o=>`<article class="card shop-order"><div class="toolbar"><strong>${staff?esc(o.name)+' ／ ':''}${esc(o.created)}</strong><span class="tag">${o.delivered_at?'全商品受け渡し完了':o.deliveries?.some(line=>line.quantity>0)?'一部受け渡し':'未受け渡し'}</span></div>${staff?'':`<p>注文合計 ¥${o.body.total.toLocaleString()} ／ 現金でお支払い</p>`}${(o.body.items||[o.body]).map((item,i)=>{const line=o.deliveries?.[i]||{quantity:0,note:'',revision:0,cash_received:0},editable=staff&&adminCan('shop-admin',true);return `<section class="shop-delivery-line"><h3 class="shop-item-heading"><span aria-hidden="true">${shopIcon(item.title)}</span> ${esc(shopTitle(item.title))}</h3>${editable?`<div class="shop-fulfillment-scroll"><div class="shop-fulfillment-row"><p>${esc(item.size)} ／ 注文 ${item.quantity}点 ／ ¥${item.subtotal.toLocaleString()}</p><label class="shop-check"><span>受け渡し完了</span><input type="checkbox" class="delivery-complete" ${line.quantity===item.quantity?'checked':''} onchange="saveShopLine('${o.id}',${i},${line.revision},this.checked?${item.quantity}:0,this)"></label><label class="field"><span>渡した数量（累計）</span><select class="delivery-quantity">${Array.from({length:item.quantity+1},(_,n)=>`<option value="${n}" ${n===line.quantity?'selected':''}>${n}点</option>`).join('')}</select></label><label class="field"><span>受け渡しコメント</span><input class="delivery-note" maxlength="2000" value="${esc(line.note)}" placeholder="例：3点中1点を渡しました"></label></div></div>`:`<div class="shop-member-item-status"><span>${esc(item.size)} ／ 注文 ${item.quantity}点 ／ ¥${item.subtotal.toLocaleString()}</span><span class="tag ${line.quantity===item.quantity?'':'shop-delivery-pending'}">${line.quantity===item.quantity?'受け渡し完了':line.quantity>0?`一部受け取り（${item.quantity}点中${line.quantity}点受け渡し済み）`:'未受け渡し'}</span></div>`}${item.note?`<p>注文時の連絡：${esc(item.note)}</p>`:''}<p><b>受け渡し済み ${line.quantity}点 ／ 残り ${item.quantity-line.quantity}点</b></p><div class="shop-cash-row"><strong>現金徴収額（この商品の合計）：¥${item.subtotal.toLocaleString()}</strong>${editable?`<label class="shop-cash-check"><input type="checkbox" class="delivery-cash" ${line.cash_received?'checked':''} onchange="saveShopLine('${o.id}',${i},${line.revision},null,this)">受け取り済み</label>`:`<span class="tag ${!staff&&!line.cash_received?'shop-cash-unreceived':''}">${line.cash_received?'受け取り済み':'未受け取り'}</span>`}</div>${editable?`<button class="outline" onclick="saveShopLine('${o.id}',${i},${line.revision},null,this)">数量・コメントを保存</button>`:line.note?`<p>受け渡しコメント：${esc(line.note)}</p>`:''}<p class="hint">${esc(line.updated||'')}</p></section>`}).join('')}</article>`).join('')||'<div class="card">この期間の注文はありません。</div>';}
async function saveShopLine(id,line_index,revision,completeQuantity,button){const root=button.closest('.shop-delivery-line'),quantity=completeQuantity===null?Number(root.querySelector('.delivery-quantity').value):completeQuantity,note=root.querySelector('.delivery-note').value,cash_received=root.querySelector('.delivery-cash').checked;button.disabled=true;try{await api('shop_delivery',{id,line_index,revision,quantity,note,cash_received});data=await api('data');renderEditToken=data.edit_token||'';const area=document.querySelector('.shop-order-admin-history .service-admin-content');if(area)area.innerHTML=shopOrderHistory(true);toast(completeQuantity===0?'未受け渡しに戻しました。':'商品の受け渡し・現金の受け取り状況を保存しました。');}catch(e){toast(e.message);button.disabled=false;if(button.type==='checkbox')button.checked=!button.checked;}}
function shopAdmin(){return `<details class="card shop-order-admin-history"><summary><b>物販の注文・支払い一覧</b></summary><div class="service-admin-content">${shopOrderHistory(true)}</div></details>`;}
function shopProductForm(id=''){const p=data.shop?.products.find(p=>p.id===id)||{sizes:['フリー'],images:[]};modal('物販商品を編集',`<form onsubmit="saveShopProduct(event,'${id}')">${field('商品名','title',shopTitle(p.title))}${field('税込金額（1点・円）','amount',p.amount||0,'number')}<label class="field">商品説明<textarea name="body" maxlength="4000">${esc(p.body||'')}</textarea></label>${field('サイズ・種類（カンマ区切り）','sizes',p.sizes.join(','))}<fieldset><legend>登録済み写真（残すものにチェック）</legend><div class="shop-edit-photos">${p.images.map(url=>`<label><img src="${esc(url)}" alt="登録済み写真"><input type="checkbox" name="keep" value="${esc(url)}" checked>残す</label>`).join('')||'写真は未登録です。'}</div></fieldset><label class="field">商品写真を追加（複数選択可）<input name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><p class="hint">JPEG・PNG・WebP、1枚5MB以下、合計30枚まで。1枚目をメイン写真に表示します。登録済みの写真はチェックを外すと商品から取り除けます。</p><div class="error" role="alert"></div><button class="lime">商品を保存</button></form>`);}
async function saveShopProduct(ev,id){ev.preventDefault();const form=ev.target,b=ev.submitter,f=new FormData(form);b.disabled=true;try{const keep=f.getAll('keep'),files=[...form.elements.photos.files],uploads=[];if(keep.length+files.length>30)throw Error('写真は合計30枚までです。');for(const file of files){if(file.size>5*1024*1024)throw Error('写真は1枚5MB以下にしてください。');uploads.push({content:await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=()=>reject(Error('写真を読み込めません。'));r.readAsDataURL(file);})});}await api('shop_product',{id,title:f.get('title'),body:f.get('body'),amount:Number(f.get('amount')),sizes:f.get('sizes').split(/[,、\n]/).map(s=>s.trim()).filter(Boolean),keep,uploads});$('#modal').close();await refresh();toast('商品・写真を保存しました。');}catch(e){form.querySelector('.error').textContent=e.message;}finally{b.disabled=false;}}

async function setShopDelivery(id,completed,button){button.disabled=true;try{await api('shop_delivery',{id,completed});data=await api('data');renderEditToken=data.edit_token||'';const area=document.querySelector('.shop-order-admin-history .service-admin-content');if(area)area.innerHTML=shopOrderHistory(true);toast(completed?'受け渡し完了を保存しました。':'未受け渡しに戻しました。');}catch(e){toast(e.message);button.disabled=false;}}

function changeShopHistorySchoolGroup(select){shopHistorySchoolGroups.set(shopHistoryKey(true),select.value);select.closest('.service-admin-content').innerHTML=shopOrderHistory(true);}
