const expenseCategories=['備品費','会場費','交通費','大会参加費','消耗品費','通信費','保険料','その他支出'];
function privateFiles(files){return (files||[]).map(f=>`<a class="btn outline small" href="/basketball-club/api/submission_file?id=${encodeURIComponent(f.id)}&member=${encodeURIComponent(selectedMember||user?.id||'')}">${esc(f.name)}</a>`).join(' ');}
function submissionUploadField(){return '<label class="field">PDF・写真（任意、合計30件まで・1件5MB以下）<input type="file" name="attachments" accept=".pdf,.jpg,.jpeg,.png,.webp" multiple></label>';}
async function submissionUploads(form){const files=[...form.querySelector('[name=attachments]').files];if(files.length>30||files.some(f=>f.size>5*1024*1024))throw Error('添付は30件まで・1件5MB以下にしてください。');return Promise.all(files.map(file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({name:file.name,content:r.result.split(',')[1]});r.onerror=()=>reject(Error('添付を読み込めません。'));r.readAsDataURL(file);})))}
function worksheetPage(){const own=user.role==='member',edit=user.role==='coach'||adminCan('worksheets',true),ws=data.worksheets;return heading('ワークシート','練習を振り返り、次の目標を記録します。')+`<div class="toolbar">${own?'<button class="lime" onclick="worksheetForm()">＋ ワークシートを提出</button>':''}${user.role==='admin'&&edit?'<button class="outline" onclick="worksheetTemplateForm()">質問・選択肢を編集</button>':''}<a class="btn outline" href="/basketball-club/api/worksheet_excel?member=${encodeURIComponent(selectedMember||user.id)}">Excelをダウンロード</a></div>${!own?'<p class="hint">提出・確認の変更を data / ワークシート.xlsx に自動保存します。</p>':''}${ws.rows.map(r=>`<article class="card"><h2>${esc(r.title)}</h2><p>${esc(r.name)} ／ ${esc(r.grade)} ／ ${esc(r.updated.slice(0,10))} <span class="tag ${r.reviewed?'':'gray'}">${r.reviewed?'確認済み':'未確認'}</span></p><div class="worksheet-answers">${JSON.parse(r.answers||'[]').map(a=>`<p><b>${esc(a.label)}</b><br>${esc(a.value)}</p>`).join('')}</div><p style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(r.body)}</p><div class="toolbar">${privateFiles(r.files)}</div><div class="toolbar">${own?`<button class="outline" onclick="worksheetForm('${r.id}')">編集</button><button class="outline danger" onclick="deleteWorksheet('${r.id}')">削除</button>`:edit?`<button class="${r.reviewed?'outline':'lime'}" onclick="reviewWorksheet('${r.id}',${!r.reviewed},this)">${r.reviewed?'未確認に戻す':'確認済みにする'}</button>`:''}</div></article>`).join('')||'<p class="card">まだ提出はありません。</p>'}`;}
function worksheetForm(id=''){const r=data.worksheets.rows.find(r=>r.id===id)||{},t=data.worksheets.template,answers=Object.fromEntries(JSON.parse(r.answers||'[]').map(a=>[a.id,a.value]));modal(id?'ワークシートを編集':'ワークシートを提出',`<form onsubmit="saveWorksheet(event,'${id}',${r.revision||0},${t.revision})">${field('タイトル','title',r.title||new Date().toLocaleDateString('sv-SE')+'の振り返り')}${t.questions.map(q=>selectField(q.label,'answer_'+q.id,[['','選んでください'],...q.options.map(o=>[o,o])],answers[q.id]||'')).join('')}<label class="field">振り返り・次回の目標<textarea name="body" maxlength="10000">${esc(r.body||'')}</textarea></label>${privateFiles(r.files)}${submissionUploadField()}<p class="hint">内容を変更して提出すると、確認状態は未確認に戻ります。</p><div class="error" role="alert"></div><button class="lime">提出する</button></form>`);}
async function saveWorksheet(ev,id,revision,template_revision){ev.preventDefault();ev.submitter.disabled=true;try{const f=new FormData(ev.target);const result=await api('worksheet',{id,revision,template_revision,title:f.get('title'),body:f.get('body'),answers:Object.fromEntries(data.worksheets.template.questions.map(q=>[q.id,f.get('answer_'+q.id)])),uploads:await submissionUploads(ev.target)});$('#modal').close();await refresh();toast(result.archive_error||'提出しました。');}catch(e){ev.target.querySelector('.error').textContent=e.message;}finally{ev.submitter.disabled=false;}}
async function reviewWorksheet(id,reviewed,button){const r=data.worksheets.rows.find(r=>r.id===id);button.disabled=true;try{const res=await api('worksheet',{id,revision:r.revision,action:'review',reviewed});await refresh();toast(res.archive_error||(reviewed?'確認済みにしました。':'未確認に戻しました。'));}catch(e){toast(e.message);button.disabled=false;}}
async function deleteWorksheet(id){if(!confirm('このワークシートを削除しますか？'))return;const r=data.worksheets.rows.find(r=>r.id===id);try{const res=await api('worksheet',{id,revision:r.revision,delete:true});await refresh();toast(res.archive_error||'削除しました。');}catch(e){toast(e.message);}}
function worksheetQuestionEditor(q={id:crypto.randomUUID(),label:'',options:['できた','少しできた','これから']} ){return `<fieldset class="worksheet-question" data-id="${esc(q.id)}">${field('質問','question',q.label)}<label class="field">選択肢（1行に1つ）<textarea name="options">${esc(q.options.join('\n'))}</textarea></label><button type="button" class="outline danger" onclick="this.closest('fieldset').remove()">この質問を削除</button></fieldset>`;}
function worksheetTemplateForm(){const t=data.worksheets.template;modal('ワークシートの質問・選択肢',`<form onsubmit="saveWorksheetTemplate(event,${t.revision})"><p>変更は次の提出・編集に適用します。提出済みの回答には当時の質問を残します。</p><p class="hint">参考：<a href="https://www.pref.kanagawa.jp/documents/12026/858619.pdf" target="_blank" rel="noopener">神奈川県のバスケットボール学習カード</a>を参考にした仮の質問です。</p><div id="worksheet-questions">${t.questions.map(worksheetQuestionEditor).join('')}</div><div class="toolbar"><button type="button" class="outline" onclick="document.getElementById('worksheet-questions').insertAdjacentHTML('beforeend',worksheetQuestionEditor())">質問を追加</button><button class="lime">質問を保存</button></div><div class="error" role="alert"></div></form>`);}
async function saveWorksheetTemplate(ev,revision){ev.preventDefault();try{const questions=[...ev.target.querySelectorAll('.worksheet-question')].map(el=>({id:el.dataset.id,label:el.querySelector('[name=question]').value.trim(),options:el.querySelector('[name=options]').value.split('\n').map(x=>x.trim()).filter(Boolean)}));await api('worksheet',{action:'template',revision,questions});$('#modal').close();await refresh();toast('質問を保存しました。');}catch(e){ev.target.querySelector('.error').textContent=e.message;}}
function memberFinancePage(){return heading('会計へ報告','レシート写真・PDFと支出内容を会計担当者へ提出します。')+`<button class="lime" onclick="memberFinanceForm()">＋ 会計に報告する</button><p class="hint">確認済みは会計担当者が内容を確認した状態です。精算・返金済みを意味しません。</p>${(data.finance_reports||[]).map(r=>`<article class="card"><span class="tag">${esc(r.account_type||'一般会計')}</span><h2>${esc(r.category)} ／ ${financeMoney(r.amount)}</h2><p>${esc(r.date)} <span class="tag">${esc(r.status)}</span></p><p style="white-space:pre-wrap">${esc(r.note)}</p><div class="toolbar">${privateFiles(r.files)}</div></article>`).join('')||'<p class="card">まだ報告はありません。</p>'}`;}
function memberFinanceForm(){modal('会計に報告する',`<form onsubmit="submitMemberFinance(event)">${selectField('会計区分','account_type',financeAccountTypes,'一般会計')}<div class="form-grid">${field('購入・支払日','date',new Date().toLocaleDateString('sv-SE'),'date')}${selectField('費目','category',[['','選んでください'],...expenseCategories.map(c=>[c,c])],'')}${field('金額（円）','amount','','number')}</div><label class="field">内容・備考<textarea name="note" maxlength="3000"></textarea></label>${submissionUploadField().replace('（任意、','（必須、')}<div class="error" role="alert"></div><button class="lime">会計に提出</button></form>`);}
async function submitMemberFinance(ev){ev.preventDefault();ev.submitter.disabled=true;try{const f=new FormData(ev.target);await api('member_finance_report',{account_type:f.get('account_type'),date:f.get('date'),category:f.get('category'),amount:f.get('amount')===''?null:Number(f.get('amount')),note:f.get('note'),uploads:await submissionUploads(ev.target)});$('#modal').close();await refresh();toast('会計に提出しました。');}catch(e){ev.target.querySelector('.error').textContent=e.message;}finally{ev.submitter.disabled=false;}}
function financeMemberReports(f,edit){return `<details class="card"><summary><b>会員からの会計報告（未確認 ${f.member_reports.filter(r=>r.status==='未確認').length}件）</b></summary><p class="hint">報告は自動計上されません。内容を確認後、必要なものを「明細を追加」から収支に登録してください。</p>${f.member_reports.map(r=>`<article class="staff-work-entry"><span class="tag">${esc(r.account_type||'一般会計')}</span><h3>${esc(r.name)} ／ ${esc(r.category)} ／ ${financeMoney(r.amount)}</h3><p>${esc(r.date)} <span class="tag">${esc(r.status)}</span></p><p style="white-space:pre-wrap">${esc(r.note)}</p><div class="toolbar">${privateFiles(r.files)}${edit?`<button class="outline" onclick="reviewFinanceMember('${r.id}',this)">${r.status==='未確認'?'確認済みにする':'未確認に戻す'}</button>`:''}</div></article>`).join('')||'<p>報告はありません。</p>'}</details>`;}
async function reviewFinanceMember(id,button){button.disabled=true;const r=data.finance.member_reports.find(r=>r.id===id);try{await api('finance_member_review',{id,revision:r.revision,status:r.status==='未確認'?'確認済み':'未確認'});await changeFinanceYear(data.finance.year);}catch(e){toast(e.message);button.disabled=false;}}
function displayedStaff(){const published=pub.staff_intros||[];if(published.length)return published;return [
{name:'コーチA',classes:['男子A'],referee:'あり',comment:'一人ひとりの挑戦を大切に、基礎から丁寧にサポートします。'},
{name:'コーチB',classes:['男子B'],referee:'なし',comment:'バスケットボールの楽しさを感じながら、できることを一緒に増やしていきましょう。'},
{name:'コーチC',classes:['女子A'],referee:'あり',comment:'仲間との声かけを大切に、自分で考えてプレーする力を育てます。'},
{name:'コーチD',classes:['女子B'],referee:'なし',comment:'初めての選手も安心して参加できるよう、楽しく練習できる環境をつくります。'},
{name:'コーチE',classes:['U15A','U15B'],referee:'あり',comment:'目標に向けた練習と振り返りを通して、選手の成長を支えます。'}
].map(s=>({...s,sample:true}));}
function publicStaffCards(rows=displayedStaff()){return rows.map(s=>`<article class="public-staff-card"><img src="${s.sample?'/basketball-club/uploads/00000000000000000000000000000003.jpg':'/basketball-club/staff-photo?id='+encodeURIComponent(s.photo)}" alt="${s.sample?'活動写真（仮）':esc(s.name)}" loading="lazy"><div>${s.sample?'<span class="tag">紹介サンプル・写真は仮</span>':''}<h3>${esc(s.name)}</h3><p class="staff-comment">${esc(s.comment)}</p><p><b>担当クラス</b><br>${s.classes.map(c=>`<span class="tag">${esc(c)}</span>`).join(' ')}</p><p><b>審判資格：</b>${esc(s.referee||'未設定')}</p></div></article>`).join('');}
function publicStaffSection(){const rows=displayedStaff();return `<section class="section wrap" id="staff-introduction"><div class="section-title"><div><div class="eng">OUR STAFF</div><h2>スタッフ紹介</h2></div><div class="staff-carousel-controls"><button type="button" class="outline small" aria-label="前のコーチ" onclick="scrollStaffCarousel(-1)">←</button><button type="button" class="outline small" aria-label="次のコーチ" onclick="scrollStaffCarousel(1)">→</button></div></div>${rows[0]?.sample?'<p class="hint">掲載イメージです。名前・紹介文・担当クラス・資格はサンプルで、写真は仮の活動写真です。</p>':''}<div class="staff-carousel" id="staff-carousel" onscroll="syncStaffScroll(this)" tabindex="0" role="region" aria-label="コーチ紹介。左右にスクロールできます">${publicStaffCards(rows.slice(0,4))}</div><div class="staff-mobile-scroll"><input type="range" min="0" max="100" step="0.1" value="0" aria-label="スタッフ紹介の横スクロール" oninput="setStaffScroll(this.value)"></div>${rows.length>=5?'<p class="staff-see-all"><a class="btn outline" href="#all-staff">他のスタッフを見る</a></p>':''}</section>`;}
function scrollStaffCarousel(direction){const track=document.getElementById('staff-carousel'),card=track?.querySelector('.public-staff-card');if(track&&card)track.scrollBy({left:direction*(card.getBoundingClientRect().width+24),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}
function staffIntroductionPage(){$('#app').innerHTML=header()+`<main class="section wrap staff-introduction-page"><a class="text-link staff-back-link" href="#home">トップページへ戻る</a><div class="page-heading"><div><div class="eng">OUR STAFF</div><h1>スタッフ紹介</h1><p>選手の成長を支えるスタッフと、担当クラスをご紹介します。</p></div></div>${displayedStaff()[0]?.sample?'<p class="hint">以下は紹介サンプルです。写真は仮の活動写真です。</p>':''}<div class="public-staff-grid">${publicStaffCards()}</div><div class="staff-bottom-home"><a class="btn outline" href="#home">トップページへ戻る</a></div></main>`;window.scrollTo(0,0);}
function staffIntroManagement(){return `<section class="card"><h2>公開サイトのスタッフ紹介</h2><p>掲載する写真・担当クラス・コメントを設定します。</p><button class="lime" onclick="staffIntroForm()">＋ スタッフ紹介を追加</button>${(data.staff_intros||[]).map(s=>`<div class="staff-work-entry"><b>${esc(s.name)}</b> <span class="tag">${s.published?'公開中':'下書き'}</span><p>${s.classes.map(esc).join('・')}</p><div class="toolbar"><button class="outline" onclick="staffIntroForm('${s.id}')">編集</button><button class="outline danger" onclick="deleteStaffIntro('${s.id}')">削除</button></div></div>`).join('')}</section>`;}
function staffIntroForMember(uid){const s=(data.staff_intros||[]).find(s=>s.staff_id===uid);staffIntroForm(s?.id||'',uid);}
function staffIntroForm(id='',uid=''){const person=data.users.find(u=>u.id===uid);const s=(data.staff_intros||[]).find(s=>s.id===id)||{name:person?.name||'',staff_id:uid,classes:staffAssignmentGroups.filter(g=>(person?.grade||'').includes(g)),position:0};modal('スタッフ紹介を編集',`<form onsubmit="saveStaffIntro(event,'${id}','${esc(s.staff_id||uid)}')">${field('掲載名','name',s.name||'')}<fieldset><legend>担当クラス（複数選択可）</legend>${staffAssignmentGroups.map(c=>`<label class="check-row"><input type="checkbox" name="classes" value="${c}" ${s.classes.includes(c)?'checked':''}>${c}</label>`).join('')}</fieldset>${selectField('審判資格','referee',[['','選んでください'],['あり','あり'],['なし','なし']],s.referee||'')}<label class="field">コメント<textarea name="comment" maxlength="2000">${esc(s.comment||'')}</textarea></label><label class="field">スタッフの写真（5MB以下）<input name="attachments" type="file" accept=".jpg,.jpeg,.png,.webp"></label>${s.photo?'<p class="hint">登録済み写真があります。写真を選ぶと差し替えます。</p>':''}${field('表示順（小さい順）','position',s.position,'number')}${selectField('公開状態','published',[['0','下書き'],['1','公開する']],s.published?'1':'0')}<p class="hint">公開するとログインせずに閲覧できます。掲載してよい写真・コメントを登録してください。</p><div class="error" role="alert"></div><div class="toolbar">${id?`<button type="button" class="outline danger" onclick="deleteStaffIntro('${id}')">紹介を削除</button>`:''}<button class="lime">保存する</button></div></form>`);}
async function saveStaffIntro(ev,id,staff_id){ev.preventDefault();ev.submitter.disabled=true;try{const f=new FormData(ev.target),s=data.staff_intros?.find(s=>s.id===id);await api('staff_intro',{id,revision:s?.revision,staff_id,referee:f.get('referee'),name:f.get('name'),classes:f.getAll('classes'),comment:f.get('comment'),position:Number(f.get('position')),published:f.get('published')==='1',photo:(await submissionUploads(ev.target))[0]});$('#modal').close();await refresh();toast('スタッフ紹介を保存しました。');}catch(e){ev.target.querySelector('.error').textContent=e.message;}finally{ev.submitter.disabled=false;}}
async function deleteStaffIntro(id){if(!confirm('このスタッフ紹介を削除しますか？'))return;const s=data.staff_intros.find(s=>s.id===id);try{await api('staff_intro',{id,revision:s.revision,delete:true});$('#modal').close();await refresh();}catch(e){toast(e.message);}}
function mikitivSection(){const c=pub.content,photo=c.conditioning_photo||c.gallery||c.hero;return `<section class="section wrap" id="other-activities"><div class="section-title"><div><div class="eng">OTHER ACTIVITIES</div><h2>その他の活動</h2></div></div><div class="activities-carousel" id="activities-carousel" onscroll="syncActivityScroll(this)" tabindex="0" role="region" aria-label="その他の活動。左右にスクロールできます"><article class="conditioning-coach-card"><span class="tag conditioning-category">${esc(c.conditioning_category)}</span>${photo?`<img src="${esc(photo)}" alt="${c.conditioning_photo?'廣田梨恵コーチ':'仮の活動写真'}" loading="lazy">`:'<div class="conditioning-no-image" role="img" aria-label="廣田コーチの写真は準備中"><span>NO IMAGE</span><small>写真準備中</small></div>'}<div class="conditioning-coach-description">${!c.conditioning_photo&&photo?'<p class="hint">仮の活動写真です。</p>':''}<h3>${esc(c.conditioning_title)}</h3><p>${esc(c.conditioning_title)}も月1回開催しています。</p><h4>${esc(c.conditioning_name)}</h4><p>${esc(c.conditioning_comment)}</p><p>${esc(c.conditioning_contact)}</p><div class="social">${social(c.conditioning_instagram,'Instagram')}</div></div></article><article class="mikitiv-activity-card"><span class="tag">${esc(c.mikitiv_category)}</span><h3>${esc(c.mikitiv_title)}</h3><p>${esc(c.mikitiv_intro)}</p><h4>${esc(c.mikitiv_heading)}</h4><p>${esc(c.mikitiv_description)}</p><div class="mikitiv-links"><a class="text-link" href="${esc(c.mikitiv_url)}" target="_blank" rel="noopener noreferrer">みきティブについて</a><a class="text-link" href="${esc(c.mikitiv_clubs_url)}" target="_blank" rel="noopener noreferrer">認定クラブ一覧を見る</a></div></article></div><div class="activities-scroll-controls"><input type="range" min="0" max="100" step="0.1" value="0" aria-label="その他の活動の横スクロール" oninput="setActivityScroll(this.value)"></div></section>`;}
let attendanceRateMember='',attendanceRateMonth='',attendanceRateData=null,attendanceRateKey='',attendanceRateLoading=false;
function attendanceRatesPage(){const key=JSON.stringify([user.id,attendanceRateMember,attendanceRateMonth]),query='member='+encodeURIComponent(attendanceRateMember)+'&month='+encodeURIComponent(attendanceRateMonth);if(attendanceRateKey!==key&&!attendanceRateLoading){attendanceRateLoading=true;api('attendance_rates?'+query).then(result=>{attendanceRateData=result;attendanceRateKey=key;attendanceRateLoading=false;if(page==='attendance-rates')dashboard();}).catch(e=>{attendanceRateLoading=false;toast(e.message);});}const rows=attendanceRateKey===key?attendanceRateData.rows:[],people=data.users.filter(u=>u.role==='member');return heading('出席率','実際の出欠をもとに、会員ごとの出席率を確認できます。')+`<div class="card form-grid"><label class="field">会員名<select onchange="attendanceRateMember=this.value;dashboard()"><option value="">すべて</option>${people.map(m=>`<option value="${esc(m.id)}" ${m.id===attendanceRateMember?'selected':''}>${esc(m.name)}</option>`).join('')}</select></label><div class="field"><span>対象月（複数選択可・未選択は全期間）</span><button type="button" class="outline" onclick="openAttendanceMonths()">対象月を選択</button><div class="toolbar">${attendanceRateMonth?attendanceRateMonth.split(',').map(m=>`<button type="button" class="outline small" data-month="${esc(m)}" onclick="removeAttendanceRateMonth(this.dataset.month)">${esc(m)} ×</button>`).join(''):'<span>全期間</span>'}${attendanceRateMonth?'<button class="outline small" onclick="clearAttendanceRateMonths()">全期間に戻す</button>':''}</div></div></div><p class="hint">実際の出欠を確認済みの回数（遅刻・早退を含む）。未確認と未来の予定は出席率に含めません。</p><div class="toolbar attendance-rate-actions"><a class="btn rate-csv" href="/basketball-club/api/attendance_rates_export?format=csv&${query}"><span>CSVを</span><span>ダウンロード</span></a><a class="btn rate-pdf" href="/basketball-club/api/attendance_rates_export?format=pdf&${query}"><span>PDFを</span><span>ダウンロード</span></a><button class="rate-refresh" onclick="attendanceRateKey='';dashboard()"><span>最新の状況に</span><span>更新</span></button></div><p class="hint">出席率は自動更新されます。ボタンを押すと、最新の出欠から集計をすぐに読み直します。</p><div class="card">${rows.map(r=>`<div class="attendance-rate-row"><b>${esc(r.name)} <small>${esc(r.grade)}</small></b><div class="attendance-rate-track" role="img" aria-label="${esc(r.name)}の出席率 ${r.rate??'未集計'}${r.rate===null?'':'%'}"><span style="width:${r.rate||0}%"></span></div><strong>${r.rate===null?'未集計':r.rate+'%'}</strong><p>出席 ${r.present}回 ／ 欠席 ${r.absent}回 ／ 未確認 ${r.unconfirmed}回</p></div>`).join('')||'<p>読み込み中、または該当する会員がいません。</p>'}</div><details class="card"><summary><b>ローカルExcelから読み込む</b></summary><p>このデモを動かしているPCの「data / 出欠入力.xlsx」で「実際の出欠」を編集して保存すると、約5秒ごとに自動で読み込み、Web画面にも反映します。会員ID・日程IDは変更しないでください。</p><p>出席・欠席・遅刻・早退・遅刻・早退・未確認を入力できます。行の削除では記録を削除しません。</p><p class="hint">${esc(attendanceRateData?.status?.message||'入力待ち')}</p></details>`;}


let basketNoteMember='';
function basketNotesPage(){const n=data.basket_notes||{rows:[],members:[]},own=user.role==='member',edit=user.role==='coach'||adminCan('basket-notes',true),members=n.members.filter(m=>!basketNoteMember||m.id===basketNoteMember),rows=n.rows.filter(r=>!basketNoteMember||r.user_id===basketNoteMember);return heading('バスケノート',own?(n.members[0]?.group||'')+'用のバスケノート':'実際に出席した活動に対する提出状況')+`${own?'':`<label class="field">会員名<select onchange="basketNoteMember=this.value;dashboard()"><option value="">すべて</option>${n.members.map(m=>`<option value="${esc(m.id)}" ${m.id===basketNoteMember?'selected':''}>${esc(m.name)}（${m.group}）</option>`).join('')}</select></label>`}<div class="card"><p>学年と活動内容に合ったノートを記入できます。</p><p class="hint">提出率＝提出済みの日数 ÷ 実際に出席した日数。同日に複数の活動がある場合も1日として集計します。遅刻・早退を含み、未確認・欠席・未来の予定は除外します。</p>${members.map(m=>`<p><b>${esc(m.name)}</b>　${m.submitted} / ${m.attended}日　<strong>${m.rate===null?'未集計':m.rate+'%'}</strong></p>`).join('')}</div>${rows.map(r=>`<article class="card"><b>${esc(r.name)} ／ ${esc(r.date)} ／ ${esc(r.title)}</b><p><span class="tag">${esc(r.submission_status||(r.submitted?'提出':'未提出'))}</span></p><div class="toolbar">${true?`<button class="outline" data-user="${esc(r.user_id)}" data-event="${esc(r.event_id)}" onclick="basketNoteForm(this)">${own?'ノートを書く・編集':'内容を見る・コメント'}</button>`:''}${!own&&edit?`<button class="outline" data-user="${esc(r.user_id)}" data-event="${esc(r.event_id)}" onclick="markBasketNote(this)">${r.submitted?'未提出に戻す':'提出済みにする'}</button>`:''}</div></article>`).join('')||'<p>対象の出席記録はありません。</p>'}`;}
async function markBasketNote(button){const r=data.basket_notes.rows.find(r=>r.user_id===button.dataset.user&&r.event_id===button.dataset.event);button.disabled=true;try{await api('basket_note',{user_id:r.user_id,event_id:r.event_id,revision:r.revision,submitted:!r.submitted});await refresh();}catch(e){toast(e.message);button.disabled=false;}}
const noteText=(label,key,value='')=>`<label class="field">${label}<textarea name="${key}" maxlength="3000">${esc(value)}</textarea></label>`;
function noteTemplateKey(r){return (r.group==='低学年'?'low':'high')+(r.kind.includes('試合')?'-match':'-practice');}
function basketNoteForm(button){const r=data.basket_notes.rows.find(r=>r.user_id===button.dataset.user&&r.event_id===button.dataset.event),own=user.role==='member',edit=user.role==='coach'||adminCan('basket-notes',true);let saved={};try{saved=JSON.parse(r.body||'{}');}catch{}const t=own?data.basket_notes.templates[noteTemplateKey(r)]:saved.template||data.basket_notes.templates[noteTemplateKey(r)],answers=saved.answers||saved;modal(r.group+'・'+(r.kind.includes('試合')?'試合版':'練習版')+'バスケノート',`<p>${esc(r.name)} ／ ${esc(r.date)}（${'日月火水木金土'[new Date(r.date+'T12:00:00').getDay()]}）</p><form onsubmit="saveBasketNote(event,'${esc(r.user_id)}','${esc(r.event_id)}',${t.revision})"><fieldset ${own?'':'disabled'} class="note-input-fields">${t.fields.map(f=>f.type==='select'?selectField(f.label,'answer_'+f.id,[['','えらんでください'],...f.options.map(v=>[v,v])],answers[f.id]||''):f.type==='text'?field(f.label,'answer_'+f.id,answers[f.id]||'','text',false):noteText(f.label,'answer_'+f.id,answers[f.id]||'')).join('')}</fieldset>${t.feedback?(own?`<h3>⑤ コーチから</h3><p style="white-space:pre-wrap">${esc(r.feedback||'まだコメントはありません。')}</p>`:noteText('⑤ コーチから','feedback',r.feedback||'')):''}${own?'<p class="hint">保存後、コーチ・管理者が提出状況を確認します。</p><button class="lime">ノートを保存</button>':t.feedback&&edit?'<button class="lime">コメントを保存</button>':''}<div class="error" role="alert"></div></form>`);}
async function saveBasketNote(ev,user_id,event_id,template_revision){ev.preventDefault();const r=data.basket_notes.rows.find(r=>r.user_id===user_id&&r.event_id===event_id),f=new FormData(ev.target),own=user.role==='member';ev.submitter.disabled=true;try{await api('basket_note',{user_id,event_id,revision:r.revision,...(own?{template_revision,answers:Object.fromEntries([...f].filter(([k])=>k.startsWith('answer_')).map(([k,v])=>[k.slice(7),v]))}:{action:'feedback',feedback:f.get('feedback')})});$('#modal').close();await refresh();toast(own?'ノートを保存しました。':'コメントを保存しました。');}catch(e){ev.target.querySelector('.error').textContent=e.message;}finally{ev.submitter.disabled=false;}}
function noteTemplateSettingsPage(){return heading('バスケノート設定','管理者だけが質問・選択肢を編集できます。保存済みのノートには当時の質問を残します。')+['low','high'].map(g=>`<section class="card"><h2>${g==='low'?'低学年用（小学1〜3年）':'高学年用（小学4〜6年）'}</h2><div class="toolbar"><button class="outline" onclick="editNoteTemplate('${g}-practice')">練習版を編集</button><button class="outline" onclick="editNoteTemplate('${g}-match')">試合版を編集</button></div></section>`).join('')+'<p class="hint">年長用はありません。中学生用は今後追加できます。</p>';}
function noteFieldEditor(f={id:crypto.randomUUID(),label:'',type:'textarea',options:[]}){return `<fieldset class="worksheet-question" data-id="${esc(f.id)}">${field('項目名','label',f.label)}${selectField('入力形式','type',[['text','短い文章'],['textarea','長い文章'],['select','選択式']],f.type)}<label class="field">選択肢（選択式の場合、1行に1つ）<textarea name="options">${esc(f.options.join('\n'))}</textarea></label><div class="toolbar"><button type="button" class="outline" onclick="const row=this.closest('fieldset');if(row.previousElementSibling)row.previousElementSibling.before(row)">上へ</button><button type="button" class="outline" onclick="const row=this.closest('fieldset');if(row.nextElementSibling)row.nextElementSibling.after(row)">下へ</button><button type="button" class="outline danger" onclick="this.closest('fieldset').remove()">項目を削除</button></div></fieldset>`;}
function editNoteTemplate(key){const t=data.note_templates[key];modal((key.startsWith('low')?'低学年':'高学年')+'・'+(key.endsWith('match')?'試合版':'練習版')+'の項目を編集',`<form onsubmit="saveNoteTemplate(event,'${key}',${t.revision})"><div id="note-template-fields">${t.fields.map(noteFieldEditor).join('')}</div><label class="check-row"><input type="checkbox" name="feedback" ${t.feedback?'checked':''}>「コーチから」の欄を表示</label><div class="toolbar"><button type="button" class="outline" onclick="document.getElementById('note-template-fields').insertAdjacentHTML('beforeend',noteFieldEditor())">項目を追加</button><button class="lime">設定を保存</button></div><div class="error" role="alert"></div></form>`);}
async function saveNoteTemplate(ev,key,revision){ev.preventDefault();try{const fields=[...ev.target.querySelectorAll('.worksheet-question')].map(el=>({id:el.dataset.id,label:el.querySelector('[name=label]').value.trim(),type:el.querySelector('[name=type]').value,options:el.querySelector('[name=options]').value.split('\n').map(x=>x.trim()).filter(Boolean)}));await api('note_templates',{key,revision,fields,feedback:ev.target.elements.feedback.checked});$('#modal').close();await refresh();toast('ノートの項目を保存しました。');}catch(e){ev.target.querySelector('.error').textContent=e.message;}}

function addAttendanceRateMonth(month){if(!month)return;attendanceRateMonth=[...new Set([...attendanceRateMonth.split(',').filter(Boolean),month])].sort().join(',');dashboard();}
function removeAttendanceRateMonth(month){attendanceRateMonth=attendanceRateMonth.split(',').filter(m=>m!==month).join(',');dashboard();}
function clearAttendanceRateMonths(){attendanceRateMonth='';dashboard();}
setInterval(async()=>{if(page!=='attendance-rates'||!user||document.hidden||attendanceRateLoading||document.querySelector('#modal')?.open)return;const key=JSON.stringify([user.id,attendanceRateMember,attendanceRateMonth]);try{const fresh=await api('attendance_rates?member='+encodeURIComponent(attendanceRateMember)+'&month='+encodeURIComponent(attendanceRateMonth));if(page==='attendance-rates'&&key===JSON.stringify([user.id,attendanceRateMember,attendanceRateMonth])&&JSON.stringify(fresh)!==JSON.stringify(attendanceRateData)){attendanceRateData=fresh;attendanceRateKey=key;dashboard();}}catch(e){}},5000);

function scrollActivityCarousel(direction){const track=document.getElementById("activities-carousel"),card=track?.querySelector("article");if(track&&card)track.scrollBy({left:direction*(card.getBoundingClientRect().width+24),behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"});}

function setStaffScroll(value){const track=document.getElementById('staff-carousel');if(track)track.scrollLeft=(track.scrollWidth-track.clientWidth)*Number(value)/100;}
function syncStaffScroll(track){const slider=document.querySelector('.staff-mobile-scroll input');if(slider)slider.value=track.scrollWidth>track.clientWidth?100*track.scrollLeft/(track.scrollWidth-track.clientWidth):0;}

function setActivityScroll(value){const track=document.getElementById('activities-carousel');if(track)track.scrollLeft=(track.scrollWidth-track.clientWidth)*Number(value)/100;}
function syncActivityScroll(track){const slider=document.querySelector('.activities-scroll-controls input');if(slider){slider.value=track.scrollWidth>track.clientWidth?100*track.scrollLeft/(track.scrollWidth-track.clientWidth):0;}}

let attendanceMonthDraft=new Set(),attendanceMonthYear=new Date().getFullYear();
function openAttendanceMonths(){attendanceMonthDraft=new Set(attendanceRateMonth.split(',').filter(Boolean));attendanceMonthYear=Number([...attendanceMonthDraft][0]?.slice(0,4))||new Date().getFullYear();modal('対象月を選択',`<p>月を複数選び、「この期間で表示」で確定してください。年を切り替えても選択は残ります。</p><div class="toolbar"><button type="button" class="outline small" aria-label="前年" onclick="attendanceMonthYear--;renderAttendanceMonths()">前年</button><b id="attendance-month-year"></b><button type="button" class="outline small" aria-label="翌年" onclick="attendanceMonthYear++;renderAttendanceMonths()">翌年</button></div><div id="attendance-month-options" class="attendance-month-options"></div><p id="attendance-month-selection" aria-live="polite"></p><div class="registration-actions"><button type="button" class="outline" onclick="attendanceMonthDraft.clear();renderAttendanceMonths()">全期間を選択</button><button type="button" class="lime" onclick="applyAttendanceMonths()">この期間で表示</button></div>`);renderAttendanceMonths();}
function renderAttendanceMonths(){document.getElementById('attendance-month-year').textContent=attendanceMonthYear+'年';document.getElementById('attendance-month-options').innerHTML=Array.from({length:12},(_,i)=>{const m=attendanceMonthYear+'-'+String(i+1).padStart(2,'0');return `<label><input type="checkbox" value="${m}" ${attendanceMonthDraft.has(m)?'checked':''} onchange="toggleAttendanceMonth(this)"><span>${i+1}月</span></label>`}).join('');updateAttendanceMonthSelection();}
function updateAttendanceMonthSelection(){document.getElementById('attendance-month-selection').textContent=attendanceMonthDraft.size?'選択中：'+[...attendanceMonthDraft].sort().join('、'):'全期間';}
function toggleAttendanceMonth(input){if(input.checked)attendanceMonthDraft.add(input.value);else attendanceMonthDraft.delete(input.value);updateAttendanceMonthSelection();}
function applyAttendanceMonths(){attendanceRateMonth=[...attendanceMonthDraft].sort().join(',');document.getElementById('modal').close();dashboard();}

function trialReviewsSection(){const all=pub.trial_reviews||[],samplePhoto=pub.content.gallery||pub.content.hero||'/basketball-club/uploads/00000000000000000000000000000003.jpg';const group=(kind,title,samples)=>{const saved=all.filter(r=>r.kind===kind),rows=saved.length?saved:samples;return `<div class="review-group"><h3>${title}</h3>${saved.length?'':'<p class="hint">掲載イメージのサンプルです。実際の口コミではありません。</p>'}<div class="${kind==='member'?'staff-carousel member-review-carousel':'public-staff-grid'}" ${kind==='member'?'id="member-review-carousel" onscroll="syncMemberReviewScroll(this)" tabindex="0" aria-label="会員の口コミ"':''}>${rows.map(r=>`<article class="public-staff-card">${kind==='member'?`<img src="${r.sample?esc(samplePhoto):r.photo?'/basketball-club/api/review_photo?id='+encodeURIComponent(r.photo):''}" ${r.sample||r.photo?'':'hidden'} alt="${r.sample?'仮の活動写真':esc(r.name)+'さんの写真'}" loading="lazy">`:''}<div>${r.sample?'<span class="tag">サンプル</span>':''}<h4>${esc(r.name)} <small>（${r.age}歳）</small></h4>${kind==='member'?`<p><b>バスケ歴：</b>${esc(r.experience||'未記入')}</p>`:''}<p class="staff-comment">${esc(r.body)}</p></div></article>`).join('')}</div>${kind==='member'?'<div class="staff-mobile-scroll member-review-scroll"><input type="range" min="0" max="100" step="0.1" value="0" aria-label="会員の口コミの横スクロール" oninput="setMemberReviewScroll(this.value)"></div>':''}</div>`};return `<section class="section wrap" id="reviews"><div class="section-title"><div><div class="eng">VOICES</div><h2>体験者・会員の口コミ</h2></div></div>${group('trial','体験者の口コミ',[{sample:true,name:'体験者A',age:8,body:'初めてでもコーチが優しく教えてくれて、楽しく参加できました。'},{sample:true,name:'体験者B',age:12,body:'みんなが声をかけてくれて安心しました。また練習に参加したいです。'}])}${group('member','会員の口コミ',[{sample:true,name:'会員A',age:10,experience:'2年',body:'仲間と練習する時間が楽しみです。できなかったシュートが入るようになってうれしいです。'},{sample:true,name:'会員B',age:13,experience:'5年',body:'自分の目標を決めて練習しています。仲間と声をかけ合うことの大切さを学びました。'}])}</section>`;}
function trialReviewsEditor(){if(!adminFull())return '';const rows=data.trial_reviews||[],labels={invited:'投稿待ち',pending:'公開確認待ち',published:'公開中',hidden:'非公開',revoked:'URL無効'};return `<details class="card"><summary><b>体験者・会員の口コミを管理</b></summary><p><button type="button" class="lime" onclick="reviewEditForm()">＋ 会員の口コミを追加</button></p><p>専用URLを発行して本人へ渡してください。URLは30日間・1回限り有効です。投稿は管理者が公開するまで表示されません。</p><form onsubmit="createReviewInvite(event)">${selectField('口コミの種類','kind',[['trial','体験者（写真なし）'],['member','会員（写真・バスケ歴あり）']],'trial')}${field('管理用メモ（公開されません）','label','','text',false)}<div class="error" role="alert"></div><button class="lime">投稿URLを発行</button></form>${rows.map(r=>`<article class="review-admin-row"><b>${esc(r.label||'口コミ投稿URL')}</b> <span class="tag">${r.kind==='member'?'会員':'体験者'}・${labels[r.status]}</span>${r.status==='invited'?`<label class="field">渡すURL<input readonly value="${esc(location.origin+'/#trial-review?token='+r.token)}" onclick="this.select()"></label><p class="hint">有効期限：${new Date(r.expires*1000).toLocaleDateString('ja-JP')}</p>`:`<h4>${esc(r.name)} ${r.age?r.age+'歳':''}</h4>${r.photo?`<img class="review-preview-photo" src="/basketball-club/api/review_photo?id=${encodeURIComponent(r.photo)}" alt="投稿写真">`:''}<p>${esc(r.experience||'')}</p><p class="staff-comment">${esc(r.body)}</p>`}<div class="toolbar">${['pending','hidden'].includes(r.status)?`<button class="lime" onclick="manageReview('${r.id}',${r.revision},'publish',this)">公開する</button>`:''}${r.status==='published'?`<button class="outline" onclick="manageReview('${r.id}',${r.revision},'hide',this)">非公開にする</button>`:''}${r.status==='invited'?`<button class="outline" onclick="manageReview('${r.id}',${r.revision},'revoke',this)">URLを無効にする</button>`:''}${['pending','published','hidden'].includes(r.status)?`<button class="outline" onclick="reviewEditForm('${r.id}')">編集</button>`:''}<button class="outline danger" onclick="manageReview('${r.id}',${r.revision},'delete',this)">削除</button></div></article>`).join('')}</details>`;}
async function createReviewInvite(ev){ev.preventDefault();await submit(ev,'trial_review_admin',{action:'create',...Object.fromEntries(new FormData(ev.target))},'口コミ投稿URLを発行しました。');}
async function manageReview(id,revision,action,button){if(action==='delete'&&!await confirmAction('口コミを削除しますか？','投稿URLと口コミを削除します。'))return;button.disabled=true;try{await api('trial_review_admin',{id,revision,action});await refresh();toast('口コミを更新しました。');}catch(e){toast(e.message);button.disabled=false;}}
async function trialReviewPage(){const token=new URLSearchParams(location.hash.split('?')[1]||'').get('token')||'';accountScreen('口コミの投稿','<p>投稿URLを確認しています。</p>');try{const info=await api('trial_review_invite?token='+encodeURIComponent(token));if(page!=='trial-review')return;accountScreen(info.kind==='member'?'会員の口コミ':'体験の口コミ',`<p>投稿した内容は管理者が確認後、公開します。表示名はニックネームでも構いません。</p><form onsubmit="sendTrialReview(event)"><input type="hidden" name="token" value="${esc(token)}">${field('公開する名前・ニックネーム','name','')}${field('体験者・会員本人の年齢','age','','number')}${info.kind==='member'?`${field('バスケ歴（例：2年）','experience','','text',false)}<label class="field">写真（任意・5MB以下）<input type="file" name="photo" accept="image/jpeg,image/png,image/webp"></label>`:''}<label class="field">口コミ<textarea name="body" maxlength="2000" required rows="5"></textarea></label><label class="check-row"><input type="checkbox" name="consent" required>表示名・年齢・口コミ${info.kind==='member'?'・バスケ歴・写真':''}の公開に同意します。未成年の方は保護者の同意を得てください。</label><div class="error" role="alert"></div><div class="registration-actions"><button class="lime">口コミを送信</button></div></form>`);}catch(e){if(page==='trial-review')accountScreen('口コミの投稿',`<p>${esc(e.message)}</p>`);}}
async function sendTrialReview(ev){ev.preventDefault();const button=ev.submitter;button.disabled=true;try{const form=new FormData(ev.target),payload=Object.fromEntries(form);payload.consent=form.get('consent')==='on';delete payload.photo;const file=ev.target.querySelector('[name=photo]')?.files[0];if(file){if(file.size>5*1024*1024)throw Error('写真は5MB以下にしてください。');payload.photo={name:file.name,content:await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);})};}await api('trial_review_submit',payload);accountScreen('送信しました','<p>口コミをお寄せいただきありがとうございます。管理者が確認してから公開します。</p><a class="btn outline" href="#home">トップページへ戻る</a>');}catch(e){ev.target.querySelector('.error').textContent=e.message;button.disabled=false;}}

function setMemberReviewScroll(value){const t=document.getElementById('member-review-carousel');if(t)t.scrollLeft=(t.scrollWidth-t.clientWidth)*Number(value)/100;}
function syncMemberReviewScroll(t){const input=document.querySelector('.member-review-scroll input');if(input)input.value=t.scrollWidth>t.clientWidth?t.scrollLeft/(t.scrollWidth-t.clientWidth)*100:0;}
function reviewEditForm(id){const r=(data.trial_reviews||[]).find(r=>r.id===id)||{kind:'member'};modal(id?'口コミを編集':'会員の口コミを追加',`<form onsubmit="saveReviewEdit(event)"><input type="hidden" name="id" value="${esc(r.id||'')}"><input type="hidden" name="revision" value="${r.revision||0}">${field('公開する名前','name',r.name||'')}${field('年齢','age',r.age||'','number')}${r.kind==='member'?`${field('バスケ歴','experience',r.experience||'','text',false)}${r.photo?`<img class="review-preview-photo" src="/basketball-club/api/review_photo?id=${encodeURIComponent(r.photo)}" alt="現在の写真"><label class="check-row"><input type="checkbox" name="remove_photo">現在の写真を削除する</label>`:''}<label class="field">写真（1枚・5MB以下）<input type="file" name="photo" accept="image/jpeg,image/png,image/webp"></label>`:''}<label class="field">口コミ<textarea name="body" maxlength="2000" rows="5" required>${esc(r.body||'')}</textarea></label><p class="hint">${id?'公開状態はそのままで内容を更新します。':'追加後は非公開で保存します。内容を確認してから公開してください。'}</p><div class="error" role="alert"></div><button class="lime">保存する</button></form>`);}
async function saveReviewEdit(ev){ev.preventDefault();const f=ev.target,b=ev.submitter;b.disabled=true;try{const values=Object.fromEntries(new FormData(f)),payload={action:values.id?'edit':'add',id:values.id,revision:Number(values.revision),name:values.name,age:values.age,body:values.body,experience:values.experience||'',remove_photo:values.remove_photo==='on'};const file=f.querySelector('[name=photo]')?.files[0];if(file){if(file.size>5*1024*1024)throw Error('写真は5MB以下にしてください。');payload.photo={name:file.name,content:await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);})};}await api('trial_review_admin',payload);$('#modal').close();await refresh();toast('口コミを保存しました。');}catch(e){f.querySelector('.error').textContent=e.message;b.disabled=false;}}
